// Handlers import these caps so they enforce what the schemas advertise, for input arrays and output rows.

const GRAPH_REF_ARRAY_MAX_ITEMS = 500;
const IGNORE_ARRAY_MAX_ITEMS = 200;
const SOURCE_FOLDER_ARRAY_MAX_ITEMS = 50;
const MEANING_GATE_EVIDENCE_ROW_LIMIT = 5;
const MEANING_GATE_REVIEW_ROW_LIMIT = 5;

export {
  GRAPH_REF_ARRAY_MAX_ITEMS,
  IGNORE_ARRAY_MAX_ITEMS,
  SOURCE_FOLDER_ARRAY_MAX_ITEMS,
  MEANING_GATE_EVIDENCE_ROW_LIMIT,
  MEANING_GATE_REVIEW_ROW_LIMIT,
};
