import {expect,test,type Page} from '@playwright/test';
import {installDesktopRailRuntime} from './desktop-rail-arrival-harness';
import {sectorWalkable,SECTOR_CURIO,SECTOR_EXIT,SECTOR_GATE,SECTOR_MOTE_PATH,SECTOR_TERMINAL,type SectorDirection,type SectorPoint} from '../../src/features/agent-activity/model/companion-sector';

const files={
 'capabilities/invoice-validation.md':'---\nuid: 30000000-0000-4000-8000-000000000001\nkind: capability\ntitle: Invoice validation\ndomain: domains/orders\n---\nChecks invoice totals before posting.\n\n## Excludes\nDoes not approve credit or establish tax correctness.\n',
 'capabilities/invoice-posting.md':'---\nuid: 30000000-0000-4000-8000-000000000002\nkind: capability\ntitle: Invoice posting\ndomain: domains/orders\ndependencies: [capabilities/invoice-validation]\nrelation_notes:\n  capabilities/invoice-validation: Posting needs the totals check.\n---\nPosts invoices after validating totals.\n',
};
const moves:[SectorDirection,string,number,number][]=[['up','ArrowUp',0,-1],['right','ArrowRight',1,0],['down','ArrowDown',0,1],['left','ArrowLeft',-1,0]];
function path(from:SectorPoint,to:SectorPoint,gateOpen:boolean,mote:SectorPoint|null):string[]{
 const queue:[SectorPoint,string[]][]=[[from,[]]],seen=new Set([`${from.x},${from.y}`]);
 while(queue.length){const [point,route]=queue.shift()!;if(Math.abs(point.x-to.x)+Math.abs(point.y-to.y)<=1)return route;
  for(const [,key,dx,dy] of moves){const next={x:point.x+dx,y:point.y+dy},id=`${next.x},${next.y}`;if(!seen.has(id)&&sectorWalkable(next,gateOpen)&&!(mote?.x===next.x&&mote.y===next.y)){seen.add(id);queue.push([next,[...route,key]]);}}
 }throw new Error('No route to objective');
}
async function walkTo(page:Page,target:SectorPoint){const sector=page.getByTestId('companion-sector');const start={x:Number(await sector.getAttribute('data-x')),y:Number(await sector.getAttribute('data-y'))},hits=Number(await sector.getAttribute('data-mote-hits'));const route=path(start,target,await sector.getAttribute('data-gate-open')==='true',hits<3?SECTOR_MOTE_PATH[hits]:null);for(const key of route)await page.keyboard.press(key);await expect.poll(async()=>Math.abs(Number(await sector.getAttribute('data-x'))-target.x)+Math.abs(Number(await sector.getAttribute('data-y'))-target.y)).toBe(1);}
async function enter(page:Page){await installDesktopRailRuntime(page,files);await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/en/?guides=off&e2e=1');await page.getByTestId('first-run-open').click();await page.getByTestId('companion-trigger').click();const dialog=page.getByTestId('companion-journal');const receipt=dialog.getByRole('button',{name:'Continue the adventure'});if(await receipt.isVisible())await receipt.click();await expect(dialog.getByTestId('companion-world')).toBeFocused();await page.keyboard.press('m');await dialog.getByRole('button',{name:'Explore on foot · WASD'}).click();await expect(dialog.getByTestId('companion-sector')).toBeVisible();await expect(dialog.getByTestId('companion-sector-stage')).toBeFocused();return dialog;}

test('keyboard expedition requires meeting Curio and a current project reflection before exiting',async({page})=>{
 const dialog=await enter(page);const sector=dialog.getByTestId('companion-sector');
 await walkTo(page,SECTOR_GATE);await page.keyboard.press('e');await expect(sector.getByRole('status')).toContainText('Meet Curio');await expect(sector).toHaveAttribute('data-gate-open','false');
 await walkTo(page,SECTOR_CURIO);await page.keyboard.press('e');await expect(sector.getByRole('status')).toContainText('Curio trusts you');
 await walkTo(page,SECTOR_GATE);await page.keyboard.press('e');await expect(sector.getByRole('status')).toContainText('signal mote');await expect(sector).toHaveAttribute('data-gate-open','false');
 for(const point of SECTOR_MOTE_PATH){await walkTo(page,point);await page.keyboard.press('e');}await expect(sector.getByRole('status')).toContainText('mote settled');
 await walkTo(page,SECTOR_GATE);await page.keyboard.press('e');await expect(sector.getByRole('status')).toContainText('saved reflection');
 await walkTo(page,SECTOR_TERMINAL);await page.keyboard.press('e');const learning=dialog.getByTestId('companion-learning');await expect(learning).toBeVisible();await learning.getByRole('button',{name:'Invoice validation',exact:true}).click();await dialog.getByRole('button',{name:'Continue after reading',exact:true}).click();await dialog.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await dialog.getByRole('button',{name:'Explain in your own words',exact:true}).click();await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill('Validation checks invoice totals; tax correctness still needs its own evidence.');await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(learning).toHaveAttribute('data-step','done');
 await page.keyboard.press('Escape');await expect(dialog.getByTestId('companion-overlay')).toBeHidden();await expect(dialog.getByTestId('companion-sector-stage')).toBeFocused();await expect(sector.getByRole('status')).not.toContainText('saved reflection');
 await walkTo(page,SECTOR_GATE);await page.keyboard.press('e');await expect(sector).toHaveAttribute('data-gate-open','true');await walkTo(page,SECTOR_EXIT);await page.keyboard.press('e');await expect(sector).toHaveAttribute('data-cleared','true');
 expect(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.startsWith('ontology-atlas:companion-sector:v1:')))).toBe(true);await page.keyboard.press('e');await expect(sector).toBeHidden();await expect(dialog.getByTestId('companion-world')).toBeFocused();
});

test('the direct map and controls fit without scrolling across desktop, phone and landscape',async({page})=>{
 const dialog=await enter(page);const sector=dialog.getByTestId('companion-sector');
 await page.evaluate(()=>document.querySelector('nextjs-portal')?.remove());
 for(const [width,height] of [[320,740],[390,844],[600,900],[768,1024],[834,1112],[844,390],[1024,768],[1440,900],[1512,900],[1920,1080],[2560,1440]]){
  await page.setViewportSize({width,height});const measure=await sector.evaluate(node=>{const b=node.getBoundingClientRect();const canvas=node.querySelector('canvas')!.getBoundingClientRect();const controls=Array.from(node.querySelectorAll('button')).map(el=>({element:el,name:el.getAttribute('aria-label')||el.textContent,rect:el.getBoundingClientRect()})).filter(item=>item.rect.width&&item.rect.height);return {overflowX:node.scrollWidth-node.clientWidth,overflowY:node.scrollHeight-node.clientHeight,canvasArea:canvas.width*canvas.height,outside:controls.filter(item=>item.rect.left<b.left-1||item.rect.right>b.right+1||item.rect.top<b.top-1||item.rect.bottom>b.bottom+1).map(item=>item.name),intercepted:controls.filter(item=>{const hit=document.elementFromPoint(item.rect.x+item.rect.width/2,item.rect.y+item.rect.height/2);return hit&&!item.element.contains(hit);}).map(item=>item.name),pad:controls.filter(item=>item.element.closest('[aria-label="Movement controls"]')).map(item=>({width:item.rect.width,height:item.rect.height}))};});console.log('SECTOR_FIT',width,height,measure);expect(measure.overflowX).toBeLessThanOrEqual(1);expect(measure.overflowY).toBeLessThanOrEqual(1);expect(measure.outside).toEqual([]);expect(measure.intercepted).toEqual([]);expect(measure.canvasArea).toBeGreaterThan(width*height*.25);if(width<=600)for(const target of measure.pad){expect(target.width).toBeGreaterThanOrEqual(44);expect(target.height).toBeGreaterThanOrEqual(44);}
  if(width===1512||width===390||width===844)await sector.screenshot({path:`output/playwright/sector-${width}x${height}.png`});
 }
});

test('a failed sector save does not invent movement and can be explicitly restarted',async({page})=>{
 const dialog=await enter(page),sector=dialog.getByTestId('companion-sector');
 await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as unknown as {restoreSectorStorage:()=>void}).restoreSectorStorage=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith('ontology-atlas:companion-sector:v1:'))throw new Error('full');return original.call(this,key,value);};});
 await page.keyboard.press('ArrowRight');await expect(sector).toHaveAttribute('data-x','3');await expect(sector.getByRole('status')).toContainText('could not be saved');
 await page.evaluate(()=>(window as unknown as {restoreSectorStorage:()=>void}).restoreSectorStorage());await sector.getByRole('button',{name:'Retry saving'}).click();await expect(sector.getByRole('status')).toContainText('Saving works again');
 await sector.getByTestId('companion-sector-stage').focus();await page.keyboard.press('ArrowRight');await expect(sector).toHaveAttribute('data-x','4');
});

test('an unreadable sector save waits for an explicit reset and leaves combat data intact',async({page})=>{
 const dialog=await enter(page);await page.keyboard.press('ArrowRight');const before=await page.evaluate(()=>{const sector=Object.keys(localStorage).find(key=>key.startsWith('ontology-atlas:companion-sector:v1:'))!,game=Object.keys(localStorage).find(key=>key.startsWith('ontology-atlas:companion-game:v1:'))!;const combat=JSON.parse(localStorage.getItem(game)!);localStorage.setItem(sector,'{bad');return {sector,game,combat:{wins:combat.wins,gold:combat.gold,xp:combat.xp,questClaims:combat.questClaims}};});
 await dialog.getByRole('button',{name:'Return',exact:true}).click();await page.getByTestId('companion-journal').getByRole('button',{name:'Close game'}).click();await page.getByTestId('companion-trigger').click();const reopened=page.getByTestId('companion-journal');await expect(reopened.getByTestId('companion-world')).toBeFocused();await page.keyboard.press('m');await reopened.getByRole('button',{name:'Explore on foot · WASD'}).click();const sector=reopened.getByTestId('companion-sector');await expect(sector.getByRole('button',{name:'Reset sector save'})).toBeVisible();await sector.getByRole('button',{name:'Reset sector save'}).click();await expect(sector.getByRole('status')).toContainText('Restart this sector?');expect(await page.evaluate(key=>localStorage.getItem(key),before.sector)).toBe('{bad');await sector.getByRole('button',{name:'Cancel'}).click();expect(await page.evaluate(key=>localStorage.getItem(key),before.sector)).toBe('{bad');await sector.getByRole('button',{name:'Reset sector save'}).click();await sector.getByRole('button',{name:'Confirm sector reset'}).click();await expect(sector).toHaveAttribute('data-x','3');expect(await page.evaluate(key=>{const state=JSON.parse(localStorage.getItem(key)!);return {wins:state.wins,gold:state.gold,xp:state.xp,questClaims:state.questClaims};},before.game)).toEqual(before.combat);
});

test('Tab and Shift+Tab keep visible focus in the sector and its open panel',async({page})=>{
 const dialog=await enter(page),sector=dialog.getByTestId('companion-sector');
 const focus=()=>page.evaluate(()=>{const el=document.activeElement as HTMLElement;const rect=el.getBoundingClientRect(),style=getComputedStyle(el);return {label:el.getAttribute('aria-label')||el.textContent?.slice(0,40)||el.tagName,inGame:Boolean(el.closest('[data-testid="companion-growth"]')),inSector:Boolean(el.closest('[data-testid="companion-sector"]')),inPanel:Boolean(el.closest('[data-testid="companion-overlay"]')),visible:rect.width>0&&rect.height>0&&style.visibility!=='hidden'&&!el.closest('[inert]')};});
 for(const [index,key] of ['Tab','Tab','Tab','Tab','Tab','Tab','Shift+Tab','Shift+Tab','Shift+Tab'].entries()){await page.keyboard.press(key);const state=await focus();expect(state.inSector,`step ${index} ${key} ${JSON.stringify(state)}`).toBe(true);expect(state.visible,`step ${index} ${key} ${JSON.stringify(state)}`).toBe(true);}
 await page.emulateMedia({reducedMotion:'no-preference'});await sector.getByTestId('companion-sector-stage').focus();await page.keyboard.press('i');await page.keyboard.press('Tab');expect((await focus()).inGame).toBe(true);await expect(dialog.getByTestId('companion-overlay')).toHaveAttribute('data-surface-state','entered');for(let i=0;i<8;i++){await page.keyboard.press('Tab');const state=await focus();expect(state.inPanel,`panel Tab ${i}`).toBe(true);expect(state.visible,`panel Tab ${i}`).toBe(true);}
 await page.keyboard.press('Escape');await page.keyboard.press('Tab');expect((await focus()).inGame).toBe(true);await expect(dialog.getByTestId('companion-overlay')).toBeHidden();await expect(sector.getByTestId('companion-sector-stage')).toBeFocused();
});

test('touch movement and enlarged text keep the sector controls reachable',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:844,height:390}}),page=await context.newPage();
 try{const dialog=await enter(page),sector=dialog.getByTestId('companion-sector');await page.evaluate(()=>document.querySelector('nextjs-portal')?.remove());
  const right=sector.getByRole('button',{name:'Move right'});await expect(right).toBeVisible();await right.tap();await expect(sector).toHaveAttribute('data-x','4');
  for(const [width,height] of [[844,390],[390,844],[320,740]]){await page.setViewportSize({width,height});const metrics=await sector.evaluate(node=>{const b=node.getBoundingClientRect();const targets=Array.from(node.querySelectorAll('button')).filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&r.height>0;});return {overflow:[node.scrollWidth-node.clientWidth,node.scrollHeight-node.clientHeight],outside:targets.filter(el=>{const r=el.getBoundingClientRect();return r.left<b.left-1||r.right>b.right+1||r.top<b.top-1||r.bottom>b.bottom+1;}).map(el=>el.getAttribute('aria-label')||el.textContent),intercepted:targets.filter(el=>{const r=el.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit&&!el.contains(hit);}).map(el=>el.getAttribute('aria-label')||el.textContent),small:targets.filter(el=>{const r=el.getBoundingClientRect();return r.width<44||r.height<44;}).map(el=>el.getAttribute('aria-label')||el.textContent)};});console.log('SECTOR_TOUCH',width,height,metrics);expect(metrics.overflow.every(value=>value<=1)).toBe(true);expect(metrics.outside).toEqual([]);expect(metrics.intercepted).toEqual([]);expect(metrics.small).toEqual([]);}
  await page.setViewportSize({width:390,height:844});await sector.getByRole('button',{name:/Scan/}).tap();await expect(sector.locator('[role="status"]:visible').filter({hasText:'Route to Curio'})).toContainText('Start');await sector.getByRole('button',{name:/Interact/}).tap();await expect(sector.locator('[role="status"]:visible').filter({hasText:'Move next to a character or device, then press E.'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await expect(sector).toHaveAttribute('data-enlarged','true');const zoom=await sector.evaluate(node=>({overflow:[node.scrollWidth-node.clientWidth,node.scrollHeight-node.clientHeight],map:node.querySelector('canvas')!.getBoundingClientRect().toJSON(),children:Array.from(node.children).map(el=>({name:el.className,rect:el.getBoundingClientRect().toJSON(),scrollHeight:el.scrollHeight,clientHeight:el.clientHeight})),actions:Array.from(node.querySelectorAll('button')).map(el=>({label:el.getAttribute('aria-label')||el.textContent,rect:el.getBoundingClientRect().toJSON()})).filter(item=>item.rect.width&&item.rect.height)}));console.log('SECTOR_DOUBLE_TEXT',JSON.stringify(zoom));await sector.screenshot({path:'output/playwright/sector-double-text.png'});expect(zoom.overflow.every(value=>value<=1)).toBe(true);expect(zoom.map.height).toBeGreaterThan(100);await expect(sector.getByRole('button',{name:/Quests/})).toBeVisible();for(const action of zoom.actions){expect(action.rect.left).toBeGreaterThanOrEqual(0);expect(action.rect.right).toBeLessThanOrEqual(390);expect(action.rect.bottom).toBeLessThanOrEqual(844);}
 }finally{await context.close();}
});
