import {expect,test,type Page} from '@playwright/test';
import {installDesktopRailRuntime} from './desktop-rail-arrival-harness';
import {waitForBoxStill} from './settle';

const topicUid='30000000-0000-4000-8000-000000000001';
const files={
 'capabilities/invoice-validation.md':`---\nuid: ${topicUid}\nkind: capability\ntitle: Invoice validation\ndomain: domains/orders\n---\nChecks invoice totals before posting.\n\n## Excludes\nDoes not approve credit or establish tax correctness.\n`,
 'capabilities/invoice-posting.md':'---\nuid: 30000000-0000-4000-8000-000000000002\nkind: capability\ntitle: Invoice posting\ndomain: domains/orders\ndependencies: [capabilities/invoice-validation]\nrelation_notes:\n  capabilities/invoice-validation: Posting needs the totals check; tax correctness requires separate evidence.\n---\nPosts invoices after validating totals.\n',
 'capabilities/currency-formatting.md':'---\nuid: 30000000-0000-4000-8000-000000000003\nkind: capability\ntitle: Currency formatting\ndomain: domains/orders\n---\nFormats a currency label.\n\n## Excludes\nDoes not convert currencies.\n'
};
async function boot(page:Page,locale='en'){
 await installDesktopRailRuntime(page,files);await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`/${locale}/?guides=off&e2e=1`);await page.getByTestId('first-run-open').click();await page.getByTestId('companion-trigger').click();const dialog=page.getByTestId('companion-journal');const receipt=dialog.getByRole('button',{name:/Continue the adventure|모험 이어가기/});if(await receipt.isVisible())await receipt.click();await expect(dialog.getByTestId('companion-world')).toBeFocused();await page.keyboard.press('t');await expect(dialog.getByTestId('companion-learning')).toBeVisible();return dialog;
}
async function select(page:Page,title='Invoice validation'){await page.getByTestId('companion-learning').getByRole('button',{name:title,exact:true}).click();await expect(page.getByTestId('companion-learning')).toHaveAttribute('data-step','read');}
const growth=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem(Object.keys(localStorage).find(key=>key.startsWith('ontology-atlas:companion-growth:v1:'))!)!));
async function reflect(page:Page,unknown=false){
 await page.getByRole('button',{name:'Continue after reading',exact:true}).click();
 if(unknown)await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();
 else{await page.getByRole('radio',{name:/Invoice posting/}).click();await page.getByRole('button',{name:'Compare with the record',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'This matches the recorded direct relation.'})).toBeVisible();await page.getByRole('button',{name:'Continue',exact:true}).click();}
 await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();
}

test('a learning expedition exposes purpose, exclusion, directed declaration and a saved uncertain explanation',async({page})=>{
 const dialog=await boot(page);await select(page);await expect(dialog).toContainText('Checks invoice totals before posting.');await dialog.getByRole('radio',{name:'Boundary',exact:true}).click();await expect(dialog).toContainText('Does not approve credit or establish tax correctness.');await reflect(page);
 const note='Validation checks totals, not tax truth. Posting declares the dependency; code impact still needs evidence.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
 const rows=(await growth(page)).entries.filter((entry:{target:{uid:string}})=>entry.target.uid===topicUid);expect(rows).toHaveLength(2);expect(rows.find((entry:{kind:string})=>entry.kind==='reflected')).toMatchObject({note,reflection:'uncertain'});
 await dialog.getByRole('button',{name:'Choose another topic',exact:true}).click();await select(page);await reflect(page);await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();expect((await growth(page)).entries.filter((entry:{target:{uid:string}})=>entry.target.uid===topicUid)).toHaveLength(2);
});

test('the original dependency declaration can be inspected without leaving the learning step',async({page})=>{
 const dialog=await boot(page);await select(page);await dialog.getByRole('button',{name:'Continue after reading',exact:true}).click();await dialog.getByRole('button',{name:'Inspect the declaring document',exact:true}).click();const source=dialog.getByTestId('companion-source');await expect(source.getByTestId('companion-source-body')).toContainText('dependencies');await expect(source.getByTestId('companion-source-body')).toContainText('capabilities/invoice-validation');await page.keyboard.press('Escape');await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','relation');
});

test('missing dependency evidence remains unknown while draft closure and failed saves preserve the learner note',async({page})=>{
 const dialog=await boot(page);await select(page,'Currency formatting');await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await expect(dialog).toContainText('That does not establish that nothing depends on it.');await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await expect(dialog).toContainText('do not conclude “no impact.”');await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();
 const note='No direct dependency is recorded. This does not show that currency formatting has no impact.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.getByTestId('companion-trigger').click();await page.keyboard.press('t');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);
 await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as unknown as {restoreStorage:()=>void}).restoreStorage=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith('ontology-atlas:companion-growth:v1:'))throw new Error('quota');return original.call(this,key,value);};});await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','reflect');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);
 await expect(dialog.getByRole('alert').filter({hasText:'The note was not saved.'})).toBeVisible();await page.evaluate(()=>(window as unknown as {restoreStorage:()=>void}).restoreStorage());await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
});

async function fit(page:Page,coarse=false){
 await waitForBoxStill(page.getByTestId('companion-content'));
 const content=page.getByTestId('companion-content');await expect(page.getByTestId('companion-overlay')).toHaveAttribute('data-surface-state','entered');const measured=await content.evaluate(el=>{
  const b=el.getBoundingClientRect();const controls=Array.from(el.querySelectorAll('button,input,textarea')).map(element=>({element,r:element.getBoundingClientRect()})).filter(({r})=>r.width&&r.height);return {viewport:[innerWidth,innerHeight],bounds:b.toJSON(),x:el.scrollWidth-el.clientWidth,y:el.scrollHeight-el.clientHeight,controls:controls.map(({element,r})=>({label:element.getAttribute('aria-label')||element.textContent,width:r.width,height:r.height,outside:r.left<b.left-1||r.right>b.right+1||r.top<b.top-1||r.bottom>b.bottom+1,hits:!(element as HTMLButtonElement).disabled?[[r.x+r.width/2,r.y+r.height/2],[r.left+2,r.y+r.height/2],[r.right-2,r.y+r.height/2],[r.x+r.width/2,r.top+2],[r.x+r.width/2,r.bottom-2]].filter(([x,y])=>!element.contains(document.elementFromPoint(x,y))).map(([x,y])=>({x,y,target:document.elementFromPoint(x,y)?.outerHTML.slice(0,220)})):[],miss:!(element as HTMLButtonElement).disabled&&[[r.x+r.width/2,r.y+r.height/2],[r.left+2,r.y+r.height/2],[r.right-2,r.y+r.height/2],[r.x+r.width/2,r.top+2],[r.x+r.width/2,r.bottom-2]].some(([x,y])=>!element.contains(document.elementFromPoint(x,y)))}))};
 });
 console.log('LEARNING_FIT',JSON.stringify(measured));expect(measured.x).toBeLessThanOrEqual(1);expect(measured.y).toBeLessThanOrEqual(1);expect(measured.controls.length).toBeGreaterThan(0);for(const control of measured.controls){expect(control.outside,control.label??'control').toBe(false);expect(control.miss,control.label??'control').toBe(false);if(coarse){expect(control.width).toBeGreaterThanOrEqual(44);expect(control.height).toBeGreaterThanOrEqual(44);}}
}
for(const locale of ['en','ko'])for(const band of ['desktop','small'])test(`learning steps retain controls across ${locale} ${band} views`,async({page})=>{
 const dialog=await boot(page,locale);const labels=locale==='en'?{read:'Continue after reading',unknown:'Keep the evidence gap and continue',reflect:'Explain in your own words',note:'Your explanation',save:'Save exploration note',again:'Choose another topic'}:{read:'읽고 다음으로',unknown:'근거 부족을 남기고 계속',reflect:'내 말로 정리하기',note:'내 설명 또는 질문',save:'탐구 기록 저장',again:'다른 주제 고르기'};
 for(const [width,height] of (band==='small'?[[320,740],[390,844],[600,900],[844,390]]:[[768,1024],[834,1112],[1024,768],[1440,900],[1920,1080],[2560,1440]])){
  console.log('LEARNING_VIEWPORT',locale,width,height);await page.setViewportSize({width,height});await fit(page);await select(page);await expect(dialog.getByRole('button',{name:labels.read,exact:true})).toBeEnabled();await fit(page);await dialog.getByRole('button',{name:labels.read,exact:true}).click();await fit(page);await dialog.getByRole('button',{name:labels.unknown,exact:true}).click();await fit(page);await dialog.getByRole('button',{name:labels.reflect,exact:true}).click();await fit(page);await dialog.getByRole('textbox',{name:labels.note,exact:true}).fill('I can cite the direct declaration, but runtime impact and tax correctness need more evidence.');await dialog.getByRole('button',{name:labels.save,exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await fit(page);await dialog.getByRole('button',{name:labels.again,exact:true}).click();
 }
});

for(const mode of ['coarse','double-text'])test(`learning decision controls work with ${mode}`,async({browser})=>{
 const context=await browser.newContext({hasTouch:mode==='coarse',viewport:{width:1512,height:900}});const page=await context.newPage();const dialog=await boot(page);if(mode==='double-text')await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 for(const [width,height] of (mode==='coarse'?[[320,740],[844,390],[1512,900]]:[[1512,900]])){
  await page.setViewportSize({width,height});await fit(page,mode==='coarse');await select(page);await expect(page.getByRole('button',{name:'Continue after reading',exact:true})).toBeEnabled();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();await fit(page,mode==='coarse');await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill('Further source evidence is needed.');await page.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await fit(page,mode==='coarse');await page.getByRole('button',{name:'Choose another topic',exact:true}).click();
 }
 await context.close();
});

test('completion rechecks the saved source instead of trusting the earlier lesson snapshot',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page);const note='This note must not be completed against changed evidence.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);
 await page.evaluate(()=>{const bridge=(window as unknown as {__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}}).__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const value=await original(command,args);if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md'){const file=value as {lastModified:number};return {...file,lastModified:file.lastModified+1000};}return value;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByRole('alert').filter({hasText:'Not saved: evidence changed or unreadable.'})).toBeVisible();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','reflect');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);expect((await growth(page)).entries.some((entry:{kind:string;target:{uid:string}})=>entry.kind==='reflected'&&entry.target.uid===topicUid)).toBe(false);
});

test('learning steps expose a nonempty accessible reading and reflection journey',async({page})=>{
 const dialog=await boot(page);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 const scan=async()=>{const result=await page.evaluate(async()=>{const result=await (window as unknown as {axe:{run:(element:Element,options:unknown)=>Promise<{passes:unknown[];violations:unknown[]}>}}).axe.run(document.querySelector('[data-testid="companion-journal"]')!,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}});return {passes:result.passes.length,violations:result.violations};});console.log('LEARNING_AXE',JSON.stringify(result));expect(result.passes).toBeGreaterThan(0);expect(result.violations).toEqual([]);};
 await scan();await select(page);await expect(dialog.getByRole('button',{name:'Continue after reading',exact:true})).toBeEnabled();await scan();await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await scan();await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await scan();await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();await scan();await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(('My question about the declaration and its limits.\n').repeat(5).slice(0,240));await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await scan();for(const [width,height] of [[390,844],[844,390]]){await page.setViewportSize({width,height});await fit(page);}
});

test('reflection selection stays consistent while current source verification is pending',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill('The direct declaration is known; runtime consequences need evidence.');
 await page.evaluate(()=>{const bridge=(window as unknown as {__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>};releaseLearningRead?:()=>void}).__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const value=await original(command,args);if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md')await new Promise<void>(resolve=>{(window as unknown as {releaseLearningRead:()=>void}).releaseLearningRead=resolve;});return value;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();const learned=dialog.getByRole('radio',{name:'I learned something',exact:true});await expect(learned).toHaveAttribute('aria-disabled','true');await learned.focus();await page.keyboard.press('Space');await expect(dialog.getByRole('radio',{name:'I still have a question',exact:true})).toHaveAttribute('aria-checked','true');await page.waitForFunction(()=>Boolean((window as unknown as {releaseLearningRead?:()=>void}).releaseLearningRead));await page.evaluate(()=>(window as unknown as {releaseLearningRead:()=>void}).releaseLearningRead());await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');expect((await growth(page)).entries.find((entry:{kind:string;target:{uid:string}})=>entry.kind==='reflected'&&entry.target.uid===topicUid).reflection).toBe('uncertain');
});

test('an unchanged vault refresh preserves the learner field and focus while source handles are renewed',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);const field=dialog.getByRole('textbox',{name:'Your explanation',exact:true});await field.fill('Keep this draft and its focus during a same-version refresh.');
 await page.evaluate(()=>{const state=window as unknown as {learningRefreshReads:number;learningFocusLost:boolean;__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}};state.learningRefreshReads=0;state.learningFocusLost=false;const field=document.querySelector('[data-testid="companion-learning"] textarea')!;new MutationObserver(()=>{if(!field.isConnected)state.learningFocusLost=true;}).observe(document.querySelector('[data-testid="companion-learning"]')!,{childList:true,subtree:true});const bridge=state.__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const result=await original(command,args);if(command==='vault_fingerprint')return String(result)+'-refresh';if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md')state.learningRefreshReads++;return result;};window.dispatchEvent(new Event('focus'));});
 await expect.poll(()=>page.evaluate(()=>(window as unknown as {learningRefreshReads:number}).learningRefreshReads)).toBeGreaterThan(0);await expect(field).toBeFocused();await expect(field).toHaveValue('Keep this draft and its focus during a same-version refresh.');expect(await page.evaluate(()=>(window as unknown as {learningFocusLost:boolean}).learningFocusLost)).toBe(false);
});

test('renewing unchanged file handles does not cancel an in-flight reflection save',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);const field=dialog.getByRole('textbox',{name:'Your explanation',exact:true});await field.fill('A current direct declaration needs separate runtime evidence.');
 await page.evaluate(()=>{const state=window as unknown as {verificationReads:number;releaseVerification?:()=>void;__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}};state.verificationReads=0;const bridge=state.__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const result=await original(command,args);if(command==='vault_fingerprint')return String(result)+'-during-save';if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md'){state.verificationReads++;if(state.verificationReads===1)await new Promise<void>(resolve=>{state.releaseVerification=resolve;});}return result;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(field).toBeDisabled();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect.poll(()=>page.evaluate(()=>(window as unknown as {verificationReads:number}).verificationReads)).toBeGreaterThanOrEqual(2);await waitForBoxStill(dialog.getByTestId('companion-content'));await expect(field).toBeDisabled();await page.evaluate(()=>(window as unknown as {releaseVerification:()=>void}).releaseVerification());await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
});
