import {expect,test,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {installDesktopRailRuntime} from './desktop-rail-arrival-harness';
import {waitForBoxStill} from './settle';

const topicUid='30000000-0000-4000-8000-000000000001';
const files={
 'capabilities/invoice-validation.md':`---\nuid: ${topicUid}\nkind: capability\ntitle: Invoice validation\ndomain: domains/orders\n---\nChecks invoice totals before posting.\n\n## Excludes\nDoes not approve credit or establish tax correctness.\n`,
 'capabilities/invoice-posting.md':'---\nuid: 30000000-0000-4000-8000-000000000002\nkind: capability\ntitle: Invoice posting\ndomain: domains/orders\ndependencies: [capabilities/invoice-validation]\nrelation_notes:\n  capabilities/invoice-validation: Posting needs the totals check; tax correctness requires separate evidence.\n---\nPosts invoices after validating totals.\n',
 'capabilities/currency-formatting.md':'---\nuid: 30000000-0000-4000-8000-000000000003\nkind: capability\ntitle: Currency formatting\ndomain: domains/orders\n---\nFormats a currency label.\n\n## Excludes\nDoes not convert currencies.\n'
};
async function boot(page:Page,locale='en'){
 await installDesktopRailRuntime(page,files);await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`/${locale}/?guides=off&e2e=1`);await page.getByTestId('first-run-open').click();await page.getByTestId('companion-trigger').click();const dialog=page.getByTestId('companion-journal');const receipt=dialog.getByRole('button',{name:/Continue the adventure|모험 이어가기/});if(await receipt.isVisible())await receipt.click();await expect(dialog.getByTestId('companion-world')).toBeFocused();await page.keyboard.press('t');await expect(dialog.getByTestId('companion-learning')).toBeVisible();return dialog;
}
async function select(page:Page,title='Invoice validation'){const panel=page.getByTestId('companion-learning');await panel.getByRole('button',{name:title,exact:true}).click();await expect(panel).toHaveAttribute('data-step',/^(read|recall)$/);if(await panel.getAttribute('data-step')==='recall')await panel.getByRole('button',{name:/^Explore again$|^다시 탐구하기$/}).click();await expect(panel).toHaveAttribute('data-step','read');}
const growth=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem(Object.keys(localStorage).find(key=>key.startsWith('ontology-atlas:companion-growth:v1:'))!)!));
async function reflect(page:Page,unknown=false){
 await page.getByRole('button',{name:'Continue after reading',exact:true}).click();
 if(unknown)await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();
 else{await page.getByRole('radio',{name:/Invoice posting/}).click();await page.getByRole('button',{name:'Compare with the record',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'This matches the recorded direct relation.'})).toBeVisible();await page.getByRole('button',{name:'Continue',exact:true}).click();}
 await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();
}

test('a learning expedition exposes purpose, exclusion, directed declaration and a saved uncertain explanation',async({page})=>{
 const dialog=await boot(page);await select(page);await expect(dialog).toContainText('Checks invoice totals before posting.');await dialog.getByRole('radio',{name:'Boundary',exact:true}).click();await expect(dialog).toContainText('Does not approve credit or establish tax correctness.');await reflect(page);
 const note='Validation checks totals, not tax truth. Posting declares the dependency; code impact still needs evidence.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
 const rows=(await growth(page)).entries.filter((entry:{target:{uid:string}})=>entry.target.uid===topicUid);expect(rows).toHaveLength(2);expect(rows.find((entry:{kind:string})=>entry.kind==='reflected')).toMatchObject({note,reflection:'uncertain'});
 await dialog.getByRole('button',{name:'Choose another topic',exact:true}).click();await select(page);await reflect(page);await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();expect((await growth(page)).entries.filter((entry:{target:{uid:string}})=>entry.target.uid===topicUid)).toHaveLength(2);
});

test('the original dependency declaration can be inspected without leaving the learning step',async({page})=>{
 const dialog=await boot(page);await select(page);await dialog.getByRole('button',{name:'Continue after reading',exact:true}).click();await dialog.getByRole('button',{name:'Inspect the declaring document',exact:true}).click();const source=dialog.getByTestId('companion-source');await expect(source.getByTestId('companion-source-body')).toContainText('dependencies');await expect(source.getByTestId('companion-source-body')).toContainText('capabilities/invoice-validation');await page.keyboard.press('Escape');await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','relation');
});

test('missing dependency evidence remains unknown while draft closure and failed saves preserve the learner note',async({page})=>{
 const dialog=await boot(page);await select(page,'Currency formatting');await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await expect(dialog).toContainText('That does not establish that nothing depends on it.');await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await expect(dialog).toContainText('do not conclude “no impact.”');await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();
 const note='No direct dependency is recorded. This does not show that currency formatting has no impact.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.getByTestId('companion-trigger').click();await page.keyboard.press('t');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);
 await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as unknown as {restoreStorage:()=>void}).restoreStorage=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.startsWith('ontology-atlas:companion-growth:v1:'))throw new Error('quota');return original.call(this,key,value);};});await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','reflect');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);
 await expect(dialog.getByRole('alert').filter({hasText:'The note was not saved.'})).toBeVisible();await page.evaluate(()=>(window as unknown as {restoreStorage:()=>void}).restoreStorage());await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
});

async function fit(page:Page,coarse=false){
 await waitForBoxStill(page.getByTestId('companion-content'));
 const content=page.getByTestId('companion-content');await expect(page.getByTestId('companion-overlay')).toHaveAttribute('data-surface-state','entered');const measured=await content.evaluate(el=>{
  const b=el.getBoundingClientRect();const controls=Array.from(el.querySelectorAll('button,input,textarea')).map(element=>({element,r:element.getBoundingClientRect()})).filter(({r})=>r.width&&r.height);return {viewport:[innerWidth,innerHeight],bounds:b.toJSON(),x:el.scrollWidth-el.clientWidth,y:el.scrollHeight-el.clientHeight,controls:controls.map(({element,r})=>({label:element.getAttribute('aria-label')||element.textContent,width:r.width,height:r.height,outside:r.left<b.left-1||r.right>b.right+1||r.top<b.top-1||r.bottom>b.bottom+1,hits:!(element as HTMLButtonElement).disabled?[[r.x+r.width/2,r.y+r.height/2],[r.left+2,r.y+r.height/2],[r.right-2,r.y+r.height/2],[r.x+r.width/2,r.top+2],[r.x+r.width/2,r.bottom-2]].filter(([x,y])=>!element.contains(document.elementFromPoint(x,y))).map(([x,y])=>({x,y,target:document.elementFromPoint(x,y)?.outerHTML.slice(0,220)})):[],miss:!(element as HTMLButtonElement).disabled&&[[r.x+r.width/2,r.y+r.height/2],[r.left+2,r.y+r.height/2],[r.right-2,r.y+r.height/2],[r.x+r.width/2,r.top+2],[r.x+r.width/2,r.bottom-2]].some(([x,y])=>!element.contains(document.elementFromPoint(x,y)))}))};
 });
 console.log('LEARNING_FIT',JSON.stringify(measured));expect(measured.x).toBeLessThanOrEqual(1);expect(measured.y).toBeLessThanOrEqual(1);expect(measured.controls.length).toBeGreaterThan(0);for(const control of measured.controls){expect(control.outside,control.label??'control').toBe(false);expect(control.miss,control.label??'control').toBe(false);if(coarse){expect(control.width).toBeGreaterThanOrEqual(44);expect(control.height).toBeGreaterThanOrEqual(44);}}
}
for(const locale of ['en','ko'])for(const band of ['desktop','small'])test(`learning steps retain controls across ${locale} ${band} views`,async({page})=>{
 const dialog=await boot(page,locale);const labels=locale==='en'?{read:'Continue after reading',unknown:'Keep the evidence gap and continue',reflect:'Explain in your own words',note:'Your explanation',save:'Save exploration note',again:'Choose another topic'}:{read:'읽고 다음으로',unknown:'근거 부족을 남기고 계속',reflect:'내 말로 정리하기',note:'내 설명 또는 질문',save:'탐구 기록 저장',again:'다른 주제 고르기'};
 for(const [width,height] of (band==='small'?[[320,740],[390,844],[600,900],[844,390]]:[[768,1024],[834,1112],[1024,768],[1440,900],[1920,1080],[2560,1440]])){
  console.log('LEARNING_VIEWPORT',locale,width,height);await page.setViewportSize({width,height});await fit(page);await select(page);await expect(dialog.getByRole('button',{name:labels.read,exact:true})).toBeEnabled();await fit(page);await dialog.getByRole('button',{name:labels.read,exact:true}).click();await fit(page);await dialog.getByRole('button',{name:labels.unknown,exact:true}).click();await fit(page);await dialog.getByRole('button',{name:labels.reflect,exact:true}).click();await fit(page);await dialog.getByRole('textbox',{name:labels.note,exact:true}).fill('I can cite the direct declaration, but runtime impact and tax correctness need more evidence.');await dialog.getByRole('button',{name:labels.save,exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await fit(page);await dialog.getByRole('button',{name:labels.again,exact:true}).click();
 }
});

for(const mode of ['coarse','double-text'])test(`learning decision controls work with ${mode}`,async({browser})=>{
 const context=await browser.newContext({hasTouch:mode==='coarse',viewport:{width:1512,height:900}});const page=await context.newPage();const dialog=await boot(page);if(mode==='double-text')await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 for(const [width,height] of (mode==='coarse'?[[320,740],[844,390],[1512,900]]:[[1512,900]])){
  await page.setViewportSize({width,height});await fit(page,mode==='coarse');await select(page);await expect(page.getByRole('button',{name:'Continue after reading',exact:true})).toBeEnabled();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await fit(page,mode==='coarse');await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();await fit(page,mode==='coarse');await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill('Further source evidence is needed.');await page.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await fit(page,mode==='coarse');await page.getByRole('button',{name:'Choose another topic',exact:true}).click();
 }
 await context.close();
});

test('completion rechecks the saved source instead of trusting the earlier lesson snapshot',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page);const note='This note must not be completed against changed evidence.';await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(note);
 await page.evaluate(()=>{const bridge=(window as unknown as {__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}}).__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const value=await original(command,args);if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md'){const file=value as {lastModified:number};return {...file,lastModified:file.lastModified+1000};}return value;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByRole('alert').filter({hasText:'Not saved: evidence changed or unreadable.'})).toBeVisible();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','reflect');await expect(dialog.getByRole('textbox',{name:'Your explanation',exact:true})).toHaveValue(note);expect((await growth(page)).entries.some((entry:{kind:string;target:{uid:string}})=>entry.kind==='reflected'&&entry.target.uid===topicUid)).toBe(false);
});

test('learning steps expose a nonempty accessible reading and reflection journey',async({page})=>{
 const dialog=await boot(page);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 const scan=async()=>{const result=await page.evaluate(async()=>{const result=await (window as unknown as {axe:{run:(element:Element,options:unknown)=>Promise<{passes:unknown[];violations:unknown[]}>}}).axe.run(document.querySelector('[data-testid="companion-journal"]')!,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}});return {passes:result.passes.length,violations:result.violations};});console.log('LEARNING_AXE',JSON.stringify(result));expect(result.passes).toBeGreaterThan(0);expect(result.violations).toEqual([]);};
 await scan();await select(page);await expect(dialog.getByRole('button',{name:'Continue after reading',exact:true})).toBeEnabled();await scan();await page.getByRole('button',{name:'Continue after reading',exact:true}).click();await scan();await page.getByRole('button',{name:'Keep the evidence gap and continue',exact:true}).click();await scan();await page.getByRole('button',{name:'Explain in your own words',exact:true}).click();await scan();await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill(('My question about the declaration and its limits.\n').repeat(5).slice(0,240));await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');await scan();for(const [width,height] of [[390,844],[844,390]]){await page.setViewportSize({width,height});await fit(page);}
});

test('reflection selection stays consistent while current source verification is pending',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);await dialog.getByRole('textbox',{name:'Your explanation',exact:true}).fill('The direct declaration is known; runtime consequences need evidence.');
 await page.evaluate(()=>{const bridge=(window as unknown as {__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>};releaseLearningRead?:()=>void}).__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const value=await original(command,args);if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md')await new Promise<void>(resolve=>{(window as unknown as {releaseLearningRead:()=>void}).releaseLearningRead=resolve;});return value;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();const learned=dialog.getByRole('radio',{name:'I learned something',exact:true});await expect(learned).toHaveAttribute('aria-disabled','true');await learned.focus();await page.keyboard.press('Space');await expect(dialog.getByRole('radio',{name:'I still have a question',exact:true})).toHaveAttribute('aria-checked','true');await page.waitForFunction(()=>Boolean((window as unknown as {releaseLearningRead?:()=>void}).releaseLearningRead));await page.evaluate(()=>(window as unknown as {releaseLearningRead:()=>void}).releaseLearningRead());await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');expect((await growth(page)).entries.find((entry:{kind:string;target:{uid:string}})=>entry.kind==='reflected'&&entry.target.uid===topicUid).reflection).toBe('uncertain');
});

test('an unchanged vault refresh preserves the learner field and focus while source handles are renewed',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);const field=dialog.getByRole('textbox',{name:'Your explanation',exact:true});await field.fill('Keep this draft and its focus during a same-version refresh.');
 await page.evaluate(()=>{const state=window as unknown as {learningRefreshReads:number;learningFocusLost:boolean;__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}};state.learningRefreshReads=0;state.learningFocusLost=false;const field=document.querySelector('[data-testid="companion-learning"] textarea')!;new MutationObserver(()=>{if(!field.isConnected)state.learningFocusLost=true;}).observe(document.querySelector('[data-testid="companion-learning"]')!,{childList:true,subtree:true});const bridge=state.__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const result=await original(command,args);if(command==='vault_fingerprint')return String(result)+'-refresh';if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md')state.learningRefreshReads++;return result;};window.dispatchEvent(new Event('focus'));});
 await expect.poll(()=>page.evaluate(()=>(window as unknown as {learningRefreshReads:number}).learningRefreshReads)).toBeGreaterThan(0);await expect(field).toBeFocused();await expect(field).toHaveValue('Keep this draft and its focus during a same-version refresh.');expect(await page.evaluate(()=>(window as unknown as {learningFocusLost:boolean}).learningFocusLost)).toBe(false);
});

test('renewing unchanged file handles does not cancel an in-flight reflection save',async({page})=>{
 const dialog=await boot(page);await select(page);await reflect(page,true);const field=dialog.getByRole('textbox',{name:'Your explanation',exact:true});await field.fill('A current direct declaration needs separate runtime evidence.');
 await page.evaluate(()=>{const state=window as unknown as {verificationReads:number;releaseVerification?:()=>void;__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}};state.verificationReads=0;const bridge=state.__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const result=await original(command,args);if(command==='vault_fingerprint')return String(result)+'-during-save';if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&args?.relativePath==='capabilities/invoice-validation.md'){state.verificationReads++;if(state.verificationReads===1)await new Promise<void>(resolve=>{state.releaseVerification=resolve;});}return result;};});
 await dialog.getByRole('button',{name:'Save exploration note',exact:true}).click();await expect(field).toBeDisabled();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect.poll(()=>page.evaluate(()=>(window as unknown as {verificationReads:number}).verificationReads)).toBeGreaterThanOrEqual(2);await waitForBoxStill(dialog.getByTestId('companion-content'));await expect(field).toBeDisabled();await page.evaluate(()=>(window as unknown as {releaseVerification:()=>void}).releaseVerification());await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','done');
});

async function seedFieldNote(page:Page,note:string){
 await page.evaluate(({uid,note})=>{const key=Object.keys(localStorage).find(value=>value.startsWith('ontology-atlas:companion-game:v1:'))!;const project=key.slice('ontology-atlas:companion-game:v1:'.length);const target={uid,slug:'capabilities/invoice-validation',title:'Invoice validation'};localStorage.setItem('ontology-atlas:companion-growth:v1:'+project,JSON.stringify({version:1,entries:[{kind:'explored',target,at:Date.UTC(2026,8,25)},{kind:'reflected',target,at:Date.UTC(2026,8,25),note,reflection:'uncertain'}]}));window.dispatchEvent(new StorageEvent('storage'));},{uid:topicUid,note});
}
const noteText=(page:Page)=>page.locator('[data-companion-note-text]:visible');
async function fitFieldNote(page:Page){
 await fit(page);const text=noteText(page);await expect(text).toHaveCount(1);const bounds=await text.evaluate(el=>{const text=el.getBoundingClientRect();const frame=el.parentElement!.getBoundingClientRect();return {top:text.top-frame.top,bottom:frame.bottom-text.bottom,left:text.left-frame.left,right:frame.right-text.right};});console.log('FIELD_NOTE_TEXT',JSON.stringify(bounds));for(const value of Object.values(bounds))expect(value).toBeGreaterThanOrEqual(-1);
}
test('a saved field note opens directly, keeps uncertainty and returns to current evidence without new XP',async({page})=>{
 const dialog=await boot(page);const note='Validation checks totals; posting records a dependency. Runtime impact needs evidence.';await seedFieldNote(page,note);const card=dialog.getByRole('button',{name:'Invoice validation',exact:true});await expect(card).toContainText('My note');const before=await growth(page);await card.click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');await expect(noteText(page)).toHaveText(note);await expect(dialog.getByText('I still have a question',{exact:true})).toBeVisible();expect(await growth(page)).toEqual(before);
 await dialog.getByRole('button',{name:'Read the full saved source',exact:true}).click();await expect(dialog.getByTestId('companion-source-body')).toContainText('Checks invoice totals');await page.keyboard.press('Escape');await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');expect(await growth(page)).toEqual(before);await dialog.getByRole('button',{name:'Explore again',exact:true}).click();await expect(dialog.getByRole('button',{name:'Continue after reading',exact:true})).toBeEnabled();expect(await growth(page)).toEqual(before);
});
async function removeFieldNoteSource(page:Page){
 await page.evaluate(()=>{const bridge=(window as unknown as {__TAURI_INTERNALS__:{invoke:(command:string,args?:Record<string,unknown>)=>Promise<unknown>}}).__TAURI_INTERNALS__;const original=bridge.invoke.bind(bridge);bridge.invoke=async(command,args)=>{const path=String(args?.relativePath??'').replace(/^\/+|\/+$/g,'');if((command==='read_vault_text_file'||command==='read_vault_binary_file')&&path==='capabilities/invoice-validation.md')throw new Error('missing');const value=await original(command,args);if(command==='list_vault_directory'&&path==='capabilities')return (value as {name:string}[]).filter(entry=>entry.name!=='invoice-validation.md');if(command==='vault_fingerprint')return String(value)+'-source-removed';return value;};window.dispatchEvent(new Event('focus'));});
}
test('removing the current document leaves its historical note readable without a replacement source',async({page})=>{
 const dialog=await boot(page);const note='This personal question survives the disappearance of its source.';await seedFieldNote(page,note);await dialog.getByRole('button',{name:'Invoice validation',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');const before=await growth(page);
 await removeFieldNoteSource(page);
 await expect(dialog.getByRole('button',{name:'Explore again',exact:true})).toBeDisabled();await expect(noteText(page)).toHaveText(note);await expect(dialog).toContainText('Current source unavailable. Your note is kept.');expect(await growth(page)).toEqual(before);await dialog.getByRole('button',{name:'Read the full saved source',exact:true}).click();await expect(dialog.getByTestId('companion-source-body')).toContainText('unavailable');await expect(dialog.getByRole('button',{name:'Open in project (leaves game)',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await expect(noteText(page)).toHaveText(note);
});
for(const locale of ['en','ko'])test(`stored notes use available space and preserve paging across ${locale} view changes`,async({page})=>{
 const dialog=await boot(page,locale);const note=(locale==='ko'?'당시 남긴 개인 메모입니다. 현재 근거와 실제 영향은 다시 확인해야 합니다. ':'A personal field note preserves questions; current evidence and runtime impact still need review. ').repeat(6).slice(0,240);await seedFieldNote(page,note);await dialog.getByRole('button',{name:'Invoice validation',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');
 for(const [width,height,font] of [[320,740,'100%'],[390,844,'100%'],[844,390,'100%'],[768,1024,'100%'],[834,1112,'100%'],[838,660,'100%'],[900,900,'100%'],[1512,900,'100%'],[1512,900,'200%']] as const){await page.setViewportSize({width,height});await page.evaluate(value=>document.documentElement.style.fontSize=value,font);console.log('FIELD_NOTE_VIEW',locale,width,height,font);await fitFieldNote(page);if(width===1512&&font==='100%')await expect(noteText(page)).toHaveText(note);}
 await page.evaluate(()=>document.documentElement.style.fontSize='100%');await page.setViewportSize({width:390,height:844});await fitFieldNote(page);await dialog.getByRole('button',{name:locale==='en'?'Next page':'다음 페이지',exact:true}).click();const second=await noteText(page).textContent();await page.setViewportSize({width:1512,height:900});await fitFieldNote(page);await expect(noteText(page)).toHaveText(note);await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.setViewportSize({width:390,height:844});await fitFieldNote(page);await expect(noteText(page)).toHaveText(second!);
 await dialog.getByRole('button',{name:locale==='en'?'Read the full saved source':'저장된 원문 전체 읽기',exact:true}).click();await expect(dialog.getByTestId('companion-source')).toBeVisible();await page.keyboard.press('Escape');await expect(noteText(page)).toHaveText(second!);
 const lines=('Evidence still needs checking.\n').repeat(9).slice(0,240);await seedFieldNote(page,lines);await page.setViewportSize({width:844,height:390});await fitFieldNote(page);await page.setViewportSize({width:1512,height:900});await fitFieldNote(page);await expect(dialog.getByRole('button',{name:locale==='en'?'Next page':'다음 페이지',exact:true})).toBeVisible();
});
test('a long retained note remains readable with coarse controls after its source disappears',async({browser})=>{
 const context=await browser.newContext({hasTouch:true,viewport:{width:844,height:390}});const page=await context.newPage();const dialog=await boot(page);await seedFieldNote(page,('Evidence still needs checking.\n').repeat(9).slice(0,240));await dialog.getByRole('button',{name:'Invoice validation',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');await removeFieldNoteSource(page);await expect(dialog.getByRole('button',{name:'Explore again',exact:true})).toBeDisabled();for(const [width,height] of [[844,390],[320,740],[390,844],[1512,900]]){await page.setViewportSize({width,height});await fit(page,true);await fitFieldNote(page);}await context.close();
});
test('field note recall has nonempty accessible controls, independent hit areas and readable styles',async({page})=>{
 const dialog=await boot(page);await seedFieldNote(page,'A retained question is personal history. Current implementation evidence still needs a fresh review.');await dialog.getByRole('button',{name:'Invoice validation',exact:true}).click();await expect(dialog.getByTestId('companion-learning')).toHaveAttribute('data-step','recall');await page.evaluate(()=>document.fonts.ready.then(()=>undefined));await fitFieldNote(page);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 const axe=await page.evaluate(async()=>{const result=await (window as unknown as {axe:{run:(element:Element,options:unknown)=>Promise<{passes:unknown[];violations:unknown[];incomplete:{id:string;nodes:{target:unknown;failureSummary?:string}[]}[]}>}}).axe.run(document.querySelector('[data-testid="companion-learning"]')!,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}});return {passes:result.passes.length,violations:result.violations,incomplete:result.incomplete.map(item=>({id:item.id,nodes:item.nodes.map(node=>({target:node.target,summary:node.failureSummary}))}))};});console.log('RECALL_AXE',JSON.stringify(axe));expect(axe.passes).toBeGreaterThan(0);expect(axe.violations).toEqual([]);
 const tokenNames=[...new Set([...readFileSync('app/globals.css','utf8').matchAll(/(--(?:text|leading|radius|shadow|color-text|color-surface)[\w-]*):/g)].map(match=>match[1]))];
 const audit=await dialog.getByTestId('companion-learning').evaluate((el,names)=>{const root=getComputedStyle(document.documentElement);const painted=Array.from(el.querySelectorAll<HTMLElement>('h4,p,time,button')).filter(node=>{const rect=node.getBoundingClientRect(),style=getComputedStyle(node);return rect.width>0&&rect.height>0&&style.display!=='none'&&style.visibility!=='hidden'&&Number(style.opacity)>=.05&&!node.closest('[inert]');});const buttons=painted.filter(node=>node.tagName==='BUTTON');const intersections=[];for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i].getBoundingClientRect(),b=buttons[j].getBoundingClientRect();const area=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));if(area>0)intersections.push({a:buttons[i].textContent,b:buttons[j].textContent,area});}const panelStyle=getComputedStyle(document.querySelector('[data-testid="companion-overlay"]')!);return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,panel:{background:panelStyle.backgroundColor,image:panelStyle.backgroundImage},intersections,styles:painted.map(node=>{const style=getComputedStyle(node);return {tag:node.tagName,label:node.getAttribute('aria-label')||node.textContent,font:style.fontSize,leading:style.lineHeight,color:style.color,background:style.backgroundColor,radius:style.borderRadius,shadow:style.boxShadow};}),tokens:Object.fromEntries(names.map(name=>[name,root.getPropertyValue(name).trim()]).filter(([,value])=>value))};},tokenNames);console.log('RECALL_AUDIT',JSON.stringify(audit));expect(audit.intersections).toEqual([]);expect(audit.styles.length).toBeGreaterThan(0);
});
