import { describe, expect, it } from "vitest";
import {
  duplicateProjectToFormValues,
  formValuesToProjectInput,
  parseLinksText,
  projectFormSchema,
} from "./schema";

function validValues(overrides: Record<string, unknown> = {}) {
  return {
    slug: "aslan-maps",
    name: "Narnia",
    nameEn: "Narnia",
    category: "planned",
    status: "idea",
    description: "description",
    detail: "",
    tagsCsv: "",
    stackCsv: "",
    linksText: "",
    dependencies: [],
    screenshots: [],
    owner: "",
    icon: "",
    startedAt: "",
    launchedAt: "",
    progress: undefined,
    isHub: false,
    ...overrides,
  };
}

describe("projectFormSchema", () => {
  it("accepts korean slug values generated by slugify", () => {
    const result = projectFormSchema.safeParse(
      validValues({ slug: "뉴스-클리핑-2" }),
    );
    expect(result.success).toBe(true);
  });

  it("rejects spaces inside slug values", () => {
    const result = projectFormSchema.safeParse(
      validValues({ slug: "bad slug" }),
    );
    expect(result.success).toBe(false);
  });

  it("rejects malformed link rows", () => {
    const result = projectFormSchema.safeParse(
      validValues({ linksText: "Docs only" }),
    );

    expect(result.success).toBe(false);
    expect(result.error?.issues[0]?.message).toContain("링크 1:");
  });

  it("rejects non-http links", () => {
    const result = projectFormSchema.safeParse(
      validValues({ linksText: "Docs|ftp://example.com" }),
    );

    expect(result.success).toBe(false);
    expect(result.error?.issues[0]?.message).toContain("http:// 또는 https://");
  });

  it("rejects launch dates earlier than start dates", () => {
    const result = projectFormSchema.safeParse(
      validValues({
        startedAt: "2026-04-12",
        launchedAt: "2026-04-11",
      }),
    );

    expect(result.success).toBe(false);
    expect(result.error?.issues[0]?.message).toContain(
      "출시일은 시작일보다 빠를 수 없습니다.",
    );
  });
});

describe("duplicateProjectToFormValues", () => {
  const project = {
    slug: "gemma4",
    name: "Gemma4",
    category: "planned",
    status: "idea",
    description: "자체 언어모델 기반 서비스.",
    detail: "detail",
    tags: ["AI"],
    stack: ["Next.js"],
    links: [{ label: "Docs", url: "https://example.com" }],
    dependencies: ["iam"],
    screenshots: ["https://example.com/image.png"],
    timeline: {},
    isHub: false,
    position: { x: 0, y: 0 },
    createdAt: new Date(0),
    updatedAt: new Date(0),
  };

  it("suggests a copy slug for duplicates", () => {
    const values = duplicateProjectToFormValues(project, ["gemma4"]);
    expect(values.slug).toBe("gemma4-copy");
    expect(values.name).toBe("Gemma4");
    expect(values.description).toBe("자체 언어모델 기반 서비스.");
  });

  it("increments duplicate slugs when needed", () => {
    const values = duplicateProjectToFormValues(project, [
      "gemma4",
      "gemma4-copy",
    ]);
    expect(values.slug).toBe("gemma4-copy-2");
  });
});

describe("formValuesToProjectInput", () => {
  it("converts date strings into timeline dates", () => {
    const result = formValuesToProjectInput(
      validValues({
        startedAt: "2026-04-12",
        launchedAt: "2026-04-14",
      }),
      { x: 10, y: 20 },
    );

    expect(result.timeline).toEqual({
      startedAt: new Date("2026-04-12T00:00:00.000Z"),
      launchedAt: new Date("2026-04-14T00:00:00.000Z"),
    });
  });
});

describe("parseLinksText", () => {
  it("parses valid link rows into label-url pairs", () => {
    expect(
      parseLinksText(
        "GitHub|https://github.com/aslan\nDocs|https://example.com",
      ),
    ).toEqual([
      { label: "GitHub", url: "https://github.com/aslan" },
      { label: "Docs", url: "https://example.com" },
    ]);
  });
});
