// Shared test fixtures for the dogfood MCP walk test suite: mock MCP
// responses (initialize, tools/list, per-tool "ok" shapes) used across the
// split test modules in this directory.
// Split out of scripts/dogfood-mcp-walk.test.mjs (structural decomposition, logic unchanged).
import { readFileSync } from "node:fs";

import {
  EXPECTED_TOOLS,
} from "../../../mcp/scripts/verify.mjs";
import {
  MAINTENANCE_KIND_VALUES,
  QUERY_ONTOLOGY_OPERATIONS,
  WRITE_RELATION_TYPE_VALUES,
} from "../../../mcp/src/ontology-engine.mjs";
import { GRAPH_ARRAY_KEYS } from "../../../mcp/src/vault.mjs";
import { TOOLS_FOR_LIST } from "../../../mcp/src/server/registry.mjs";
export const ROOT_PKG = JSON.parse(readFileSync("package.json", "utf-8"));
const DOGFOOD_UID = "11111111-1111-4111-8111-111111111111";

function rustConfigurationEvidenceFixture() {
  return {
    contract: "rustFeatureConfigurationEvidence:v1",
    status: "not_present",
    claimBoundary: {
      compileTimePredicateLocations: false,
      predicateEvaluation: false,
      runtimeImpact: false,
      importDependency: false,
      macroConsumers: false,
      semanticDependency: false,
    },
    coverage: {
      predicateEvaluation: false,
      macroExpansion: false,
      buildScriptsExecuted: false,
    },
    packages: [],
    unsupportedWorkspaceMembers: [],
    writePolicy: {
      automaticRelation: false,
      writeAllowed: false,
      humanApprovalRequired: true,
    },
    limitations: ["No Cargo manifest was observed."],
  };
}

function importScanCoverageFixture() {
  return {
    contract: "importScanCoverage:v1",
    supportedLanguages: ["go", "javascript", "python", "rust", "typescript"],
    supportedExtensions: [".go", ".js", ".py", ".rs", ".ts"],
    detectedUnsupportedLanguages: [],
    allDetectedLanguagesSupported: true,
    zeroEdgesMeaning: "no_supported_static_import_edges_observed",
    limitations: ["Static source evidence is not semantic dependency approval."],
  };
}

function makeDogfoodInitialize() {
  return {
    protocolVersion: "2024-11-05",
    serverInfo: { name: "ontology-atlas-mcp", version: "0.12.0" },
    instructions: [
      "Use read-only first-contact diagnosis before write tools.",
      `Tool inventory includes ${EXPECTED_TOOLS.join(", ")}.`,
      "rename_concept refuses an existing `newSlug` unless overwrite: true is explicit.",
      "delete_concept force: true means accepting dangling referrers.",
      "Use expected_mtime when patching a previously-read concept.",
      "Tool schemas reject unknown arguments with nearest hints.",
      "unknown arguments are rejected instead of being ignored.",
      'unknown tool names are rejected with closest tool-name hints such as Unknown tool: list_concept. Did you mean "list_concepts"?',
      "Tool errors include structuredContent.errorCode values such as unknown_tool, unknown_argument, and invalid_arguments.",
      "Tool errors include structuredContent repair fields such as receivedTool, receivedArgument, unknownArguments, rowName, receivedField, unknownFields, allowedFields, receivedFields, firstSeenAt, receivedValue, suggestion, allowedTools, allowedArguments, and allowedValues.",
      "Missing node errors include structuredContent repair fields such as missingSlug, similarSlugs, recoveryTools, and createTool.",
      "Slug conflict errors include structuredContent repair fields such as conflictSlug, recoveryTools, and overwriteOption.",
      'Unknown argument "lmit" for list_concepts. Did you mean "limit"?',
      'Unknown arguments for list_concepts: "lmit" (did you mean "limit"?), "summry" (did you mean "summary"?)',
      "Batch add_concepts and add_relations isolate each non-object row and unknown row fields as ok:false.",
      "Invalid-only batches return no row-level write metadata and no top-level `postWriteMaintenance`; if every row failed, treat the call as dry validation evidence and retry corrected rows.",
      "Invalid-only batches return no row-level `changed` / `alreadyExists` write metadata and no top-level `postWriteMaintenance`; if every row failed, treat the call as dry validation evidence and retry corrected rows.",
      'Batch add_relations unknown type row errors include a closest-value hint such as Did you mean "depends_on"?',
      "Duplicate add_concepts input slugs report concepts[n] duplicate slug in input batch; first seen at concepts[m].",
      'operation must be one of: ... Invalid value: overveiw. Did you mean "overview"?',
      "maintenance_plan phases, severities, and kinds filters are enum-validated.",
      "health and workspace_brief tune probes with componentLimit, cycleLimit, recommendationLimit, orderLimit, nodeLimit, dependencyTypes, and componentTypes.",
      "dependencyTypes / componentTypes accept relation types domains, domain, capabilities, elements, dependencies, depends_on, relates, contains, describes; typoed values fail with nearest-value hints.",
      "maintenance_plan ready pages return cursor.found=true with cursor.reason=null.",
      "maintenance_plan ready pages set cursor.nextAfterActionId to the last returned action id and cursor.hasMore for remaining pages.",
      "maintenance_plan nextExecutableAction and nextReviewAction point only at the first executable/review action in the current returned page.",
      "maintenance_plan afterActionId cursor misses return cursor.found=false and cursor.reason.",
      "maintenance_plan missing cursors return cursor.nextAfterActionId=null and cursor.hasMore=false.",
      "query_ontology agent_brief returns relationDecisionGuide for relation_check outcomes skip_existing, review_inverse, safe_to_add, and review_new_schema.",
      "query_ontology agent_brief returns graphDbQueryPack for facets, schema, match_nodes, match_edges, domain_matrix, centrality, all_paths, and explain_relation.",
      "query_ontology agent_brief returns traversalStrategy plan_before_enumeration, bounded_path_evidence, and containment_cross_check.",
      "query_ontology agent_brief resultContracts describe all_paths limit, searchBudget, expandedStates, exhaustive, truncatedByBudget, totalPathsExact, evidence.status, evidence.reason, and evidence.pathsComplete.",
    ].join("\n"),
  };
}

/** Keep the healthy fixture sourced from the public registry so schema ratchets cannot drift from
 * the actual tools/list surface. Individual gate tests clone and deliberately mutate this shape. */
export function makeDogfoodToolsList() {
  // JSON cloning intentionally breaks shared schema references. The gate tests mutate one
  // tool at a time; preserving registry aliasing would make an unrelated mutation look like
  // drift in the first tool that reuses that nested schema.
  return { tools: JSON.parse(JSON.stringify(TOOLS_FOR_LIST)) };
}

function batchCapError(noun) {
  const text = `Too many ${noun}: 51. Max 50 per call.`;
  return {
    result: {
      isError: true,
      content: [{ text }],
      structuredContent: { ok: false, errorCode: "invalid_arguments", error: text },
    },
  };
}

function strictValueErrorResponse(valueName, allowedValues, receivedValue, suggestion) {
  const suggestionText = suggestion ? ` Did you mean "${suggestion}"?` : "";
  const text = `${valueName} must be one of: ${allowedValues.join(", ")}. Received: "${receivedValue}".${suggestionText}`;
  return {
    result: {
      isError: true,
      content: [{ text }],
      structuredContent: {
        ok: false,
        errorCode: "invalid_arguments",
        error: text,
        valueName,
        receivedValue,
        ...(suggestion ? { suggestion } : {}),
        allowedValues,
      },
    },
  };
}

const dogfoodTargets = {
  projectSlug: "project",
  domainSlug: "domains/ai-agent-partner",
  capabilitySlug: "capabilities/mcp-server",
  capabilityTitle: "MCP Server",
  mergeTargetSlug: "capabilities/vault-validator",
  pathTargetSlug: "domains/vault-local-first",
  patternStartSlug: "project",
  pattern: ["domains", "capabilities"],
  relationType: "domain",
  slugNeedle: "mcp",
  similarCandidateSlug: "capabilities/mcp-server-v2",
};

export const okShape = {
  targets: dogfoodTargets,
  initialize: makeDogfoodInitialize(),
  toolsList: makeDogfoodToolsList(),
  kinds: { total: 1, byKind: { project: 1 } },
  kindsStructured: { total: 1, byKind: { project: 1 } },
  list: {
    total: 1,
    returned: 1,
    limited: false,
    pagination: { offset: 0, limit: 100, total: 1, returned: 1, hasMore: false, nextOffset: null },
    vaultRoot: "/tmp/vault",
    nodes: [{ uid: DOGFOOD_UID, slug: "project", kind: "project", title: "Project", mtime: 1 }],
  },
  listStructured: {
    total: 1,
    returned: 1,
    limited: false,
    pagination: { offset: 0, limit: 100, total: 1, returned: 1, hasMore: false, nextOffset: null },
    vaultRoot: "/tmp/vault",
    nodes: [{ uid: DOGFOOD_UID, slug: "project", kind: "project", title: "Project", mtime: 1 }],
  },
  projectProbe: {
    total: 1,
    returned: 1,
    limited: false,
    pagination: { offset: 0, limit: 100, total: 1, returned: 1, hasMore: false, nextOffset: null },
    vaultRoot: "/tmp/vault",
    nodes: [{ uid: DOGFOOD_UID, slug: "project", kind: "project", title: "Project", mtime: 1 }],
  },
  projectProbeStructured: {
    total: 1,
    returned: 1,
    limited: false,
    pagination: { offset: 0, limit: 100, total: 1, returned: 1, hasMore: false, nextOffset: null },
    vaultRoot: "/tmp/vault",
    nodes: [{ uid: DOGFOOD_UID, slug: "project", kind: "project", title: "Project", mtime: 1 }],
  },
  batch: {
    concepts: [
      {
        ok: true,
        uid: DOGFOOD_UID,
        slug: "project",
        frontmatter: { kind: "project", title: "Project" },
        excerpt: "Project excerpt",
        mtime: 1,
      },
      {
        ok: true,
        uid: DOGFOOD_UID,
        slug: "capabilities/mcp-server",
        frontmatter: { kind: "capability", title: "MCP Server" },
        excerpt: "MCP Server excerpt",
        mtime: 1,
      },
      {
        ok: false,
        slug: "missing-dogfood-slug",
        error: "Doc not found: missing-dogfood-slug",
      },
    ],
  },
  batchStructured: {
    concepts: [
      {
        ok: true,
        uid: DOGFOOD_UID,
        slug: "project",
        frontmatter: { kind: "project", title: "Project" },
        excerpt: "Project excerpt",
        mtime: 1,
      },
      {
        ok: true,
        uid: DOGFOOD_UID,
        slug: "capabilities/mcp-server",
        frontmatter: { kind: "capability", title: "MCP Server" },
        excerpt: "MCP Server excerpt",
        mtime: 1,
      },
      {
        ok: false,
        slug: "missing-dogfood-slug",
        error: "Doc not found: missing-dogfood-slug",
      },
    ],
  },
  addConceptsRowRepair: {
    concepts: [
      { slug: "", ok: false, error: "concepts[0] must be an object", errorCode: "invalid_arguments" },
      {
        slug: "dogfood-row-repair-multi",
        ok: false,
        error: 'Unknown fields in concepts[1]: "titel" (did you mean "title"?), "domian" (did you mean "domain"?). Allowed fields: slug, kind, title, domain, capabilities, elements, path, body, labels. Received fields: domian, kind, slug, titel, title.',
        errorCode: "invalid_arguments",
        rowName: "concepts[1]",
        unknownFields: [
          { name: "titel", suggestion: "title" },
          { name: "domian", suggestion: "domain" },
        ],
        allowedFields: ["slug", "kind", "title", "domain", "capabilities", "elements", "path", "body", "labels"],
        receivedFields: ["domian", "kind", "slug", "titel", "title"],
      },
      {
        slug: "verify-duplicate-slug",
        ok: false,
        error: 'kind must be one of: project, domain, capability, element, document. Received: "capabilty". Did you mean "capability"?',
        errorCode: "invalid_arguments",
        valueName: "kind",
        receivedValue: "capabilty",
        suggestion: "capability",
        allowedValues: ["project", "domain", "capability", "element", "document"],
      },
      {
        slug: "verify-duplicate-slug",
        ok: false,
        error: "concepts[3] duplicate slug in input batch; first seen at concepts[2]",
        errorCode: "conflict",
        rowName: "concepts[3]",
        conflictSubject: "Duplicate slug in input batch",
        conflictSlug: "verify-duplicate-slug",
        firstSeenAt: "concepts[2]",
      },
      {
        slug: "dogfood-row-repair-single",
        ok: false,
        error: 'Unknown field "titel" in concepts[4]. Did you mean "title"? Allowed fields: slug, kind, title, domain, capabilities, elements, path, body, labels. Received fields: kind, slug, titel, title.',
        errorCode: "invalid_arguments",
        rowName: "concepts[4]",
        receivedField: "titel",
        suggestion: "title",
        unknownFields: [{ name: "titel", suggestion: "title" }],
        allowedFields: ["slug", "kind", "title", "domain", "capabilities", "elements", "path", "body", "labels"],
        receivedFields: ["kind", "slug", "titel", "title"],
      },
    ],
  },
  addConceptsRowRepairStructured: {
    concepts: [
      { slug: "", ok: false, error: "concepts[0] must be an object", errorCode: "invalid_arguments" },
      {
        slug: "dogfood-row-repair-multi",
        ok: false,
        error: 'Unknown fields in concepts[1]: "titel" (did you mean "title"?), "domian" (did you mean "domain"?). Allowed fields: slug, kind, title, domain, capabilities, elements, path, body, labels. Received fields: domian, kind, slug, titel, title.',
        errorCode: "invalid_arguments",
        rowName: "concepts[1]",
        unknownFields: [
          { name: "titel", suggestion: "title" },
          { name: "domian", suggestion: "domain" },
        ],
        allowedFields: ["slug", "kind", "title", "domain", "capabilities", "elements", "path", "body", "labels"],
        receivedFields: ["domian", "kind", "slug", "titel", "title"],
      },
      {
        slug: "verify-duplicate-slug",
        ok: false,
        error: 'kind must be one of: project, domain, capability, element, document. Received: "capabilty". Did you mean "capability"?',
        errorCode: "invalid_arguments",
        valueName: "kind",
        receivedValue: "capabilty",
        suggestion: "capability",
        allowedValues: ["project", "domain", "capability", "element", "document"],
      },
      {
        slug: "verify-duplicate-slug",
        ok: false,
        error: "concepts[3] duplicate slug in input batch; first seen at concepts[2]",
        errorCode: "conflict",
        rowName: "concepts[3]",
        conflictSubject: "Duplicate slug in input batch",
        conflictSlug: "verify-duplicate-slug",
        firstSeenAt: "concepts[2]",
      },
      {
        slug: "dogfood-row-repair-single",
        ok: false,
        error: 'Unknown field "titel" in concepts[4]. Did you mean "title"? Allowed fields: slug, kind, title, domain, capabilities, elements, path, body, labels. Received fields: kind, slug, titel, title.',
        errorCode: "invalid_arguments",
        rowName: "concepts[4]",
        receivedField: "titel",
        suggestion: "title",
        unknownFields: [{ name: "titel", suggestion: "title" }],
        allowedFields: ["slug", "kind", "title", "domain", "capabilities", "elements", "path", "body", "labels"],
        receivedFields: ["kind", "slug", "titel", "title"],
      },
    ],
  },
  addRelationsRowRepair: {
    relations: [
      { ok: false, from: "", to: "", type: "", error: "relations[0] must be an object", errorCode: "invalid_arguments" },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "relates",
        error: 'Unknown fields in relations[1]: "relation" (did you mean "type"?), "frm" (did you mean "from"?). Allowed fields: from, to, type, why, expected_mtime. Received fields: frm, from, relation, to, type.',
        errorCode: "invalid_arguments",
        rowName: "relations[1]",
        unknownFields: [
          { name: "relation", suggestion: "type" },
          { name: "frm", suggestion: "from" },
        ],
        allowedFields: ["from", "to", "type", "why", "expected_mtime"],
        receivedFields: ["frm", "from", "relation", "to", "type"],
      },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "depend_on",
        error: 'relations[2] type must be one of: depends_on, relates, contains, describes, domains, capabilities, elements, domain. Received: "depend_on". Did you mean "depends_on"?',
        errorCode: "invalid_arguments",
        valueName: "type",
        receivedValue: "depend_on",
        suggestion: "depends_on",
        allowedValues: WRITE_RELATION_TYPE_VALUES,
      },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "relates",
        error: 'Unknown field "relation" in relations[3]. Did you mean "type"? Allowed fields: from, to, type, why, expected_mtime. Received fields: from, relation, to, type.',
        errorCode: "invalid_arguments",
        rowName: "relations[3]",
        receivedField: "relation",
        suggestion: "type",
        unknownFields: [{ name: "relation", suggestion: "type" }],
        allowedFields: ["from", "to", "type", "why", "expected_mtime"],
        receivedFields: ["from", "relation", "to", "type"],
      },
    ],
  },
  addRelationsRowRepairStructured: {
    relations: [
      { ok: false, from: "", to: "", type: "", error: "relations[0] must be an object", errorCode: "invalid_arguments" },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "relates",
        error: 'Unknown fields in relations[1]: "relation" (did you mean "type"?), "frm" (did you mean "from"?). Allowed fields: from, to, type, why, expected_mtime. Received fields: frm, from, relation, to, type.',
        errorCode: "invalid_arguments",
        rowName: "relations[1]",
        unknownFields: [
          { name: "relation", suggestion: "type" },
          { name: "frm", suggestion: "from" },
        ],
        allowedFields: ["from", "to", "type", "why", "expected_mtime"],
        receivedFields: ["frm", "from", "relation", "to", "type"],
      },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "depend_on",
        error: 'relations[2] type must be one of: depends_on, relates, contains, describes, domains, capabilities, elements, domain. Received: "depend_on". Did you mean "depends_on"?',
        errorCode: "invalid_arguments",
        valueName: "type",
        receivedValue: "depend_on",
        suggestion: "depends_on",
        allowedValues: WRITE_RELATION_TYPE_VALUES,
      },
      {
        ok: false,
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        type: "relates",
        error: 'Unknown field "relation" in relations[3]. Did you mean "type"? Allowed fields: from, to, type, why, expected_mtime. Received fields: from, relation, to, type.',
        errorCode: "invalid_arguments",
        rowName: "relations[3]",
        receivedField: "relation",
        suggestion: "type",
        unknownFields: [{ name: "relation", suggestion: "type" }],
        allowedFields: ["from", "to", "type", "why", "expected_mtime"],
        receivedFields: ["from", "relation", "to", "type"],
      },
    ],
  },
  ev: { matches: [] },
  evStructured: { matches: [] },
  path: { found: true, hopCount: 1, hops: ["a", "b"], edges: [{ from: "a", to: "b", via: "relates" }] },
  pathStructured: { found: true, hopCount: 1, hops: ["a", "b"], edges: [{ from: "a", to: "b", via: "relates" }] },
  bl: {
    target: "capabilities/mcp-server",
    total: 1,
    matches: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" }],
  },
  blStructured: {
    target: "capabilities/mcp-server",
    total: 1,
    matches: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" }],
  },
  orph: { total: 0, orphans: [] },
  orphStructured: { total: 0, orphans: [] },
  queryConcepts: {
    filter: "kind=capability",
    parsedAs: "kind=capability",
    total: 1,
    matches: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server", mtime: 1 }],
    limited: false,
  },
  queryConceptsStructured: {
    filter: "kind=capability",
    parsedAs: "kind=capability",
    total: 1,
    matches: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server", mtime: 1 }],
    limited: false,
  },
  queryConceptsLimited: {
    filter: "slug!=project",
    parsedAs: "slug!=project",
    total: 1,
    matches: [{ slug: "README", kind: "vault-readme", title: "README", mtime: 1 }],
    limited: true,
  },
  queryConceptsLimitedStructured: {
    filter: "slug!=project",
    parsedAs: "slug!=project",
    total: 1,
    matches: [{ slug: "README", kind: "vault-readme", title: "README", mtime: 1 }],
    limited: true,
  },
  analyzedRepo: {
    rootPath: "/repo",
    framework: "fsd",
    project: { slug: "sample", title: "Sample" },
    domains: [{ slug: "domains/auth", title: "Auth", evidence: { source: "README.md", line: 3 } }],
    capabilities: [{ slug: "capabilities/auth", title: "Auth", evidence: { source: "src/features/auth" } }],
    elements: [{ slug: "elements/src/views/home", title: "Home", path: "src/views/home", evidence: { source: "src/views/home" } }],
    suggestedRelations: [{ from: "sample", to: "capabilities/auth", type: "contains" }],
    skipped: [{ path: "src/.cache", reason: "dotfile/ignore" }],
    configurationEvidence: rustConfigurationEvidenceFixture(),
  },
  analyzedRepoStructured: {
    rootPath: "/repo",
    framework: "fsd",
    project: { slug: "sample", title: "Sample" },
    domains: [{ slug: "domains/auth", title: "Auth", evidence: { source: "README.md", line: 3 } }],
    capabilities: [{ slug: "capabilities/auth", title: "Auth", evidence: { source: "src/features/auth" } }],
    elements: [{ slug: "elements/src/views/home", title: "Home", path: "src/views/home", evidence: { source: "src/views/home" } }],
    suggestedRelations: [{ from: "sample", to: "capabilities/auth", type: "contains" }],
    skipped: [{ path: "src/.cache", reason: "dotfile/ignore" }],
    configurationEvidence: rustConfigurationEvidenceFixture(),
  },
  inferredImports: {
    rootPath: "/repo",
    filesScanned: 2,
    edges: [{ from: "src/features/auth/index.ts", to: "src/entities/user/index.ts", kind: "static", sourceRole: "production", importUsage: "value" }],
    externalImports: [{ from: "src/features/auth/index.ts", spec: "zod" }],
    unresolved: [{ from: "src/features/auth/index.ts", spec: "@/missing", reason: "alias-not-found" }],
    coverage: importScanCoverageFixture(),
    moduleEdges: [{ from: "capabilities/auth", to: "capabilities/user", count: 1, kindCounts: { static: 1 }, sourceRoleCounts: { production: 1, test: 0, unknown: 0 }, importUsageCounts: { value: 1, type_only: 0, unknown: 0 }, productValueCount: 1, evidence: [{ from: "src/features/auth/index.ts", to: "src/entities/user/index.ts", kind: "static", sourceRole: "production", importUsage: "value" }], evidenceLimited: false }],
  },
  inferredImportsStructured: {
    rootPath: "/repo",
    filesScanned: 2,
    edges: [{ from: "src/features/auth/index.ts", to: "src/entities/user/index.ts", kind: "static", sourceRole: "production", importUsage: "value" }],
    externalImports: [{ from: "src/features/auth/index.ts", spec: "zod" }],
    unresolved: [{ from: "src/features/auth/index.ts", spec: "@/missing", reason: "alias-not-found" }],
    coverage: importScanCoverageFixture(),
    moduleEdges: [{ from: "capabilities/auth", to: "capabilities/user", count: 1, kindCounts: { static: 1 }, sourceRoleCounts: { production: 1, test: 0, unknown: 0 }, importUsageCounts: { value: 1, type_only: 0, unknown: 0 }, productValueCount: 1, evidence: [{ from: "src/features/auth/index.ts", to: "src/entities/user/index.ts", kind: "static", sourceRole: "production", importUsage: "value" }], evidenceLimited: false }],
  },
  renameDryRunRes: {
    result: {
      content: [
        {
          text: JSON.stringify({
            ok: false,
            dryRun: true,
            previewReady: true,
            canConfirm: true,
            wouldChange: true,
            blockedReasons: [],
            oldSlug: "capabilities/mcp-server",
            newSlug: "capabilities/mcp-server-dogfood-dry-run",
            sourcePath: "/tmp/vault/capabilities/mcp-server.md",
            targetPath: "/tmp/vault/capabilities/mcp-server-dogfood-dry-run.md",
            moved: false,
            backlinkUpdates: { updates: [], totalUpdated: 0 },
            message: "dry-run — confirm:true to apply",
          }),
        },
      ],
      structuredContent: {
        ok: false,
        dryRun: true,
        previewReady: true,
        canConfirm: true,
        wouldChange: true,
        blockedReasons: [],
        oldSlug: "capabilities/mcp-server",
        newSlug: "capabilities/mcp-server-dogfood-dry-run",
        sourcePath: "/tmp/vault/capabilities/mcp-server.md",
        targetPath: "/tmp/vault/capabilities/mcp-server-dogfood-dry-run.md",
        moved: false,
        backlinkUpdates: { updates: [], totalUpdated: 0 },
        message: "dry-run — confirm:true to apply",
      },
    },
  },
  mergeDryRunRes: {
    result: {
      content: [
        {
          text: JSON.stringify({
            ok: false,
            dryRun: true,
            previewReady: true,
            canConfirm: true,
            wouldChange: true,
            blockedReasons: [],
            fromSlug: "capabilities/mcp-server",
            intoSlug: "domains/ai-agent-partner",
            fromPath: "/tmp/vault/capabilities/mcp-server.md",
            deleted: false,
            backlinkUpdates: { updates: [], totalUpdated: 0 },
            capturedFrom: { frontmatter: {} },
            message: "dry-run — confirm:true to apply",
          }),
        },
      ],
      structuredContent: {
        ok: false,
        dryRun: true,
        previewReady: true,
        canConfirm: true,
        wouldChange: true,
        blockedReasons: [],
        fromSlug: "capabilities/mcp-server",
        intoSlug: "domains/ai-agent-partner",
        fromPath: "/tmp/vault/capabilities/mcp-server.md",
        deleted: false,
        backlinkUpdates: { updates: [], totalUpdated: 0 },
        capturedFrom: { frontmatter: {} },
        message: "dry-run — confirm:true to apply",
      },
    },
  },
  deleteDryRunRes: {
    result: {
      content: [
        {
          text: JSON.stringify({
            ok: false,
            dryRun: true,
            previewReady: true,
            canConfirm: true,
            wouldChange: true,
            blockedReasons: [],
            slug: "capabilities/mcp-server",
            filePath: "/tmp/vault/capabilities/mcp-server.md",
            backlinks: [],
            message: "dry-run — force:true to apply",
          }),
        },
      ],
      structuredContent: {
        ok: false,
        dryRun: true,
        previewReady: true,
        canConfirm: true,
        wouldChange: true,
        blockedReasons: [],
        slug: "capabilities/mcp-server",
        filePath: "/tmp/vault/capabilities/mcp-server.md",
        backlinks: [],
        message: "dry-run — force:true to apply",
      },
    },
  },
  validation: {
    scanned: 1,
    problems: [],
    summary: { problemFiles: 0, errorFiles: 0, warningFiles: 0, byCode: {} },
  },
  validationStructured: {
    scanned: 1,
    problems: [],
    summary: { problemFiles: 0, errorFiles: 0, warningFiles: 0, byCode: {} },
  },
  brief: {
    operation: "workspace_brief",
    status: "healthy",
    summary: { nodes: 1, edges: 0, issues: 0, growthActions: 0 },
    nextActions: [],
    growth: {
      relationRecommendations: 0,
      externalElementRefs: 0,
      danglingReferences: 0,
      unassignedNodes: 0,
      emptyDomains: 0,
      totalActions: 0,
    },
    health: { checks: [{ id: "compile_issues", status: "pass", count: 0 }] },
  },
  tunedBrief: {
    operation: "workspace_brief",
    status: "healthy",
    summary: { nodes: 1, edges: 0, issues: 0, growthActions: 0 },
    nextActions: [],
    growth: {
      relationRecommendations: 0,
      externalElementRefs: 0,
      danglingReferences: 0,
      unassignedNodes: 0,
      emptyDomains: 0,
      totalActions: 0,
    },
    health: { checks: [{ id: "compile_issues", status: "pass", count: 0 }] },
  },
  health: {
    operation: "health",
    status: "healthy",
    summary: { issues: 0, unresolvedEdges: 0, dependencyCycles: 0 },
    checks: [{ id: "compile_issues", status: "pass", count: 0 }],
  },
  tunedHealth: {
    operation: "health",
    status: "healthy",
    summary: { issues: 0, unresolvedEdges: 0, dependencyCycles: 0 },
    checks: [{ id: "compile_issues", status: "pass", count: 0 }],
  },
  compiled: {
    version: 1,
    graphHash: "abc123",
    maxMtime: 1,
    nodeCount: 1,
    edgeCount: 2,
    resolvedEdgeCount: 1,
    externalEdgeCount: 1,
    unresolvedEdgeCount: 0,
    aliasCount: 1,
    ambiguousAliasCount: 0,
    issueCount: 0,
    canonicalizationActionCount: 0,
    byKind: { project: 1 },
    byDomain: {},
  },
  compiledStructured: {
    version: 1,
    graphHash: "abc123",
    maxMtime: 1,
    nodeCount: 1,
    edgeCount: 2,
    resolvedEdgeCount: 1,
    externalEdgeCount: 1,
    unresolvedEdgeCount: 0,
    aliasCount: 1,
    ambiguousAliasCount: 0,
    issueCount: 0,
    canonicalizationActionCount: 0,
    byKind: { project: 1 },
    byDomain: {},
  },
  compiledIndexes: {
    version: 1,
    graphHash: "abc123",
    maxMtime: 1,
    nodeCount: 1,
    edgeCount: 2,
    resolvedEdgeCount: 1,
    externalEdgeCount: 1,
    unresolvedEdgeCount: 0,
    aliasCount: 1,
    ambiguousAliasCount: 0,
    issueCount: 0,
    canonicalizationActionCount: 0,
    byKind: { project: 1 },
    byDomain: {},
    nodes: [{ uid: DOGFOOD_UID, slug: "project", kind: "project", title: "Project", mtime: 1, outDegree: 2, inDegree: 0 }],
    edges: [{ id: "e1", from: "project", to: "domains/core", via: "domains", ref: "domains/core", resolved: true, external: false }],
    aliases: [{ alias: "project", slug: "project" }],
    ambiguousAliases: [],
    issues: [],
    canonicalizationActions: [],
    summary: {
      graphHash: "abc123",
      nodes: 1,
      edges: 2,
      resolvedEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
      aliases: 1,
      ambiguousAliases: 0,
      issues: 0,
    },
    nodesPagination: { offset: 0, limit: 1, total: 1, returned: 1, hasMore: false, nextOffset: null },
    edgesPagination: { offset: 0, limit: 1, total: 2, returned: 1, hasMore: true, nextOffset: 1 },
    indexes: {
      out: { project: ["e1", "e2"] },
      in: { "domains/core": ["e1"] },
      byKind: { project: ["project"] },
      byDomain: {},
      uidToSlug: { [DOGFOOD_UID]: "project" },
      slugToUid: { project: DOGFOOD_UID },
      mergedUidToSlug: {},
      edgeById: {
        e1: { id: "e1", from: "project", to: "domains/core", via: "domains", ref: "domains/core", resolved: true, external: false },
        e2: { id: "e2", from: "project", to: "external/npm", via: "dependencies", ref: "external/npm", resolved: false, external: true },
      },
      aliasToSlug: { project: "project" },
    },
  },
  compiledIndexesStructured: null,
  overview: {
    operation: "overview",
    graph: {
      nodes: 1,
      edges: 2,
      resolvedEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
      aliases: 1,
      ambiguousAliases: 0,
      issues: 0,
      graphHash: "abc123",
      maxMtime: 1,
    },
    byKind: { project: 1 },
    byRelation: {},
    hubs: [],
  },
  overviewStructured: {
    operation: "overview",
    graph: {
      nodes: 1,
      edges: 2,
      resolvedEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
      aliases: 1,
      ambiguousAliases: 0,
      issues: 0,
      graphHash: "abc123",
      maxMtime: 1,
    },
    byKind: { project: 1 },
    byRelation: {},
    hubs: [],
  },
  patternWalk: {
    operation: "pattern_walk",
    start: "project",
    pattern: ["domains", "capabilities"],
    layers: [
      {
        step: 1,
        relation: "domains",
        totalPaths: 1,
        totalNodes: 1,
        nodes: [{ slug: "domains/auth", kind: "domain", title: "Auth" }],
      },
    ],
    endNodes: [{ slug: "capabilities/login", kind: "capability", title: "Login" }],
    paths: {
      total: 1,
      limited: false,
      rows: [
        {
          end: "capabilities/login",
          path: ["project", "domains/auth", "capabilities/login"],
          edges: [],
        },
      ],
    },
  },
  allPaths: {
    operation: "all_paths",
    from: "capabilities/mcp-server",
    to: "domains/vault-local-first",
    found: true,
    direction: "undirected",
    maxHops: 4,
    searchBudget: 5000,
    expandedStates: 10,
    exhaustive: true,
    truncatedByBudget: false,
    totalPaths: 2,
    totalPathsExact: true,
    limited: false,
    shortestHopCount: 2,
    byLength: { 2: 2 },
    paths: [
      {
        hopCount: 2,
        hops: ["capabilities/mcp-server", "domains/ai-agent-partner", "domains/vault-local-first"],
        edges: [],
      },
      {
        hopCount: 2,
        hops: ["capabilities/mcp-server", "capabilities/vault-validator", "domains/vault-local-first"],
        edges: [],
      },
    ],
  },
  allPathsPlan: {
    operation: "query_plan",
    targetOperation: "all_paths",
    sideEffect: false,
    normalized: {
      targetOperation: "all_paths",
      types: null,
      limit: 25,
      from: "capabilities/mcp-server",
      to: "domains/vault-local-first",
      direction: "undirected",
      maxHops: 4,
      searchBudget: 5000,
    },
    indexesUsed: ["aliasToSlug", "in", "out"],
    estimate: {
      strategy: "bounded_path_enumeration",
      edgeScans: 20,
      reachableWithinDepth: 8,
      frontierByDepth: [],
      potentialPathUpperBound: 40,
      resultUpperBound: 25,
      costClass: "medium",
    },
    warnings: ["all_paths may be truncated by limit; reduce maxHops or add relation types."],
    execution: {
      shouldRun: false,
      nextStep: "review",
      recommendation: "Review warnings before running suggestedQuery.",
      suggestedQuery: {
        operation: "all_paths",
        from: "capabilities/mcp-server",
        to: "domains/vault-local-first",
        direction: "undirected",
        maxHops: 4,
        searchBudget: 5000,
        limit: 25,
      },
      saferQuery: {
        operation: "all_paths",
        from: "capabilities/mcp-server",
        to: "domains/vault-local-first",
        direction: "undirected",
        maxHops: 3,
        searchBudget: 1000,
        limit: 10,
        types: ["depends_on", "relates"],
      },
    },
  },
  projectMapPlan: {
    operation: "query_plan",
    targetOperation: "project_map",
    sideEffect: false,
    normalized: {
      targetOperation: "project_map",
      types: null,
      limit: 100,
    },
    indexesUsed: ["compiled_artifact"],
    estimate: {
      strategy: "aggregate_scan",
      nodeScans: 1,
      edgeScans: 2,
      costClass: "low",
    },
    warnings: [],
    execution: {
      shouldRun: true,
      nextStep: "run",
      recommendation: "Run suggestedQuery as planned.",
      suggestedQuery: {
        operation: "project_map",
        limit: 100,
      },
    },
  },
  projectMap: {
    operation: "project_map",
    project: "project",
    node: { slug: "project", kind: "project", title: "Project" },
    summary: {
      nodes: 3,
      domains: 1,
      capabilities: 1,
      elements: 0,
      unassignedNodes: 0,
      internalEdges: 2,
      boundaryEdges: 0,
      externalEdges: 0,
      unresolvedEdges: 0,
    },
    limited: false,
    domains: [
      {
        slug: "domains/auth",
        kind: "domain",
        title: "Auth",
        summary: {
          nodes: 2,
          capabilities: 1,
          elements: 0,
          internalEdges: 1,
          boundaryEdges: 0,
          externalEdges: 0,
          unresolvedEdges: 0,
        },
        capabilities: {
          total: 1,
          limited: false,
          nodes: [{ slug: "capabilities/login", kind: "capability", title: "Login" }],
        },
        elements: { total: 0, limited: false, nodes: [] },
      },
    ],
    unassigned: { total: 0, limited: false, nodes: [] },
    hotspots: [],
  },
  domainProfile: {
    operation: "domain_profile",
    domain: "domains/ai-agent-partner",
    node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
    parents: {
      projects: [{ slug: "project", via: "domains", node: { slug: "project", kind: "project", title: "Project" } }],
    },
    summary: {
      nodes: 3,
      capabilities: 1,
      elements: 1,
      internalEdges: 2,
      boundaryEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
    },
    capabilities: {
      total: 1,
      limited: false,
      nodes: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" }],
    },
    elements: {
      total: 1,
      limited: false,
      nodes: [{ slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" }],
    },
    hotspots: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" }],
    edges: {
      boundary: {
        total: 1,
        limited: false,
        byRelation: { relates: 1 },
        edges: [{ from: "capabilities/mcp-server", to: "domains/vault-local-first", via: "relates" }],
      },
      external: {
        total: 1,
        limited: false,
        byRelation: { elements: 1 },
        edges: [{ from: "capabilities/mcp-server", to: "mcp/src/index.js", via: "elements" }],
      },
      unresolved: { total: 0, limited: false, byRelation: {}, edges: [] },
    },
  },
  domainMatrix: {
    operation: "domain_matrix",
    project: "project",
    summary: {
      domains: 2,
      nodes: 5,
      assignedNodes: 4,
      unassignedNodes: 1,
      crossDomainEdges: 1,
      selfDomainEdges: 2,
      externalEdges: 1,
      unresolvedEdges: 0,
    },
    domains: [
      {
        slug: "domains/ai-agent-partner",
        node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        nodes: 3,
        outgoing: 1,
        incoming: 0,
        selfEdges: 2,
        externalEdges: 1,
        unresolvedEdges: 0,
      },
      {
        slug: "domains/vault-local-first",
        node: { slug: "domains/vault-local-first", kind: "domain", title: "Vault Local First" },
        nodes: 1,
        outgoing: 0,
        incoming: 1,
        selfEdges: 0,
        externalEdges: 0,
        unresolvedEdges: 0,
      },
    ],
    connections: {
      total: 1,
      limited: false,
      rows: [
        {
          from: "domains/ai-agent-partner",
          to: "domains/vault-local-first",
          count: 1,
          byRelation: { relates: 1 },
          examples: [{ from: "capabilities/mcp-server", to: "domains/vault-local-first", via: "relates" }],
        },
      ],
    },
  },
  components: {
    operation: "components",
    totalComponents: 2,
    largestSize: 4,
    singletonCount: 1,
    limited: false,
    components: [
      {
        id: 1,
        size: 4,
        kinds: { project: 1, domain: 1, capability: 2 },
        nodeLimited: false,
        nodes: [
          { slug: "project", kind: "project", title: "Project" },
          { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
          { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
          { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" },
        ],
      },
      {
        id: 2,
        size: 1,
        kinds: { capability: 1 },
        nodeLimited: false,
        nodes: [{ slug: "capabilities/orphan", kind: "capability", title: "Orphan" }],
      },
    ],
  },
  relationCheck: {
    operation: "relation_check",
    from: "capabilities/mcp-server",
    to: "domains/ai-agent-partner",
    relation: "domain",
    fromKind: "capability",
    toKind: "domain",
    exists: true,
    verdict: "already_exists",
    recommendation: {
      decision: "skip_existing",
      severity: "info",
      reason: "Exact edge already exists; do not add another relation.",
    },
    matchingEdges: [
      {
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        via: "domain",
      },
    ],
    inverseEdges: [],
    schemaPattern: {
      fromKind: "capability",
      relation: "domain",
      toKind: "domain",
      count: 1,
    },
  },
  maintenancePlan: {
    operation: "maintenance_plan",
    sideEffect: false,
    graphHash: "abc123",
    summary: {
      totalActions: 2,
      filteredActions: 2,
      remainingActions: 2,
      executableActions: 1,
      reviewActions: 1,
      compileIssues: 0,
      dependencyCycles: 0,
      canonicalizationActions: 0,
      danglingReferences: 0,
      relationRecommendations: 1,
      externalElementRefs: 0,
      externalElementRefsIgnored: 0,
      unassignedNodes: 1,
      emptyDomains: 0,
    },
    filters: {
      executableOnly: false,
      phases: [],
      severities: [],
      kinds: [],
    },
    cursor: {
      afterActionId: null,
      found: true,
      reason: null,
      startIndex: 0,
      nextAfterActionId: "maint_review",
      hasMore: false,
    },
    byPhase: { link: 1, review: 1 },
    bySeverity: { warn: 1, info: 1 },
    byKind: { add_missing_relation: 1, unassigned_node: 1 },
    limited: false,
    nextExecutableAction: {
      id: "maint_link",
      phase: "link",
      kind: "add_missing_relation",
      severity: "warn",
      score: 1,
      reason: "Missing containment relation.",
      executable: true,
      proposedAction: {
        tool: "add_relation",
        args: { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", type: "capabilities" },
      },
      nodes: {
        from: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        to: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
      },
    },
    nextReviewAction: {
      id: "maint_review",
      phase: "review",
      kind: "unassigned_node",
      severity: "info",
      score: 0.5,
      reason: "Node has no project assignment.",
      executable: false,
    },
    actions: [
      {
        id: "maint_link",
        phase: "link",
        kind: "add_missing_relation",
        severity: "warn",
        score: 1,
        reason: "Missing containment relation.",
        executable: true,
        proposedAction: {
          tool: "add_relation",
          args: { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", type: "capabilities" },
        },
        nodes: {
          from: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
          to: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
        },
      },
      {
        id: "maint_review",
        phase: "review",
        kind: "unassigned_node",
        severity: "info",
        score: 0.5,
        reason: "Node has no project assignment.",
        executable: false,
      },
    ],
  },
  maintenancePlanMissingCursor: {
    operation: "maintenance_plan",
    sideEffect: false,
    graphHash: "abc123",
    summary: {
      totalActions: 2,
      filteredActions: 2,
      remainingActions: 0,
      executableActions: 1,
      reviewActions: 1,
      compileIssues: 0,
      dependencyCycles: 0,
      canonicalizationActions: 0,
      danglingReferences: 0,
      relationRecommendations: 1,
      externalElementRefs: 0,
      externalElementRefsIgnored: 0,
      unassignedNodes: 1,
      emptyDomains: 0,
    },
    filters: {
      executableOnly: false,
      phases: [],
      severities: [],
      kinds: [],
    },
    cursor: {
      afterActionId: "maint_missing",
      found: false,
      reason: "afterActionId not found in filtered maintenance actions",
      startIndex: null,
      nextAfterActionId: null,
      hasMore: false,
    },
    byPhase: {},
    bySeverity: {},
    byKind: {},
    limited: false,
    nextExecutableAction: null,
    nextReviewAction: null,
    actions: [],
  },
  growthPlan: {
    operation: "growth_plan",
    summary: {
      relationRecommendations: 1,
      externalElementRefs: 1,
      externalElementRefsIgnored: 0,
      danglingReferences: 1,
      unassignedNodes: 1,
      emptyDomains: 1,
      totalActions: 3,
    },
    relationRecommendations: {
      operation: "recommend_relations",
      mode: "domain_containment",
      totalRecommendations: 1,
      limited: false,
      recommendations: [
        {
          kind: "missing_domain_containment",
          score: 1,
          from: "domains/ai-agent-partner",
          to: "capabilities/mcp-server",
          relation: "capabilities",
          reason: "Missing containment relation.",
          proposedAction: {
            tool: "add_relation",
            args: { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", type: "capabilities" },
          },
        },
      ],
    },
    externalElementRefs: {
      total: 1,
      limited: false,
      rows: [
        {
          kind: "materialize_external_element",
          score: 0.8,
          from: "capabilities/mcp-server",
          ref: "mcp/src/index.js",
          suggestedSlug: "elements/mcp-src-index",
          reason: "Materialize external element.",
          proposedAction: {
            tool: "add_concept",
            args: { slug: "elements/mcp-src-index", kind: "element", title: "Index" },
          },
        },
      ],
    },
    danglingReferences: {
      total: 1,
      limited: false,
      rows: [
        {
          kind: "resolve_dangling_reference",
          score: 0.7,
          from: "capabilities/mcp-server",
          ref: "capabilities/missing",
          relation: "dependencies",
          inferredKind: "capability",
          suggestedSlug: "capabilities/missing",
          reason: "Resolve dangling reference.",
          proposedAction: {
            tool: "add_concept",
            args: { slug: "capabilities/missing", kind: "capability", title: "Missing" },
          },
        },
      ],
    },
    unassignedNodes: {
      total: 1,
      limited: false,
      rows: [
        {
          kind: "unassigned_node",
          score: 0.5,
          slug: "capabilities/orphan",
          reason: "Assign it to a domain.",
        },
      ],
    },
    emptyDomains: {
      total: 1,
      limited: false,
      rows: [
        {
          kind: "empty_domain",
          score: 0.4,
          slug: "domains/empty",
          reason: "Domain has no contained capability or element nodes yet.",
        },
      ],
    },
  },
  relationRecommendations: {
    operation: "recommend_relations",
    mode: "domain_containment",
    totalRecommendations: 1,
    limited: false,
    recommendations: [
      {
        kind: "missing_domain_containment",
        score: 1,
        from: "domains/ai-agent-partner",
        to: "capabilities/mcp-server",
        relation: "capabilities",
        reason: "Missing containment relation.",
        proposedAction: {
          tool: "add_relation",
          args: { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", type: "capabilities" },
        },
      },
    ],
  },
  cycles: {
    operation: "cycles",
    relationTypes: ["dependencies"],
    maxDepth: 8,
    totalCycles: 1,
    limited: false,
    cycles: [
      {
        id: "capabilities/a>capabilities/b>capabilities/a",
        length: 2,
        nodes: ["capabilities/a", "capabilities/b", "capabilities/a"],
        edges: [
          { from: "capabilities/a", to: "capabilities/b", via: "dependencies" },
          { from: "capabilities/b", to: "capabilities/a", via: "dependencies" },
        ],
      },
    ],
  },
  topologicalOrder: {
    operation: "topological_order",
    relationTypes: ["dependencies"],
    prerequisiteFirst: true,
    includeIsolated: false,
    acyclic: true,
    totalNodes: 3,
    orderedCount: 3,
    selectedEdges: 2,
    limited: false,
    order: [
      { rank: 0, slug: "capabilities/storage", node: { slug: "capabilities/storage", kind: "capability", title: "Storage" } },
      { rank: 1, slug: "capabilities/auth", node: { slug: "capabilities/auth", kind: "capability", title: "Auth" } },
      { rank: 2, slug: "capabilities/app", node: { slug: "capabilities/app", kind: "capability", title: "App" } },
    ],
    layers: [
      { rank: 0, nodes: [{ slug: "capabilities/storage", kind: "capability", title: "Storage" }] },
      { rank: 1, nodes: [{ slug: "capabilities/auth", kind: "capability", title: "Auth" }] },
      { rank: 2, nodes: [{ slug: "capabilities/app", kind: "capability", title: "App" }] },
    ],
    blocked: [],
  },
  lineage: {
    operation: "lineage",
    center: "capabilities/mcp-server",
    node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    depth: 3,
    ancestors: {
      total: 2,
      limited: false,
      nodes: [
        { slug: "domains/ai-agent-partner", distance: 1, via: "domain", node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
        { slug: "project", distance: 2, via: "domains", node: { slug: "project", kind: "project", title: "Project" } },
      ],
    },
    descendants: {
      total: 1,
      limited: false,
      nodes: [
        { slug: "elements/mcp-sdk", distance: 1, via: "elements", node: { slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" } },
      ],
    },
    edges: [
      { from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" },
      { from: "project", to: "domains/ai-agent-partner", via: "domains" },
      { from: "capabilities/mcp-server", to: "elements/mcp-sdk", via: "elements" },
    ],
  },
  containmentTree: {
    operation: "containment_tree",
    root: "project",
    depth: 3,
    totalRoots: 1,
    emittedNodes: 4,
    limited: false,
    roots: [
      {
        slug: "project",
        via: null,
        distance: 0,
        node: { slug: "project", kind: "project", title: "Project" },
        children: [
          {
            slug: "domains/ai-agent-partner",
            via: "domains",
            distance: 1,
            node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
            children: [
              {
                slug: "capabilities/mcp-server",
                via: "capabilities",
                distance: 2,
                node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
                children: [
                  {
                    slug: "elements/mcp-sdk",
                    via: "elements",
                    distance: 3,
                    node: { slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" },
                    children: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    cycles: [],
  },
  reachability: {
    operation: "reachability",
    start: "capabilities/mcp-server",
    node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    direction: "outgoing",
    depth: 2,
    summary: {
      reachableNodes: 2,
      traversedEdges: 2,
      layers: 2,
      terminalNodes: 1,
    },
    byKind: { domain: 1, element: 1 },
    byRelation: { domain: 1, elements: 1 },
    layers: [
      {
        distance: 1,
        total: 1,
        nodes: [{ slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" }],
      },
      {
        distance: 2,
        total: 1,
        nodes: [{ slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" }],
      },
    ],
    paths: {
      total: 2,
      limited: false,
      rows: [
        {
          slug: "domains/ai-agent-partner",
          distance: 1,
          path: ["capabilities/mcp-server", "domains/ai-agent-partner"],
          edges: [{ from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" }],
          node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        },
        {
          slug: "elements/mcp-sdk",
          distance: 2,
          path: ["capabilities/mcp-server", "domains/ai-agent-partner", "elements/mcp-sdk"],
          edges: [
            { from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" },
            { from: "domains/ai-agent-partner", to: "elements/mcp-sdk", via: "elements" },
          ],
          node: { slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" },
        },
      ],
    },
    terminalNodes: [{ slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" }],
    edges: {
      total: 2,
      limited: false,
      rows: [
        { from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" },
        { from: "domains/ai-agent-partner", to: "elements/mcp-sdk", via: "elements" },
      ],
    },
  },
  impact: {
    operation: "impact",
    center: "capabilities/mcp-server",
    direction: "incoming",
    depth: 2,
    total: 2,
    limited: false,
    nodes: [
      { slug: "domains/ai-agent-partner", distance: 1, node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
      { slug: "capabilities/ontology-sync-skill", distance: 1, node: { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" } },
    ],
    edges: [
      { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", via: "capabilities" },
      { from: "capabilities/ontology-sync-skill", to: "capabilities/mcp-server", via: "dependencies" },
    ],
  },
  blastRadius: {
    operation: "blast_radius",
    center: "capabilities/mcp-server",
    node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    direction: "incoming",
    depth: 2,
    risk: "medium",
    summary: {
      affectedNodes: 2,
      affectedEdges: 2,
      affectedKinds: 2,
      affectedDomains: 1,
      crossDomainEdges: 0,
    },
    byKind: { capability: 1, domain: 1 },
    byDomain: { "domains/ai-agent-partner": 2 },
    nodes: {
      total: 2,
      limited: false,
      rows: [
        { slug: "domains/ai-agent-partner", distance: 1, domain: "domains/ai-agent-partner", node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
        { slug: "capabilities/ontology-sync-skill", distance: 1, domain: "domains/ai-agent-partner", node: { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" } },
      ],
    },
    edges: {
      total: 2,
      limited: false,
      rows: [
        { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", via: "capabilities", fromDomain: "domains/ai-agent-partner", toDomain: "domains/ai-agent-partner", crossDomain: false },
        { from: "capabilities/ontology-sync-skill", to: "capabilities/mcp-server", via: "dependencies", fromDomain: "domains/ai-agent-partner", toDomain: "domains/ai-agent-partner", crossDomain: false },
      ],
    },
  },
  subgraph: {
    operation: "subgraph",
    seed: "capabilities/mcp-server",
    direction: "both",
    depth: 1,
    totalNodes: 3,
    totalEdges: 2,
    limited: false,
    nodes: [
      { slug: "capabilities/mcp-server", distance: 0, node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" } },
      { slug: "domains/ai-agent-partner", distance: 1, node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
      { slug: "elements/mcp-sdk", distance: 1, node: { slug: "elements/mcp-sdk", kind: "element", title: "MCP SDK" } },
    ],
    edges: [
      { from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" },
      { from: "capabilities/mcp-server", to: "elements/mcp-sdk", via: "elements" },
    ],
  },
  schema: {
    operation: "schema",
    totalPatterns: 2,
    limited: false,
    patterns: [
      { fromKind: "capability", relation: "domain", toKind: "domain", count: 1, resolved: 1, external: 0 },
      { fromKind: "capability", relation: "elements", toKind: "external", count: 1, resolved: 0, external: 1 },
    ],
  },
  facets: {
    operation: "facets",
    graph: {
      nodes: 3,
      edges: 2,
      resolvedEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
    },
    nodes: {
      byKind: { capability: 1, domain: 1, element: 1 },
      byDomain: { "domains/ai-agent-partner": 2 },
      byDegreeBucket: { "0": 0, "1": 2, "2-4": 1, "5-9": 0, "10+": 0 },
      topByDegree: [{ slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" }],
    },
    edges: {
      byRelation: { domain: 1, elements: 1 },
      byResolution: { resolved: 1, external: 1, unresolved: 0 },
      topPatterns: [
        { fromKind: "capability", relation: "domain", toKind: "domain", count: 1, resolved: 1, external: 0 },
      ],
    },
  },
  matchNodes: {
    operation: "match_nodes",
    filters: {
      kind: "capability",
      domain: null,
      slugContains: "mcp",
      minDegree: null,
      maxDegree: null,
      minInDegree: null,
      minOutDegree: null,
      hasIncoming: null,
      hasOutgoing: null,
      sort: "degree",
    },
    totalMatches: 1,
    limited: false,
    nodes: [
      {
        slug: "capabilities/mcp-server",
        kind: "capability",
        title: "MCP Server",
        inDegree: 3,
        outDegree: 4,
        degree: 7,
      },
    ],
  },
  matchEdges: {
    operation: "match_edges",
    filters: {
      from: "capabilities/mcp-server",
      to: null,
      fromKind: null,
      toKind: null,
      types: null,
      includeExternal: true,
      includeUnresolved: false,
    },
    totalMatches: 2,
    limited: false,
    edges: [
      {
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        via: "domain",
        resolved: true,
        external: false,
        fromNode: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
        toNode: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        toKind: "domain",
      },
      {
        from: "capabilities/mcp-server",
        to: "mcp/src/index.js",
        via: "elements",
        resolved: false,
        external: true,
        fromNode: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
        toNode: null,
        toKind: "external",
      },
    ],
  },
  nodeProfile: {
    operation: "node_profile",
    center: "capabilities/mcp-server",
    node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    aliases: ["mcp-server"],
    degree: { in: 2, out: 3, total: 5 },
    edges: {
      incoming: {
        total: 1,
        byRelation: { dependencies: 1 },
        limited: false,
        edges: [
          {
            from: "capabilities/ontology-sync-skill",
            to: "capabilities/mcp-server",
            via: "dependencies",
            resolved: true,
            external: false,
            otherNode: { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" },
            otherKind: "capability",
          },
        ],
      },
      outgoing: {
        total: 1,
        byRelation: { domain: 1 },
        limited: false,
        edges: [
          {
            from: "capabilities/mcp-server",
            to: "domains/ai-agent-partner",
            via: "domain",
            resolved: true,
            external: false,
            otherNode: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
            otherKind: "domain",
          },
        ],
      },
    },
    containment: {
      parents: [
        { slug: "domains/ai-agent-partner", via: "domain", node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
      ],
      parentLimited: false,
      children: [],
      childLimited: false,
    },
    lineage: {
      depth: 3,
      ancestors: {
        total: 1,
        limited: false,
        nodes: [
          { slug: "domains/ai-agent-partner", distance: 1, via: "domain", node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" } },
        ],
      },
      descendants: { total: 0, limited: false, nodes: [] },
    },
  },
  centrality: {
    operation: "centrality",
    graph: { nodes: 3, edges: 4, resolvedEdges: 3, graphHash: "abc123" },
    parameters: { types: null, iterations: 20, limit: 8 },
    rankings: {
      pageRank: [
        {
          slug: "capabilities/mcp-server",
          kind: "capability",
          title: "MCP Server",
          inDegree: 2,
          outDegree: 3,
          degree: 5,
          pageRank: 0.42,
          bridgeScore: 6,
        },
        {
          slug: "domains/ai-agent-partner",
          kind: "domain",
          title: "AI Agent Partner",
          inDegree: 1,
          outDegree: 1,
          degree: 2,
          pageRank: 0.2,
          bridgeScore: 1,
        },
      ],
      bridges: [
        {
          slug: "capabilities/mcp-server",
          kind: "capability",
          title: "MCP Server",
          inDegree: 2,
          outDegree: 3,
          degree: 5,
          pageRank: 0.42,
          bridgeScore: 6,
        },
      ],
      authorities: [
        {
          slug: "capabilities/mcp-server",
          kind: "capability",
          title: "MCP Server",
          inDegree: 2,
          outDegree: 3,
          degree: 5,
          pageRank: 0.42,
          bridgeScore: 6,
        },
      ],
      hubs: [
        {
          slug: "capabilities/mcp-server",
          kind: "capability",
          title: "MCP Server",
          inDegree: 2,
          outDegree: 3,
          degree: 5,
          pageRank: 0.42,
          bridgeScore: 6,
        },
      ],
    },
  },
  communities: {
    operation: "communities",
    parameters: { types: null, iterations: 20, limit: 6, nodeLimit: 6 },
    summary: { communities: 2, largestSize: 3, singletonCount: 1, crossCommunityEdges: 1 },
    limited: false,
    communities: [
      {
        id: 1,
        label: "domains/ai-agent-partner",
        size: 3,
        internalEdges: 2,
        boundaryEdges: 1,
        kinds: { domain: 1, capability: 2 },
        domains: { "domains/ai-agent-partner": 3 },
        representative: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
        nodeLimited: false,
        nodes: [
          { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
          { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
          { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" },
        ],
      },
      {
        id: 2,
        label: "README",
        size: 1,
        internalEdges: 0,
        boundaryEdges: 0,
        kinds: { "vault-readme": 1 },
        domains: {},
        representative: { slug: "README", kind: "vault-readme", title: "Readme" },
        nodeLimited: false,
        nodes: [{ slug: "README", kind: "vault-readme", title: "Readme" }],
      },
    ],
    crossCommunityEdges: {
      total: 1,
      limited: false,
      rows: [
        {
          from: "capabilities/mcp-server",
          to: "domains/vault-local-first",
          via: "relates",
          fromCommunity: 1,
          toCommunity: 2,
        },
      ],
    },
  },
  similarNodes: {
    operation: "similar_nodes",
    source: {
      mode: "candidate",
      slug: "capabilities/mcp-server-v2",
      kind: "capability",
      title: "MCP Server",
      domain: "domains/ai-agent-partner",
    },
    parameters: { types: null, limit: 5 },
    totalMatches: 1,
    limited: false,
    matches: [
      {
        node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
        score: 0.9,
        signals: { slug: 0.2, title: 0.35, kind: 0.1, domain: 0.1, neighbors: 0.15 },
        sharedNeighbors: [
          { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        ],
      },
    ],
  },
  explainRelation: {
    operation: "explain_relation",
    from: "capabilities/mcp-server",
    to: "domains/vault-local-first",
    fromNode: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    toNode: { slug: "domains/vault-local-first", kind: "domain", title: "Vault Local First" },
    verdict: "path",
    domains: { from: "domains/ai-agent-partner", to: "domains/vault-local-first", sameDomain: false },
    direct: { total: 0, edges: [] },
    shortestPath: {
      found: true,
      direction: "undirected",
      maxHops: 4,
      hopCount: 2,
      hops: ["capabilities/mcp-server", "domains/ai-agent-partner", "domains/vault-local-first"],
      edges: [
        { from: "capabilities/mcp-server", to: "domains/ai-agent-partner", via: "domain" },
        { from: "domains/ai-agent-partner", to: "domains/vault-local-first", via: "relates" },
      ],
    },
    commonNeighbors: {
      total: 1,
      limited: false,
      rows: [
        {
          slug: "domains/ai-agent-partner",
          node: { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
          fromEdges: [
            {
              from: "capabilities/mcp-server",
              to: "domains/ai-agent-partner",
              via: "domain",
              direction: "outgoing",
            },
          ],
          toEdges: [
            {
              from: "domains/ai-agent-partner",
              to: "domains/vault-local-first",
              via: "relates",
              direction: "outgoing",
            },
          ],
        },
      ],
    },
  },
  neighbors: {
    operation: "neighbors",
    center: "capabilities/mcp-server",
    node: { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
    total: 2,
    limited: false,
    edges: [
      {
        direction: "outgoing",
        id: "capabilities/mcp-server:domain:domains/ai-agent-partner",
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        via: "domain",
        ref: "domains/ai-agent-partner",
        resolved: true,
        external: false,
      },
      {
        direction: "incoming",
        id: "capabilities/ontology-sync-skill:dependencies:capabilities/mcp-server",
        from: "capabilities/ontology-sync-skill",
        to: "capabilities/mcp-server",
        via: "dependencies",
        ref: "capabilities/mcp-server",
        resolved: true,
        external: false,
      },
    ],
    nodes: [
      { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
      { slug: "capabilities/ontology-sync-skill", kind: "capability", title: "Ontology Sync Skill" },
    ],
  },
  queryPath: {
    operation: "path",
    from: "capabilities/mcp-server",
    to: "domains/vault-local-first",
    found: true,
    hopCount: 2,
    hops: ["capabilities/mcp-server", "domains/ai-agent-partner", "domains/vault-local-first"],
    edges: [
      {
        from: "capabilities/mcp-server",
        to: "domains/ai-agent-partner",
        via: "domain",
        traversedFrom: "capabilities/mcp-server",
        traversedTo: "domains/ai-agent-partner",
      },
      {
        from: "domains/ai-agent-partner",
        to: "domains/vault-local-first",
        via: "relates",
        traversedFrom: "domains/ai-agent-partner",
        traversedTo: "domains/vault-local-first",
      },
    ],
  },
  projectScope: {
    operation: "project_scope",
    project: "project",
    node: { slug: "project", kind: "project", title: "Project" },
    summary: {
      nodes: 3,
      internalEdges: 2,
      boundaryEdges: 1,
      externalEdges: 1,
      unresolvedEdges: 0,
    },
    byKind: { project: 1, domain: 1, capability: 1 },
    byDomain: { "domains/ai-agent-partner": 2 },
    nodes: {
      total: 3,
      limited: false,
      rows: [
        { slug: "project", kind: "project", title: "Project" },
        { slug: "domains/ai-agent-partner", kind: "domain", title: "AI Agent Partner" },
        { slug: "capabilities/mcp-server", kind: "capability", title: "MCP Server" },
      ],
    },
    edges: {
      internal: {
        total: 2,
        byRelation: { domains: 1, capabilities: 1 },
        limited: false,
        edges: [
          { from: "project", to: "domains/ai-agent-partner", via: "domains", toScope: "internal" },
          { from: "domains/ai-agent-partner", to: "capabilities/mcp-server", via: "capabilities", toScope: "internal" },
        ],
      },
      boundary: {
        total: 1,
        byRelation: { relates: 1 },
        limited: false,
        edges: [
          { from: "capabilities/mcp-server", to: "domains/vault-local-first", via: "relates", toScope: "boundary" },
        ],
      },
      external: {
        total: 1,
        byRelation: { elements: 1 },
        limited: false,
        edges: [
          { from: "capabilities/mcp-server", to: "mcp/src/index.js", via: "elements", toScope: "external" },
        ],
      },
      unresolved: { total: 0, byRelation: {}, limited: false, edges: [] },
    },
  },
  strictArgs: {
    result: {
      isError: true,
      content: [{ text: 'Unknown argument "lmit" for list_concepts. Did you mean "limit"? Allowed arguments: domain, kind, limit, since, summary. Received arguments: lmit.' }],
      structuredContent: {
        ok: false,
        errorCode: "unknown_argument",
        error: 'Unknown argument "lmit" for list_concepts. Did you mean "limit"? Allowed arguments: domain, kind, limit, since, summary. Received arguments: lmit.',
        toolName: "list_concepts",
        receivedArgument: "lmit",
        suggestion: "limit",
        unknownArguments: [{ name: "lmit", suggestion: "limit" }],
        allowedArguments: ["domain", "kind", "limit", "offset", "since", "summary"],
        receivedArguments: ["lmit"],
      },
    },
  },
  strictMultiArgs: {
    result: {
      isError: true,
      content: [{ text: 'Unknown arguments for list_concepts: "lmit" (did you mean "limit"?), "summry" (did you mean "summary"?). Allowed arguments: domain, kind, limit, since, summary. Received arguments: lmit, summry.' }],
      structuredContent: {
        ok: false,
        errorCode: "unknown_argument",
        error: 'Unknown arguments for list_concepts: "lmit" (did you mean "limit"?), "summry" (did you mean "summary"?). Allowed arguments: domain, kind, limit, since, summary. Received arguments: lmit, summry.',
        toolName: "list_concepts",
        receivedArguments: ["lmit", "summry"],
        unknownArguments: [
          { name: "lmit", suggestion: "limit" },
          { name: "summry", suggestion: "summary" },
        ],
        allowedArguments: ["domain", "kind", "limit", "offset", "since", "summary"],
      },
    },
  },
  strictEnum: {
    result: {
      isError: true,
      content: [{ text: `operation must be one of: ${QUERY_ONTOLOGY_OPERATIONS.join(", ")}. Received: "overveiw". Did you mean "overview"?` }],
      structuredContent: {
        ok: false,
        errorCode: "invalid_arguments",
        error: `operation must be one of: ${QUERY_ONTOLOGY_OPERATIONS.join(", ")}. Received: "overveiw". Did you mean "overview"?`,
        valueName: "operation",
        receivedValue: "overveiw",
        suggestion: "overview",
        allowedValues: QUERY_ONTOLOGY_OPERATIONS,
      },
    },
  },
  strictUnknownTool: {
    result: {
      isError: true,
      content: [{ text: `Error: Unknown tool: list_concept. Did you mean "list_concepts"? Allowed tools: ${[...EXPECTED_TOOLS].sort().join(", ")}.` }],
      structuredContent: {
        ok: false,
        errorCode: "unknown_tool",
        error: `Unknown tool: list_concept. Did you mean "list_concepts"? Allowed tools: ${[...EXPECTED_TOOLS].sort().join(", ")}.`,
        receivedTool: "list_concept",
        suggestion: "list_concepts",
        allowedTools: [...EXPECTED_TOOLS].sort(),
      },
    },
  },
  strictMaintenancePhaseFilter: strictValueErrorResponse("phases items", ["validate", "repair", "link", "materialize", "review"], "repiar", "repair"),
  strictMaintenanceSeverityFilter: strictValueErrorResponse("severities items", ["fail", "warn", "info"], "fatal", "fail"),
  // Derived, not transcribed — a hand-copied list here silently stopped matching
  // the server the day the node-eligibility gate added two kinds (2026-07-31).
  strictMaintenanceKindFilter: strictValueErrorResponse("kinds items", [...MAINTENANCE_KIND_VALUES], "add_mising_relation", "add_missing_relation"),
  strictRelationFilter: strictValueErrorResponse("dependencyTypes items", ["domains", "domain", "capabilities", "elements", "dependencies", "depends_on", "relates", "contains", "describes"], "depend_on", "depends_on"),
  strictFindNeighborsTypeFilter: strictValueErrorResponse("types items", ["domains", "domain", "capabilities", "elements", "dependencies", "depends_on", "relates", "contains", "describes"], "depend_on", "depends_on"),
  strictFindOrphansKindFilter: strictValueErrorResponse("kind", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictFindOrphansExcludeKindFilter: strictValueErrorResponse("excludeKinds items", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictQueryConceptsKindFilter: strictValueErrorResponse("kind", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictQueryConceptsHasKeyFilter: strictValueErrorResponse("has key", [...GRAPH_ARRAY_KEYS], "capabilties", "capabilities"),
  strictListConceptsKindFilter: strictValueErrorResponse("kind", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictRelationCheck: strictValueErrorResponse("type", ["domains", "domain", "capabilities", "elements", "dependencies", "depends_on", "relates", "contains", "describes"], "depend_on", "depends_on"),
  strictAddRelation: strictValueErrorResponse("type", ["depends_on", "relates", "contains", "describes", "domains", "capabilities", "elements", "domain"], "depend_on", "depends_on"),
  strictGraphKindFilter: strictValueErrorResponse("kind", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictRecommendRelationsKindFilter: strictValueErrorResponse("kind", ["capability", "element"], "capabilty", "capability"),
  strictRecommendRelationsUnsupportedKindFilter: strictValueErrorResponse("kind", ["capability", "element"], "domain"),
  strictMatchNodesSortFilter: strictValueErrorResponse("sort", ["degree", "inDegree", "outDegree", "slug"], "outDegre", "outDegree"),
  strictMatchEdgesTypeFilter: strictValueErrorResponse("type", ["domains", "domain", "capabilities", "elements", "dependencies", "depends_on", "relates", "contains", "describes"], "depend_on", "depends_on"),
  strictGraphFromKindFilter: strictValueErrorResponse("fromKind", ["project", "domain", "capability", "element", "document", "vault-readme"], "capabilty", "capability"),
  strictGraphToKindFilter: strictValueErrorResponse("toKind", ["project", "domain", "capability", "element", "document", "vault-readme", "external", "unresolved"], "externl", "external"),
  getConceptsBatchCap: batchCapError("slugs"),
  addConceptsBatchCap: batchCapError("concepts"),
  addRelationsBatchCap: batchCapError("relations"),
};

for (const value of Object.values(okShape)) {
  const result = value?.result;
  const text = result?.content?.[0]?.text;
  if (result?.isError === true && typeof text === "string" && !result.structuredContent) {
    result.structuredContent = { ok: false, errorCode: "invalid_arguments", error: text };
  }
}

for (const [resultField, structuredField] of [
  ["brief", "briefStructured"],
  ["tunedBrief", "tunedBriefStructured"],
  ["health", "healthStructured"],
  ["tunedHealth", "tunedHealthStructured"],
  ["compiledIndexes", "compiledIndexesStructured"],
  ["patternWalk", "patternWalkStructured"],
  ["allPaths", "allPathsStructured"],
  ["allPathsPlan", "allPathsPlanStructured"],
  ["projectMapPlan", "projectMapPlanStructured"],
  ["projectMap", "projectMapStructured"],
  ["domainProfile", "domainProfileStructured"],
  ["domainMatrix", "domainMatrixStructured"],
  ["components", "componentsStructured"],
  ["relationCheck", "relationCheckStructured"],
  ["maintenancePlan", "maintenancePlanStructured"],
  ["maintenancePlanMissingCursor", "maintenancePlanMissingCursorStructured"],
  ["growthPlan", "growthPlanStructured"],
  ["relationRecommendations", "relationRecommendationsStructured"],
  ["cycles", "cyclesStructured"],
  ["topologicalOrder", "topologicalOrderStructured"],
  ["lineage", "lineageStructured"],
  ["containmentTree", "containmentTreeStructured"],
  ["reachability", "reachabilityStructured"],
  ["impact", "impactStructured"],
  ["blastRadius", "blastRadiusStructured"],
  ["subgraph", "subgraphStructured"],
  ["schema", "schemaStructured"],
  ["facets", "facetsStructured"],
  ["matchNodes", "matchNodesStructured"],
  ["matchEdges", "matchEdgesStructured"],
  ["nodeProfile", "nodeProfileStructured"],
  ["centrality", "centralityStructured"],
  ["communities", "communitiesStructured"],
  ["similarNodes", "similarNodesStructured"],
  ["explainRelation", "explainRelationStructured"],
  ["neighbors", "neighborsStructured"],
  ["queryPath", "queryPathStructured"],
  ["projectScope", "projectScopeStructured"],
]) {
  okShape[structuredField] ??= structuredClone(okShape[resultField]);
}
