import { z } from 'zod';

const envSchema = z.object({
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1),
  NEXT_PUBLIC_DEMO_LOGIN_EMAIL: z.string().optional(),
  NEXT_PUBLIC_DEMO_LOGIN_PASSWORD: z.string().optional(),
  NEXT_PUBLIC_DEV_ADMIN_BYPASS: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_USE_EMULATORS: z.string().optional(),
  NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: z.string().optional(),
  NEXT_PUBLIC_FUNCTIONS_EMULATOR_HOST: z.string().optional(),
  NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION: z.string().optional(),
  NEXT_PUBLIC_DEV_ADMIN_PROXY_ORIGIN: z.string().optional(),
});

const parsed = envSchema.safeParse({
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_DEMO_LOGIN_EMAIL: process.env.NEXT_PUBLIC_DEMO_LOGIN_EMAIL,
  NEXT_PUBLIC_DEMO_LOGIN_PASSWORD: process.env.NEXT_PUBLIC_DEMO_LOGIN_PASSWORD,
  NEXT_PUBLIC_DEV_ADMIN_BYPASS: process.env.NEXT_PUBLIC_DEV_ADMIN_BYPASS,
  NEXT_PUBLIC_FIREBASE_USE_EMULATORS: process.env.NEXT_PUBLIC_FIREBASE_USE_EMULATORS,
  NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST: process.env.NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST,
  NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST,
  NEXT_PUBLIC_FUNCTIONS_EMULATOR_HOST: process.env.NEXT_PUBLIC_FUNCTIONS_EMULATOR_HOST,
  NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION: process.env.NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION,
  NEXT_PUBLIC_DEV_ADMIN_PROXY_ORIGIN: process.env.NEXT_PUBLIC_DEV_ADMIN_PROXY_ORIGIN,
});

if (!parsed.success) {
  // 빌드 시점에 .env.local이 없을 수 있으므로 경고만 하고 계속 진행.
  // 실제 Firebase SDK 호출 시점에 빈 값이면 SDK가 에러를 던진다.
  console.warn(
    '[env] Firebase 환경변수가 누락되었습니다. .env.example을 참고해 .env.local을 설정하세요.',
  );
}

export const env = parsed.success
  ? parsed.data
  : ({
      NEXT_PUBLIC_FIREBASE_API_KEY: '',
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: '',
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: '',
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: '',
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '',
      NEXT_PUBLIC_FIREBASE_APP_ID: '',
      NEXT_PUBLIC_DEMO_LOGIN_EMAIL: '',
      NEXT_PUBLIC_DEMO_LOGIN_PASSWORD: '',
      NEXT_PUBLIC_DEV_ADMIN_BYPASS: '',
      NEXT_PUBLIC_FIREBASE_USE_EMULATORS: '',
      NEXT_PUBLIC_FIRESTORE_EMULATOR_HOST: '',
      NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: '',
      NEXT_PUBLIC_FUNCTIONS_EMULATOR_HOST: '',
      NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION: '',
      NEXT_PUBLIC_DEV_ADMIN_PROXY_ORIGIN: '',
    } as const);
