/**
 * GENERATED by `node scripts/build-mcp-catalogue.mjs`. Do not edit by hand.
 *
 * Captured 2026-09-07: 4 services, 1 hosted
 * addresses and 4 programs that run on this computer.
 *
 * **This list is not complete and Atlas has not audited any server on it.** It
 * is a shortcut past typing a package name, nothing more; "By hand" reaches
 * every server that exists. Rows marked `registry` were read from the official
 * MCP Registry, whose metadata is CC0-1.0; rows marked `curated` were read off
 * the vendor's own page on the date beside them.
 *
 * Nothing here is fetched while the app runs. Refreshing it is a person running
 * the script and committing the diff.
 */
import type { CatalogueEntry } from './mcp-catalogue';

/** The day a person ran the generator. The screen says it out loud. */
export const MCP_CATALOGUE_CAPTURED_AT = '2026-09-07';

export const MCP_CATALOGUE: readonly CatalogueEntry[] = [
  {
    "id": "notion",
    "name": "notion",
    "title": "Notion",
    "summary": "Read and write the pages and databases in your Notion workspace.",
    "docsUrl": "https://developers.notion.com/guides/mcp/get-started-with-mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "com.notion/mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@notionhq/notion-mcp-server",
        "version": "2.5.1",
        "args": [
          "-y",
          "@notionhq/notion-mcp-server@2.5.1"
        ],
        "env": [
          {
            "name": "NOTION_TOKEN",
            "secret": true,
            "required": true,
            "issueUrl": "https://www.notion.so/profile/integrations"
          }
        ],
        "source": "curated"
      }
    ]
  },
  {
    "id": "github",
    "name": "github",
    "title": "GitHub",
    "summary": "Read and write issues, pull requests, code and wikis on GitHub.",
    "docsUrl": "https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.github/github-mcp-server",
    "registryChecked": true,
    "variants": [
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "docker",
        "packageId": "ghcr.io/github/github-mcp-server",
        "version": "1.12.0",
        "args": [
          "run",
          "-i",
          "--rm",
          "-e",
          "GITHUB_PERSONAL_ACCESS_TOKEN",
          "ghcr.io/github/github-mcp-server:1.12.0@sha256:46cdbbd810faf6f7aed1745ea04057443f5cb9fcadc15c7308add18cf9a83e33"
        ],
        "env": [
          {
            "name": "GITHUB_PERSONAL_ACCESS_TOKEN",
            "secret": true,
            "required": true,
            "issueUrl": "https://github.com/settings/personal-access-tokens/new"
          }
        ],
        "source": "registry"
      }
    ]
  },
  {
    "id": "playwright",
    "name": "playwright",
    "title": "Playwright",
    "summary": "Open web pages and navigate, click, type and read through accessibility snapshots.",
    "docsUrl": "https://github.com/microsoft/playwright-mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.microsoft/playwright-mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@playwright/mcp",
        "version": "0.0.80",
        "args": [
          "-y",
          "@playwright/mcp@0.0.80"
        ],
        "env": [],
        "source": "registry"
      }
    ]
  },
  {
    "id": "context7",
    "name": "context7",
    "title": "Context7",
    "summary": "Current, version-specific documentation and code examples for a library.",
    "docsUrl": "https://github.com/upstash/context7",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.upstash/context7",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.context7.com/mcp",
        "auth": "none",
        "headers": [],
        "source": "registry"
      },
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@upstash/context7-mcp",
        "version": "4.0.5",
        "args": [
          "-y",
          "@upstash/context7-mcp@4.0.5"
        ],
        "env": [
          {
            "name": "CONTEXT7_API_KEY",
            "secret": true,
            "required": false,
            "description": "API key for authentication",
            "issueUrl": "https://context7.com/dashboard"
          }
        ],
        "source": "registry"
      }
    ]
  }
] as const;
