/** The macOS app: readiness, ACP registry, performance budgets, runtime split, and the native vault bridge. */

export const rules = [
  {
    order: 310,
    command: 'pnpm test:desktop:check',
    reason: 'desktop readiness checker contract changed',
    matches: [
      /^scripts\/check-desktop-readiness\.(?:mjs|test\.mjs)$/,
      /^scripts\/desktop-doctor\.(?:mjs|test\.mjs)$/,
      /^scripts\/desktop-smoke\.(?:mjs|test\.mjs)$/,
      /^scripts\/verify-macos-app-launch(?:\.[^/]+)?\.mjs$/,
      /^scripts\/lib\/verify-macos\/[^/]+\.mjs$/,
      /^scripts\/verify-macos-dmg\.mjs$/,
      /^scripts\/verify-macos-install-smoke\.mjs$/,
      /^scripts\/lib\/macos-dmg-layout\.(?:mjs|test\.mjs)$/,
      /^scripts\/lib\/redact-command\.(?:mjs|test\.mjs)$/,
      /^scripts\/check-macos-download-release\.mjs$/,
      /^scripts\/build-updater-manifest\.(?:mjs|test\.mjs)$/,
      /^scripts\/stage-macos-release-assets\.(?:mjs|test\.mjs)$/,
      /^\.github\/workflows\/deploy-pages\.yml$/,
    ],
  },
  {
    order: 330,
    command: 'pnpm acp:registry:check',
    reason: 'ACP launch identity, isolation boundary, or release wiring changed',
    matches: [
      /^scripts\/build-acp-registry\.(?:mjs|test\.mjs)$/,
      /^src-tauri\/src\/acp-registry\.json$/,
      /^src-tauri\/src\/acp\.rs$/,
      /^src-tauri\/src\/acp\/.+\.rs$/,
      /^\.github\/workflows\/release-macos\.yml$/,
    ],
  },
  {
    order: 340,
    // The no-build half of this budget is tests/contract/bundled-vault-budget.contract.test.ts.
    command: 'pnpm build && pnpm desktop:perf',
    reason: 'bundled vault data or the desktop performance budget surface changed — re-measure the static budgets',
    matches: [
      /^src\/entities\/docs-vault\/data\//,
      /^scripts\/build-docs-vault\.mjs$/,
      /^scripts\/check-desktop-performance\.(?:mjs|test\.mjs)$/,
      /^src\/entities\/docs-vault\/lib\/static-(?:vault-source|headings)\.ts$/,
    ],
  },
  {
    order: 350,
    command: 'pnpm test:desktop:runtime',
    reason: 'hosted-vs-installed desktop runtime split changed',
    matches: [
      /^src\/views\/docs-vault\/lib\/persistence(?:\.test)?\.ts$/,
      /^src\/views\/root-entry\/ui\/RootEntryPage(?:\.test)?\.tsx$/,
      /^src\/widgets\/app-settings-menu\/ui\/AppSettingsMenu(?:\.test)?\.tsx$/,
    ],
  },
  // `cargo test` needs the gitignored MCP sidecar binary; `test:desktop:bridge` builds it first.
  {
    order: 370,
    command: 'pnpm test:desktop:bridge',
    reason: 'native macOS vault bridge changed',
    matches: [
      /^src\/shared\/lib\/tauri-vault-fs(?:\.test)?\.ts$/,
      /^src-tauri\/src\/(?:lib\.rs|(?:acp_runtime|acp_session|app_shell|project_source|vault|webview_verify)\/[^/]+\.rs)$/,
      /^src-tauri\/Cargo\.(?:toml|lock)$/,
    ],
  },
  {
    order: 380,
    command: 'pnpm desktop:check',
    reason: 'macOS desktop readiness inputs changed',
    matches: [
      /^scripts\/check-desktop-readiness\.(?:mjs|test\.mjs)$/,
      /^scripts\/quality\/source-language\/(?:inventory|source-paths)\.mjs$/,
      /^scripts\/desktop-doctor\.(?:mjs|test\.mjs)$/,
      /^scripts\/desktop-smoke\.(?:mjs|test\.mjs)$/,
      /^scripts\/verify-macos-dmg\.mjs$/,
      /^scripts\/verify-macos-install-smoke\.mjs$/,
      /^scripts\/lib\/macos-dmg-layout\.(?:mjs|test\.mjs)$/,
      /^scripts\/lib\/redact-command\.(?:mjs|test\.mjs)$/,
      /^scripts\/check-macos-download-release\.mjs$/,
      /^scripts\/stage-macos-release-assets\.(?:mjs|test\.mjs)$/,
      /^docs\/DESKTOP-MACOS\.md$/,
      /^src\/views\/docs-vault\/lib\/persistence(?:\.test)?\.ts$/,
      /^src\/shared\/lib\/tauri-vault-fs(?:\.test)?\.ts$/,
      /^src\/views\/root-entry\/ui\/RootEntryPage(?:\.test)?\.tsx$/,
      /^src\/views\/docs-vault\/ui\/DocsVault(?:Page|Header|DocumentPane|Sidebar)\.tsx$/,
      /^src\/views\/docs-vault\/model\/[^/]+\.tsx?$/,
      /^src\/widgets\/app-settings-menu\/ui\/AppSettingsMenu(?:\.test)?\.tsx$/,
      /^\.github\/workflows\/deploy-pages\.yml$/,
      /^src-tauri\//,
      /^package\.json$/,
      /^next\.config\.ts$/,
    ],
  },
];

export const directTests = {
  script: [
    ['scripts/build-brand-assets.mjs', 'scripts/build-brand-raster.test.mjs'],
    ['scripts/build-brand-raster.mjs', 'scripts/build-brand-raster.test.mjs'],
    ['scripts/brand-raster-page.html', 'scripts/build-brand-raster.test.mjs'],
    ['scripts/build-traveler-sprites.mjs', 'scripts/build-brand-raster.test.mjs'],
    ['scripts/check-desktop-readiness.mjs', 'scripts/check-desktop-readiness.test.mjs'],
    ['scripts/check-desktop-readiness.test.mjs', 'scripts/check-desktop-readiness.test.mjs'],
    ['scripts/desktop-doctor.mjs', 'scripts/desktop-doctor.test.mjs'],
    ['scripts/desktop-doctor.test.mjs', 'scripts/desktop-doctor.test.mjs'],
    ['scripts/desktop-smoke.mjs', 'scripts/desktop-smoke.test.mjs'],
    ['scripts/desktop-smoke.test.mjs', 'scripts/desktop-smoke.test.mjs'],
    ['scripts/lib/macos-dmg-layout.mjs', 'scripts/lib/macos-dmg-layout.test.mjs'],
    ['scripts/lib/macos-dmg-layout.test.mjs', 'scripts/lib/macos-dmg-layout.test.mjs'],
    ['scripts/lib/redact-command.mjs', 'scripts/lib/redact-command.test.mjs'],
    ['scripts/lib/redact-command.test.mjs', 'scripts/lib/redact-command.test.mjs'],
  ],
};
