/** Authored documentation: the static docs vault, Markdown language and links, living-document metadata, and rendered doc copy. */

export const rules = [
  {
    order: 140,
    command: 'pnpm docs-vault:build',
    reason: 'static docs-vault input or generated output changed',
    // Every build input and every generated output (bug sweep 2026-09-01): the
    // storefront sample is a build input, and a hand edit to any generated
    // file — content.json, headings, gateway-*, sample-storefront.*, the
    // public copies — is exactly what the check exists to flag. The old list
    // covered only docs/**.md and manifest.json, so those edits got a green
    // advisor run before the pre-commit hook's broader grep caught them.
    matches: [
      /^docs\/.+\.md$/,
      /^docs\/records\/.+\.json$/,
      /^samples\/storefront\/.+\.md$/,
      /^src\/entities\/docs-vault\/data\//,
      /^public\/docs-vault\//,
    ],
  },
  {
    order: 160,
    command: 'pnpm exec vitest run tests/contract/bundled-vault-budget.contract.test.ts',
    reason: 'authored bundled-vault inputs changed — measure generated bytes without a Next build',
    matches: [/^docs\/.+\.(?:md|json)$/, /^samples\/storefront\/.+\.md$/],
  },
  {
    order: 170,
    command: 'pnpm test:docs-vault',
    reason: 'docs-vault build/check, conflict-recovery helper, or a file the worktree-materialization test copies changed',
    // The materialization test copies a hand-picked file set into a scratch repository, so a new
    // import in any of those files breaks it without touching the test (lesson on new-record.mjs
    // importing lessons.mjs, 2026-09-26).
    matches: [
      /^scripts\/(?:build-docs-vault|build-messages|resolve-docs-vault-conflicts|prepare-worktree|new-record|lessons|worktree-materialization)\.(?:mjs|test\.mjs)$/,
      /^\.githooks\/post-(?:checkout|merge)$/,
      /^scripts\/lib\/(?:record-ledgers|po-pilot-records|parse-frontmatter)\.(?:mjs|test\.mjs)$/,
    ],
  },
  {
    order: 180,
    command: 'pnpm docs:language',
    reason: 'authored Markdown must not add unexplained Korean prose',
    matches: [/\.md$/, /^scripts\/quality\/markdown-language\//],
  },
  {
    order: 190,
    command: 'pnpm test:docs:language',
    reason: 'Markdown language inventory or ratchet implementation changed',
    matches: [/^scripts\/quality\/markdown-language\//],
  },
  {
    order: 220,
    // The accident this net actually catches is "a document moved or the vault was
    // regenerated but the prose citing it stayed", which only happens in a PR that
    // touched markdown — so markdown is also the trigger for the suggestion.
    command: 'pnpm docs:links',
    reason: 'markdown moved or edited — cited paths and links may have gone stale',
    matches: [/\.md$/],
  },
  {
    order: 230,
    // Living documents carry their kind, status and area; a new or edited one,
    // a template, the kind table or the move map can each break that.
    command: 'pnpm docs:meta && pnpm docs:move -- --check',
    reason: 'a living document, template, document kind or move changed — metadata and moved paths must stay current',
    matches: [/^docs\/(?!ontology\/|records\/(?!README)|archive\/|audits\/|benchmark\/|prototypes\/|(?:DECISIONS|CHANGELOG|PO-PILOT)\.md$|BACKLOG-SNAPSHOT-).+\.md$/, /^docs\/\.moved\.json$/, /^scripts\/lib\/doc-types\.mjs$/],
  },
  {
    order: 240,
    command: 'pnpm test:guide-examples',
    reason: 'public guide ontology examples and the external judgment probe must satisfy their contracts',
    matches: [
      /^docs\/guide\/[^/]+\.md$/,
      /^examples\/external-judgment\//,
      /^scripts\/check-guide-frontmatter-examples\.test\.mjs$/,
    ],
  },
  {
    order: 250,
    command: 'pnpm docs:surface:check',
    reason: 'MCP tool registry, CLI command registry, or their READMEs changed',
    matches: [
      /^mcp\/src\/index\.js$/,
      /^cli\/src\/lib\/cli-commands\.mjs$/,
      /^mcp\/README\.md$/,
      /^cli\/README\.md$/,
      /^docs\/\.generated\/mcp-surface\.json$/,
    ],
  },
  {
    order: 260,
    command: 'pnpm test:docs:checks',
    reason: 'docs surface, doc-link, doc-metadata or doc-move tooling changed',
    matches: [
      /^scripts\/build-docs-surface\.(?:mjs|test\.mjs)$/,
      /^scripts\/check-doc-links\.(?:mjs|test\.mjs)$/,
      /^scripts\/(?:check-doc-meta|docs-move|new-doc|doc-history)\.(?:mjs|test\.mjs)$/,
      /^scripts\/lib\/(?:docs-surface|doc-links|doc-types)\.mjs$/,
    ],
  },
  {
    order: 270,
    command: 'pnpm test:mcp:docs',
    reason: 'GitHub workflow or community template changed',
    matches: [
      /^\.github\/workflows\/release-macos\.yml$/,
      /^\.github\/PULL_REQUEST_TEMPLATE\.md$/,
      /^\.github\/DISCUSSIONS-CATEGORIES\.md$/,
      /^\.github\/ISSUE_TEMPLATE\/[^/]+\.yml$/,
    ],
  },
  {
    order: 1300,
    command: 'pnpm test:mcp:docs',
    reason: 'public docs or dogfood ontology docs changed',
    matches: [
      /^README\.md$/,
      /^AGENTS\.md$/,
      /^CLAUDE\.md$/,
      /^docs\/DEVELOPMENT-CHECKS\.md$/,
      /^docs\/CHANGELOG\.md$/,
      /^docs\/ontology\//,
      /^mcp\/README\.md$/,
      /^cli\/README\.md$/,
      /^scripts\/check-package-contracts\.test\.mjs$/,
    ],
  },
  {
    order: 1330,
    /*
     * **Vault markdown is drawn on screen.** `/docs` renders this folder as is, and so
     * do `samples/storefront` and `docs/guide`. So the prose written here is **product
     * copy**, not code, and it is within reach of the copy gate (no em dashes).
     *
     * ⚠️ Without this rule it was actually breached (2026-08-21): two vault nodes were
     * written with em dashes in the prose, `vault:validate` only looks at frontmatter
     * integrity so it passed, and the pre-push hook passed it too. It went red only
     * **after CI's Unit · Contract job had run for 7 minutes**. The integrity check and
     * the copy check **measure different things**, so neither substitutes for the
     * other.
     */
    command: 'pnpm test:run tests/contract/em-dash-ratchet.contract.test.ts',
    reason: 'rendered doc markdown changed (vault, guide, sample)',
    matches: [
      /^docs\/ontology\/.*\.md$/,
      /^docs\/guide\/.*\.md$/,
      /^docs\/CHANGELOG\.md$/,
      /^samples\/storefront\/.*\.md$/,
    ],
  },
];

export const directTests = {
  script: [
    ['scripts/build-docs-vault.mjs', 'scripts/build-docs-vault.test.mjs'],
    ['scripts/build-docs-vault.test.mjs', 'scripts/build-docs-vault.test.mjs'],
    ['scripts/resolve-docs-vault-conflicts.mjs', 'scripts/resolve-docs-vault-conflicts.test.mjs'],
    ['scripts/resolve-docs-vault-conflicts.test.mjs', 'scripts/resolve-docs-vault-conflicts.test.mjs'],
  ],
};
