/** Dogfood, benchmark, performance, and smoke scripts, and the package-script reference check. */

export const rules = [
  {
    order: 530,
    command: 'pnpm test:dogfood:script-refs',
    reason: 'help text, package-script references, or focused wrapper behavior changed',
    matches: [
      /^package\.json$/,
      /^scripts\/lib\/pnpm-script-refs\.(?:mjs|test\.mjs)$/,
      /^scripts\/lib\/test-name-pattern\.(?:mjs|test\.mjs)$/,
      /^scripts\/lib\/check-mcp-source-dependencies\.(?:mjs|test\.mjs)$/,
      /^scripts\/run-focused-node-test\.(?:mjs|test\.mjs)$/,
      /^scripts\/dogfood-mcp-walk\.(?:mjs|test\.mjs)$/,
      /^cli\/src\/commands\/mcp-verify\.mjs$/,
      /^mcp\/scripts\/verify\.mjs$/,
      /^README\.md$/,
      /^docs\/DEVELOPMENT-CHECKS\.md$/,
      /^docs\/benchmark\/README\.md$/,
      /^mcp\/README\.md$/,
      /^cli\/README\.md$/,
      /^scripts\/migrations\/README\.md$/,
      /^\.agents\/skills\/[^/]+\/SKILL\.md$/,
      /^\.claude\/rules\/[^/]+\.md$/,
      /^\.claude\/skills\/[^/]+\/SKILL\.md$/,
    ],
  },
  {
    order: 620,
    command: 'pnpm test:dogfood:args',
    reason: 'dogfood shortcut argument helper changed',
    matches: [/^scripts\/lib\/dogfood-args\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 630,
    command: 'pnpm test:dogfood:compile-fix',
    reason: 'dogfood compile-fix idempotence helper changed',
    matches: [/^scripts\/dogfood-compile-fix\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 860,
    command: 'pnpm test:dogfood:status',
    reason: 'dogfood status shortcut changed',
    matches: [/^scripts\/dogfood-status\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 870,
    command: 'pnpm test:dogfood:graph-db',
    reason: 'dogfood graph DB pack gate changed',
    matches: [/^scripts\/dogfood-graph-db-pack\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 880,
    command: 'pnpm benchmark --dry-run',
    reason: 'Codex benchmark runner config changed',
    matches: [/^scripts\/benchmark\.mjs$/],
  },
  {
    order: 890,
    command: 'pnpm benchmark:change-flow --dry-run',
    reason: 'end-to-end meaning-to-change benchmark runner config changed',
    matches: [/^scripts\/benchmark-change-flow(?:\.test)?\.mjs$/],
  },
  {
    order: 900,
    command: 'pnpm benchmark:scale --dry-run',
    reason: 'Codex scale benchmark runner config changed',
    matches: [/^scripts\/benchmark-scale\.mjs$/],
  },
  {
    order: 910,
    command: 'node scripts/perf-vault.mjs 10',
    reason: 'vault parser perf smoke changed',
    matches: [/^scripts\/perf-vault\.mjs$/],
  },
  {
    order: 920,
    command: 'node --test scripts/perf-graph.test.mjs',
    reason: 'graph compiler/query perf audit helper contract changed',
    matches: [/^scripts\/perf-graph\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 930,
    command: 'pnpm perf:graph:check',
    reason: 'graph compiler/query perf budget changed',
    matches: [/^scripts\/perf-graph\.mjs$/],
  },
  {
    order: 940,
    command: 'pnpm perf:graph:scale',
    reason: 'graph compiler/query scale budget changed',
    matches: [/^scripts\/perf-graph\.mjs$/],
  },
  {
    order: 950,
    command: 'pnpm smoke:onboarding',
    reason: 'clean onboarding smoke changed',
    matches: [/^scripts\/smoke-clean-onboarding\.mjs$/],
  },
  {
    order: 960,
    command: 'pnpm smoke:memory-loop',
    reason: 'fresh repo memory loop smoke changed',
    matches: [/^scripts\/smoke-memory-loop\.mjs$/],
  },
  {
    order: 1070,
    command: 'pnpm test:mcp:dogfood:timeout',
    reason: 'MCP dogfood timeout/argument diagnostics changed',
    matches: [/^scripts\/dogfood-mcp-walk\.(?:mjs|test\.mjs)$/],
  },
  {
    order: 1080,
    command: 'pnpm test:mcp:dogfood',
    reason: 'MCP dogfood helper changed',
    matches: [/^scripts\/dogfood-mcp-walk\.(?:mjs|test\.mjs)$/],
  },
];

export const directTests = {
  script: [
    ['scripts/lib/check-mcp-source-dependencies.mjs', 'scripts/lib/check-mcp-source-dependencies.test.mjs'],
    ['scripts/lib/check-mcp-source-dependencies.test.mjs', 'scripts/lib/check-mcp-source-dependencies.test.mjs'],
    ['scripts/dogfood-compile-fix.mjs', 'scripts/dogfood-compile-fix.test.mjs'],
    ['scripts/dogfood-compile-fix.test.mjs', 'scripts/dogfood-compile-fix.test.mjs'],
    ['scripts/dogfood-mcp-walk.mjs', 'scripts/dogfood-mcp-walk.test.mjs'],
    ['scripts/dogfood-mcp-walk.test.mjs', 'scripts/dogfood-mcp-walk.test.mjs'],
    ['scripts/dogfood-status.mjs', 'scripts/dogfood-status.test.mjs'],
    ['scripts/dogfood-status.test.mjs', 'scripts/dogfood-status.test.mjs'],
    ['scripts/dogfood-graph-db-pack.mjs', 'scripts/dogfood-graph-db-pack.test.mjs'],
    ['scripts/dogfood-graph-db-pack.test.mjs', 'scripts/dogfood-graph-db-pack.test.mjs'],
    ['scripts/run-focused-node-test.mjs', 'scripts/run-focused-node-test.test.mjs'],
    ['scripts/run-focused-node-test.test.mjs', 'scripts/run-focused-node-test.test.mjs'],
    ['scripts/lib/dogfood-args.mjs', 'scripts/lib/dogfood-args.test.mjs'],
    ['scripts/lib/dogfood-args.test.mjs', 'scripts/lib/dogfood-args.test.mjs'],
    ['scripts/lib/pnpm-script-refs.mjs', 'scripts/lib/pnpm-script-refs.test.mjs'],
    ['scripts/lib/test-name-pattern.mjs', 'scripts/lib/test-name-pattern.test.mjs'],
  ],
};
