#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

export const DESKTOP_SMOKE_LOCALES = ["en", "ko"];
export const DESKTOP_SMOKE_ROUTES = [
  "/download",
  "/docs",
  "/ontology",
  "/topology",
  "/ontology/edit",
  "/ontology/insights",
];
export const DESKTOP_SMOKE_ROOT_ENTRY = "index.html";
/**
 * 번들에 볼트가 실렸는지 보는 두 표본.
 *
 * [개정 2026-08-01] 두 번째 항목은 `ontology/capabilities/desktop-app-distribution.md`
 * 였는데, 볼트를 규격 기준으로 다시 지으면서 그 파일이 사라졌다. 이 검사의
 * 목적은 「특정 개념이 있는가」가 아니라 「**볼트 디렉터리가 통째로 번들에
 * 복사됐는가**」이므로, 표본은 **어떤 볼트에도 있는 파일**이어야 한다.
 * `ontology/README.md` 는 `kind: vault-readme` 로 생성기가 항상 만든다.
 */
export const DESKTOP_SMOKE_DOCS = [
  "docs-vault/DESKTOP-MACOS.md",
  "docs-vault/ontology/README.md",
];

/**
 * Metadata generated by the current route entrypoints.
 *
 * `/ontology/edit` intentionally has no entry of its own: it is a compatibility
 * redirect to the workshop and inherits the app title for the few milliseconds
 * before navigation. Its destination is proved through the chunk contract.
 */
export const DESKTOP_SMOKE_ROUTE_TITLES = {
  "en:/download": "Download · Ontology Atlas",
  "ko:/download": "다운로드 · Ontology Atlas",
  "en:/docs": "Ontology workspace · Ontology Atlas",
  "ko:/docs": "저장소 · Ontology Atlas",
  "en:/ontology": "Ontology · Ontology Atlas",
  "ko:/ontology": "온톨로지 · Ontology Atlas",
  "en:/topology": "Relief · Ontology Atlas",
  "ko:/topology": "지형도 · Ontology Atlas",
  "en:/ontology/insights": "Graph Insights · Ontology Atlas",
  "ko:/ontology/insights": "그래프 인사이트 · Ontology Atlas",
};

/**
 * Server-rendered copy is required only where it is itself the static product
 * surface. Client workbenches are covered by route-specific component markers
 * below instead of brittle historical prose.
 *
 * 문구를 **여기 적어 두지 않는다 — 메시지 카탈로그에서 읽는다.**
 *
 * 예전에는 네 문장을 이 파일에 그대로 박아 뒀다. 그러다 #730 이 다운로드
 * 화면을 다시 만들면서 그 문장들을 걷어냈고, 이 게이트는 **어제의 문장**을
 * 요구한 채로 남았다. `scripts/desktop-smoke.test.mjs` 는 상수가 자기
 * 리터럴과 같은지만 봤으므로 249개 테스트가 전부 초록인 채였고, 결함은
 * `pnpm build` 뒤에 `desktop:smoke` 를 실제로 돌리는 곳 —
 * 즉 **태그를 찍은 뒤의 릴리스 빌드** — 에서만 드러났다.
 * (`desktop:check` 가 같은 이유로 v1.0.0-rc.2 1차 시도를 막았다. #743.)
 *
 * 키만 못박으면 그 종류의 부패가 불가능해진다. 문구가 바뀌면 카탈로그와 함께
 * 바뀌고, 키가 사라지면 아래 `resolveRouteText` 가 즉시 멈춘다. 게이트가
 * 지켜야 하는 것은 "어제의 문장" 이 아니라 **"오늘의 화면이 실제로 정적
 * 출력에 들어갔는가"** 다.
 */
export const DESKTOP_SMOKE_ROUTE_TEXT_KEYS = {
  // `download.title` 은 2026-07-29 관문 재설계에서 사라졌다 — 히어로가
  // `eyebrow` + `stageTitle` 두 줄로 갈렸고, 후자는 줄바꿈을 품어 렌더 텍스트와
  // 원문이 다르므로 키로 고르지 않는다(위 독블록의 ICU 규칙과 같은 이유).
  // `eyebrow` 는 한 줄이고 플랫폼과 제품 성격을 함께 말해서 이 자리에 맞다.
  "/download": [
    "download.eyebrow",
    "download.trustHeading",
    "download.archHelpTitle",
    "download.webCta",
  ],
};

function messageAtPath(messages, dottedKey) {
  return dottedKey
    .split(".")
    .reduce((node, part) => (node && typeof node === "object" ? node[part] : undefined), messages);
}

/**
 * 카탈로그를 읽어 `"<locale>:<route>"` → 기대 문구 배열로 편다.
 *
 * ICU 플레이스홀더(`{tag}`)가 든 문구는 렌더 결과가 원문과 다르므로 키로
 * 고르지 않는다 — 고르면 여기서 멈춘다.
 */
export function resolveRouteText({
  root = process.cwd(),
  locales = DESKTOP_SMOKE_LOCALES,
  keysByRoute = DESKTOP_SMOKE_ROUTE_TEXT_KEYS,
} = {}) {
  const resolved = {};
  for (const locale of locales) {
    const catalogPath = path.join(root, "messages", `${locale}.json`);
    const messages = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
    for (const [route, keys] of Object.entries(keysByRoute)) {
      resolved[`${locale}:${route}`] = keys.map((key) => {
        const value = messageAtPath(messages, key);
        if (typeof value !== "string" || value.length === 0) {
          throw new Error(
            `desktop smoke copy contract points at ${locale} message "${key}", which no longer exists. ` +
              "Point DESKTOP_SMOKE_ROUTE_TEXT_KEYS at a message the route still renders.",
          );
        }
        if (/[{}]/.test(value)) {
          throw new Error(
            `desktop smoke copy contract picked ${locale} message "${key}", which carries an ICU placeholder ` +
              `(${value}). The rendered HTML never contains the raw string — pick a placeholder-free message.`,
          );
        }
        return value;
      });
    }
  }
  return resolved;
}

/**
 * Stable source markers that state what each packaged route means today.
 *
 * These are not a substitute for the installed-app WebView verifier. They
 * prove that the static export packaged the live route implementation instead
 * of a retired browse, builder, or query-cockpit chunk.
 */
export const DESKTOP_SMOKE_ROUTE_CHUNK_TEXT = {
  // 구 fact-strip 마커는 #730 의 리메이크에서 사라졌다. 그 자리에 오늘 실제로
  // 렌더되는 신뢰 섹션 마커를 둔다 — 마커는 "이 라우트가 오늘 무엇인가" 를
  // 말해야지, 어제 무엇이었는지를 말하면 안 된다. (은퇴한 마커 이름을 여기
  // 적지 않는다: 계약 테스트가 이 파일을 문자열로 읽으므로, 설명으로 적어도
  // "아직 남아 있다" 로 잡힌다 — 문자열 게이트는 자기 문서까지 읽는다.)
  "/download": [
    "download-trust",
    "download-platform-macos",
    "download-platform-windows",
  ],
  "/docs": [
    "data-docs-header-zone",
    "data-docs-viewer",
    "sourceContract.filesLabel",
    "sourceContract.graphLabel",
    "sourceContract.agentLabel",
  ],
  "/ontology": ["/topology/?", "index", "expanded"],
  "/topology": ["topology-map-v2-canvas", "topology-concept-search"],
  "/ontology/edit": ["/ontology/studio/?node=", "/ontology/studio/"],
  "/ontology/insights": [
    "maintenance-board",
    "one-tab-one-question",
    "tab-query",
  ],
};

function routeIndexPath({ locale, route }) {
  const cleanRoute = route.replace(/^\/+|\/+$/g, "");
  return path.join(locale, cleanRoute, "index.html");
}

function existsUnder(root, relativePath) {
  return fs.existsSync(path.join(root, relativePath));
}

function readTextUnder(root, relativePath) {
  const filePath = path.join(root, relativePath);
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, "utf8");
}

function hasTitle(html, title) {
  return html.includes(`<title>${title}</title>`);
}

function hasAllText(text, fragments) {
  return fragments.every((fragment) => text.includes(fragment));
}

function scriptChunkPathsFromHtml(html) {
  return Array.from(
    html.matchAll(/\bsrc=["']([^"']*_next\/static\/chunks\/[^"']+\.js)["']/g),
  )
    .map((match) => match[1].replace(/^\//, ""))
    .filter((value, index, array) => array.indexOf(value) === index);
}

function readRouteChunkText(outDir, html) {
  return scriptChunkPathsFromHtml(html)
    .map((chunkPath) => readTextUnder(outDir, chunkPath) ?? "")
    .join("\n");
}

function isMissingBuildArtifact(check) {
  return (
    check.id === "out-dir" ||
    check.id === "_next" ||
    check.id === "root-entry" ||
    check.id.startsWith("route:") ||
    check.id.startsWith("doc:")
  );
}

export function evaluateDesktopSmoke({
  outDir = path.join(process.cwd(), "out"),
  locales = DESKTOP_SMOKE_LOCALES,
  routes = DESKTOP_SMOKE_ROUTES,
  docs = DESKTOP_SMOKE_DOCS,
  routeTitles = DESKTOP_SMOKE_ROUTE_TITLES,
  routeText,
  routeChunkText = {},
} = {}) {
  const expectedRouteText = routeText ?? resolveRouteText();
  const checks = [];
  const addCheck = (id, label, ok, details = "") => {
    checks.push({ id, label, ok, details });
  };

  addCheck("out-dir", "Next.js static export exists", fs.existsSync(outDir), outDir);
  addCheck("_next", "packaged app assets exist", existsUnder(outDir, "_next"), "_next");
  addCheck(
    "root-entry",
    "Tauri app root entry exists",
    existsUnder(outDir, DESKTOP_SMOKE_ROOT_ENTRY),
    DESKTOP_SMOKE_ROOT_ENTRY,
  );

  for (const locale of locales) {
    for (const route of routes) {
      const relativePath = routeIndexPath({ locale, route });
      const exists = existsUnder(outDir, relativePath);
      const html = exists ? readTextUnder(outDir, relativePath) : null;
      addCheck(
        `route:${locale}:${route}`,
        `${locale}${route} static route exists`,
        exists,
        relativePath,
      );

      const expectedTitle = routeTitles[`${locale}:${route}`];
      if (expectedTitle) {
        addCheck(
          `route-title:${locale}:${route}`,
          `${locale}${route} static route title matches`,
          typeof html === "string" && hasTitle(html, expectedTitle),
          expectedTitle,
        );
      }

      const expectedText =
        expectedRouteText[`${locale}:${route}`] ?? expectedRouteText[route];
      if (expectedText) {
        addCheck(
          `route-text:${locale}:${route}`,
          `${locale}${route} current static handoff copy is bundled`,
          typeof html === "string" && hasAllText(html, expectedText),
          expectedText.join(", "),
        );
      }

      const expectedChunkText =
        routeChunkText[`${locale}:${route}`] ?? routeChunkText[route];
      if (expectedChunkText) {
        const chunkText =
          typeof html === "string" ? readRouteChunkText(outDir, html) : "";
        addCheck(
          `route-chunk-text:${locale}:${route}`,
          `${locale}${route} current component contract is bundled`,
          typeof html === "string" && hasAllText(chunkText, expectedChunkText),
          expectedChunkText.join(", "),
        );
      }
    }
  }

  for (const doc of docs) {
    addCheck(
      `doc:${doc}`,
      `${doc} is bundled for offline docs`,
      existsUnder(outDir, doc),
      doc,
    );
  }

  const missing = checks.filter((check) => !check.ok);
  const missingBuildArtifact = missing.some(isMissingBuildArtifact);
  return {
    ok: missing.length === 0,
    checks,
    missing,
    blockerKind:
      missing.length === 0
        ? null
        : missingBuildArtifact
          ? "missing-build-artifact"
          : "static-contract-drift",
    nextAction:
      missing.length === 0
        ? "Run pnpm desktop:dev or pnpm desktop:build, then smoke the same routes inside the .app shell."
        : missingBuildArtifact
          ? "Run pnpm build before pnpm desktop:smoke so out/ contains every current static desktop artifact."
          : "Static contract drift: compare the failing title, copy, or component marker with the current route source; update the product or this smoke contract, then rebuild once.",
  };
}

function renderDesktopSmoke(report) {
  const lines = ["[desktop-smoke] packaged static route smoke"];
  for (const check of report.checks) {
    lines.push(
      `${check.ok ? "✓" : "✗"} ${check.label}${check.details ? ` (${check.details})` : ""}`,
    );
  }
  lines.push(`[desktop-smoke] ${report.ok ? "ready" : "blocked"}: ${report.nextAction}`);
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const report = evaluateDesktopSmoke({
    routeChunkText: DESKTOP_SMOKE_ROUTE_CHUNK_TEXT,
  });
  console.log(renderDesktopSmoke(report));
  if (!report.ok) process.exitCode = 1;
}
