#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

export const DESKTOP_SMOKE_LOCALES = ["en", "ko"];
export const DESKTOP_SMOKE_ROUTES = [
  "/download",
  "/docs",
  "/ontology",
  "/topology",
  "/ontology/edit",
  "/ontology/insights",
];
export const DESKTOP_SMOKE_ROOT_ENTRY = "index.html";
export const DESKTOP_SMOKE_DOCS = [
  "docs-vault/DESKTOP-MACOS.md",
  "docs-vault/ontology/capabilities/desktop-app-distribution.md",
];

/**
 * Metadata generated by the current route entrypoints.
 *
 * `/ontology/edit` intentionally has no entry of its own: it is a compatibility
 * redirect to the workshop and inherits the app title for the few milliseconds
 * before navigation. Its destination is proved through the chunk contract.
 */
export const DESKTOP_SMOKE_ROUTE_TITLES = {
  "en:/download": "Download · Ontology Atlas",
  "ko:/download": "다운로드 · Ontology Atlas",
  "en:/docs": "Ontology workspace · Ontology Atlas",
  "ko:/docs": "저장소 · Ontology Atlas",
  "en:/ontology": "Ontology · Ontology Atlas",
  "ko:/ontology": "온톨로지 · Ontology Atlas",
  "en:/topology": "Relief · Ontology Atlas",
  "ko:/topology": "지형도 · Ontology Atlas",
  "en:/ontology/insights": "Graph Insights · Ontology Atlas",
  "ko:/ontology/insights": "그래프 인사이트 · Ontology Atlas",
};

/**
 * Server-rendered copy is required only where it is itself the static product
 * surface. Client workbenches are covered by route-specific component markers
 * below instead of brittle historical prose.
 */
export const DESKTOP_SMOKE_ROUTE_TEXT = {
  "en:/download": [
    "Install once. Work from your local vault.",
    "Pick your vault folder",
    "Connect your AI assistant",
    "MCP server auto-registration",
  ],
  "ko:/download": [
    "한 번 설치하고, 내 로컬 vault 에서 작업하세요.",
    "vault 폴더 선택",
    "AI 어시스턴트 연결하기",
    "MCP 서버 자동등록",
  ],
};

/**
 * Stable source markers that state what each packaged route means today.
 *
 * These are not a substitute for the installed-app WebView verifier. They
 * prove that the static export packaged the live route implementation instead
 * of a retired browse, builder, or query-cockpit chunk.
 */
export const DESKTOP_SMOKE_ROUTE_CHUNK_TEXT = {
  "/download": [
    "download-fact-strip",
    "download-platform-macos",
    "download-platform-windows",
  ],
  "/docs": [
    "data-docs-header-zone",
    "data-docs-viewer",
    "sourceContract.filesLabel",
    "sourceContract.graphLabel",
    "sourceContract.agentLabel",
  ],
  "/ontology": ["/topology/?", "index", "expanded"],
  "/topology": ["canvas-v2", "active-relation-inspector", "focus-path-state"],
  "/ontology/edit": ["/ontology/studio/?node=", "/ontology/studio/"],
  "/ontology/insights": [
    "maintenance-board",
    "one-tab-one-question",
    "tab-query",
  ],
};

function routeIndexPath({ locale, route }) {
  const cleanRoute = route.replace(/^\/+|\/+$/g, "");
  return path.join(locale, cleanRoute, "index.html");
}

function existsUnder(root, relativePath) {
  return fs.existsSync(path.join(root, relativePath));
}

function readTextUnder(root, relativePath) {
  const filePath = path.join(root, relativePath);
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, "utf8");
}

function hasTitle(html, title) {
  return html.includes(`<title>${title}</title>`);
}

function hasAllText(text, fragments) {
  return fragments.every((fragment) => text.includes(fragment));
}

function scriptChunkPathsFromHtml(html) {
  return Array.from(
    html.matchAll(/\bsrc=["']([^"']*_next\/static\/chunks\/[^"']+\.js)["']/g),
  )
    .map((match) => match[1].replace(/^\//, ""))
    .filter((value, index, array) => array.indexOf(value) === index);
}

function readRouteChunkText(outDir, html) {
  return scriptChunkPathsFromHtml(html)
    .map((chunkPath) => readTextUnder(outDir, chunkPath) ?? "")
    .join("\n");
}

function isMissingBuildArtifact(check) {
  return (
    check.id === "out-dir" ||
    check.id === "_next" ||
    check.id === "root-entry" ||
    check.id.startsWith("route:") ||
    check.id.startsWith("doc:")
  );
}

export function evaluateDesktopSmoke({
  outDir = path.join(process.cwd(), "out"),
  locales = DESKTOP_SMOKE_LOCALES,
  routes = DESKTOP_SMOKE_ROUTES,
  docs = DESKTOP_SMOKE_DOCS,
  routeTitles = DESKTOP_SMOKE_ROUTE_TITLES,
  routeText = DESKTOP_SMOKE_ROUTE_TEXT,
  routeChunkText = {},
} = {}) {
  const checks = [];
  const addCheck = (id, label, ok, details = "") => {
    checks.push({ id, label, ok, details });
  };

  addCheck("out-dir", "Next.js static export exists", fs.existsSync(outDir), outDir);
  addCheck("_next", "packaged app assets exist", existsUnder(outDir, "_next"), "_next");
  addCheck(
    "root-entry",
    "Tauri app root entry exists",
    existsUnder(outDir, DESKTOP_SMOKE_ROOT_ENTRY),
    DESKTOP_SMOKE_ROOT_ENTRY,
  );

  for (const locale of locales) {
    for (const route of routes) {
      const relativePath = routeIndexPath({ locale, route });
      const exists = existsUnder(outDir, relativePath);
      const html = exists ? readTextUnder(outDir, relativePath) : null;
      addCheck(
        `route:${locale}:${route}`,
        `${locale}${route} static route exists`,
        exists,
        relativePath,
      );

      const expectedTitle = routeTitles[`${locale}:${route}`];
      if (expectedTitle) {
        addCheck(
          `route-title:${locale}:${route}`,
          `${locale}${route} static route title matches`,
          typeof html === "string" && hasTitle(html, expectedTitle),
          expectedTitle,
        );
      }

      const expectedText = routeText[`${locale}:${route}`] ?? routeText[route];
      if (expectedText) {
        addCheck(
          `route-text:${locale}:${route}`,
          `${locale}${route} current static handoff copy is bundled`,
          typeof html === "string" && hasAllText(html, expectedText),
          expectedText.join(", "),
        );
      }

      const expectedChunkText =
        routeChunkText[`${locale}:${route}`] ?? routeChunkText[route];
      if (expectedChunkText) {
        const chunkText =
          typeof html === "string" ? readRouteChunkText(outDir, html) : "";
        addCheck(
          `route-chunk-text:${locale}:${route}`,
          `${locale}${route} current component contract is bundled`,
          typeof html === "string" && hasAllText(chunkText, expectedChunkText),
          expectedChunkText.join(", "),
        );
      }
    }
  }

  for (const doc of docs) {
    addCheck(
      `doc:${doc}`,
      `${doc} is bundled for offline docs`,
      existsUnder(outDir, doc),
      doc,
    );
  }

  const missing = checks.filter((check) => !check.ok);
  const missingBuildArtifact = missing.some(isMissingBuildArtifact);
  return {
    ok: missing.length === 0,
    checks,
    missing,
    blockerKind:
      missing.length === 0
        ? null
        : missingBuildArtifact
          ? "missing-build-artifact"
          : "static-contract-drift",
    nextAction:
      missing.length === 0
        ? "Run pnpm desktop:dev or pnpm desktop:build, then smoke the same routes inside the .app shell."
        : missingBuildArtifact
          ? "Run pnpm build before pnpm desktop:smoke so out/ contains every current static desktop artifact."
          : "Static contract drift: compare the failing title, copy, or component marker with the current route source; update the product or this smoke contract, then rebuild once.",
  };
}

function renderDesktopSmoke(report) {
  const lines = ["[desktop-smoke] packaged static route smoke"];
  for (const check of report.checks) {
    lines.push(
      `${check.ok ? "✓" : "✗"} ${check.label}${check.details ? ` (${check.details})` : ""}`,
    );
  }
  lines.push(`[desktop-smoke] ${report.ok ? "ready" : "blocked"}: ${report.nextAction}`);
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const report = evaluateDesktopSmoke({
    routeChunkText: DESKTOP_SMOKE_ROUTE_CHUNK_TEXT,
  });
  console.log(renderDesktopSmoke(report));
  if (!report.ok) process.exitCode = 1;
}
