#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

export const DESKTOP_SMOKE_LOCALES = ["en", "ko"];
export const DESKTOP_SMOKE_ROUTES = [
  "/download",
  "/docs",
  "/ontology",
  "/topology",
  "/ontology/edit",
  "/ontology/insights",
];
export const DESKTOP_SMOKE_ROOT_ENTRY = "index.html";
/**
 * Two samples proving the vault made it into the bundle.
 *
 * [Revised 2026-08-01] The second entry used to be
 * `ontology/capabilities/desktop-app-distribution.md`, and rebuilding the vault to
 * spec removed that file. This check asks whether **the whole vault directory was
 * copied into the bundle**, not whether a particular concept exists, so the samples
 * must be **files present in any vault**. `ontology/README.md` is always produced by
 * the generator as `kind: vault-readme`.
 */
export const DESKTOP_SMOKE_DOCS = [
  "docs-vault/DESKTOP-MACOS.md",
  "docs-vault/ontology/README.md",
];

/**
 * Metadata generated by the current route entrypoints.
 *
 * `/ontology/edit` intentionally has no entry of its own: it is a compatibility
 * redirect to the map workbench and inherits the app title for the few milliseconds
 * before navigation. Its destination is proved through the chunk contract.
 */
export const DESKTOP_SMOKE_ROUTE_TITLES = {
  "en:/download": "Download · Ontology Atlas",
  "ko:/download": "다운로드 · Ontology Atlas",
  "en:/docs": "Ontology workspace · Ontology Atlas",
  "ko:/docs": "저장소 · Ontology Atlas",
  "en:/ontology": "Ontology · Ontology Atlas",
  "ko:/ontology": "온톨로지 · Ontology Atlas",
  "en:/topology": "Map · Ontology Atlas",
  "ko:/topology": "지도 · Ontology Atlas",
  "en:/ontology/insights": "Graph Insights · Ontology Atlas",
  "ko:/ontology/insights": "내 폴더 분석 · Ontology Atlas",
};

/**
 * Server-rendered copy is required only where it is itself the static product
 * surface. Client workbenches are covered by route-specific component markers
 * below instead of brittle historical prose.
 *
 * **The copy is not written here — it is read from the message catalogue.**
 *
 * Four sentences used to be pinned into this file verbatim. When #730 rebuilt the
 * download screen those sentences went away, and this gate was left demanding
 * **yesterday's copy**. `scripts/desktop-smoke.test.mjs` only checked the constant
 * against its own literal, so all 249 tests stayed green and the defect surfaced
 * only where `desktop:smoke` actually runs after `pnpm build` — **the release build
 * after the tag was cut**. (`desktop:check` blocked the first attempt at
 * v1.0.0-rc.2 for the same reason, #743.)
 *
 * Pinning keys alone makes that kind of decay impossible: copy changes together
 * with the catalogue, and a deleted key stops `resolveRouteText` below immediately.
 * What the gate must protect is not yesterday's sentence but **whether today's
 * screen actually landed in the static output.**
 */
export const DESKTOP_SMOKE_ROUTE_TEXT_KEYS = {
  // `download.title` disappeared in the 2026-07-29 gateway redesign — the hero split
  // into `eyebrow` + `stageTitle`, and the latter contains a line break so its
  // rendered text differs from the source (the same reason as the ICU rule in the
  // doc-block above). `eyebrow` is one line and names both the platform and the
  // product's character, which suits this slot.
  //
  // 2026-08-19: of the previous key set, two disappeared from the screen when the
  // install section was deleted, and the third rendered **only on the unpublished
  // branch** — all three are strings a published build's static HTML cannot contain.
  // Replaced with three section titles that render in every release state.
  "/download": [
    "download.eyebrow",
    "download.demoTitle",
    "download.evidenceTitle",
    "download.agentsTitle",
  ],
};

function messageAtPath(messages, dottedKey) {
  return dottedKey
    .split(".")
    .reduce((node, part) => (node && typeof node === "object" ? node[part] : undefined), messages);
}

/**
 * Reads the catalogue and expands it into `"<locale>:<route>"` → expected copy.
 *
 * Copy containing an ICU placeholder (`{tag}`) renders differently from its source,
 * so such keys must not be chosen — choosing one stops here.
 */
export function resolveRouteText({
  root = process.cwd(),
  locales = DESKTOP_SMOKE_LOCALES,
  keysByRoute = DESKTOP_SMOKE_ROUTE_TEXT_KEYS,
} = {}) {
  const resolved = {};
  for (const locale of locales) {
    const catalogPath = path.join(root, "messages", `${locale}.json`);
    const messages = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
    for (const [route, keys] of Object.entries(keysByRoute)) {
      resolved[`${locale}:${route}`] = keys.map((key) => {
        const value = messageAtPath(messages, key);
        if (typeof value !== "string" || value.length === 0) {
          throw new Error(
            `desktop smoke copy contract points at ${locale} message "${key}", which no longer exists. ` +
              "Point DESKTOP_SMOKE_ROUTE_TEXT_KEYS at a message the route still renders.",
          );
        }
        if (/[{}]/.test(value)) {
          throw new Error(
            `desktop smoke copy contract picked ${locale} message "${key}", which carries an ICU placeholder ` +
              `(${value}). The rendered HTML never contains the raw string — pick a placeholder-free message.`,
          );
        }
        return value;
      });
    }
  }
  return resolved;
}

/**
 * Stable source markers that state what each packaged route means today.
 *
 * These are not a substitute for the installed-app WebView verifier. They
 * prove that the static export packaged the live route implementation instead
 * of a retired browse, builder, or query-cockpit chunk.
 */
export const DESKTOP_SMOKE_ROUTE_CHUNK_TEXT = {
  // A marker must say what this route is today, not what it used to be. (Retired
  // marker names are not written here: the contract test reads this file as text, so
  // naming one even in prose is caught as "still present" — a text gate reads its own
  // documentation too.) When the install section disappeared on 2026-08-19 the trust
  // section's marker retired with it, and the markers are now the three sections that
  // make up this route today: the hero's download, the demo, and the agent.
  "/download": [
    "gateway-hero-cta",
    "gateway-demo-section",
    "gateway-agents-section",
  ],
  "/docs": [
    "data-docs-header-zone",
    "data-docs-viewer",
    "sourceContract.filesLabel",
    "sourceContract.graphLabel",
    "sourceContract.agentLabel",
  ],
  "/ontology": ["/topology/?", "index", "expanded"],
  "/topology": ["topology-map-v2-canvas", "topology-concept-search"],
  "/ontology/edit": ["/topology/?p=", "/topology/?workbench=create"],
  "/ontology/insights": [
    "maintenance-board",
    "one-tab-one-question",
    "tab-query",
  ],
};

function routeIndexPath({ locale, route }) {
  const cleanRoute = route.replace(/^\/+|\/+$/g, "");
  return path.join(locale, cleanRoute, "index.html");
}

function existsUnder(root, relativePath) {
  return fs.existsSync(path.join(root, relativePath));
}

function readTextUnder(root, relativePath) {
  const filePath = path.join(root, relativePath);
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, "utf8");
}

function hasTitle(html, title) {
  return html.includes(`<title>${title}</title>`);
}

function hasAllText(text, fragments) {
  return fragments.every((fragment) => text.includes(fragment));
}

function scriptChunkPathsFromHtml(html) {
  return Array.from(
    html.matchAll(/\bsrc=["']([^"']*_next\/static\/chunks\/[^"']+\.js)["']/g),
  )
    .map((match) => match[1].replace(/^\//, ""))
    .filter((value, index, array) => array.indexOf(value) === index);
}

function readRouteChunkText(outDir, html) {
  return scriptChunkPathsFromHtml(html)
    .map((chunkPath) => readTextUnder(outDir, chunkPath) ?? "")
    .join("\n");
}

function isMissingBuildArtifact(check) {
  return (
    check.id === "out-dir" ||
    check.id === "_next" ||
    check.id === "root-entry" ||
    check.id.startsWith("route:") ||
    check.id.startsWith("doc:")
  );
}

export function evaluateDesktopSmoke({
  outDir = path.join(process.cwd(), "out"),
  locales = DESKTOP_SMOKE_LOCALES,
  routes = DESKTOP_SMOKE_ROUTES,
  docs = DESKTOP_SMOKE_DOCS,
  routeTitles = DESKTOP_SMOKE_ROUTE_TITLES,
  routeText,
  routeChunkText = {},
} = {}) {
  const expectedRouteText = routeText ?? resolveRouteText();
  const checks = [];
  const addCheck = (id, label, ok, details = "") => {
    checks.push({ id, label, ok, details });
  };

  addCheck("out-dir", "Next.js static export exists", fs.existsSync(outDir), outDir);
  addCheck("_next", "packaged app assets exist", existsUnder(outDir, "_next"), "_next");
  addCheck(
    "root-entry",
    "Tauri app root entry exists",
    existsUnder(outDir, DESKTOP_SMOKE_ROOT_ENTRY),
    DESKTOP_SMOKE_ROOT_ENTRY,
  );

  for (const locale of locales) {
    for (const route of routes) {
      const relativePath = routeIndexPath({ locale, route });
      const exists = existsUnder(outDir, relativePath);
      const html = exists ? readTextUnder(outDir, relativePath) : null;
      addCheck(
        `route:${locale}:${route}`,
        `${locale}${route} static route exists`,
        exists,
        relativePath,
      );

      const expectedTitle = routeTitles[`${locale}:${route}`];
      if (expectedTitle) {
        addCheck(
          `route-title:${locale}:${route}`,
          `${locale}${route} static route title matches`,
          typeof html === "string" && hasTitle(html, expectedTitle),
          expectedTitle,
        );
      }

      const expectedText =
        expectedRouteText[`${locale}:${route}`] ?? expectedRouteText[route];
      if (expectedText) {
        addCheck(
          `route-text:${locale}:${route}`,
          `${locale}${route} current static handoff copy is bundled`,
          typeof html === "string" && hasAllText(html, expectedText),
          expectedText.join(", "),
        );
      }

      const expectedChunkText =
        routeChunkText[`${locale}:${route}`] ?? routeChunkText[route];
      if (expectedChunkText) {
        const chunkText =
          typeof html === "string" ? readRouteChunkText(outDir, html) : "";
        addCheck(
          `route-chunk-text:${locale}:${route}`,
          `${locale}${route} current component contract is bundled`,
          typeof html === "string" && hasAllText(chunkText, expectedChunkText),
          expectedChunkText.join(", "),
        );
      }
    }
  }

  for (const doc of docs) {
    addCheck(
      `doc:${doc}`,
      `${doc} is bundled for offline docs`,
      existsUnder(outDir, doc),
      doc,
    );
  }

  const missing = checks.filter((check) => !check.ok);
  const missingBuildArtifact = missing.some(isMissingBuildArtifact);
  return {
    ok: missing.length === 0,
    checks,
    missing,
    blockerKind:
      missing.length === 0
        ? null
        : missingBuildArtifact
          ? "missing-build-artifact"
          : "static-contract-drift",
    nextAction:
      missing.length === 0
        ? "Run pnpm desktop:dev or pnpm desktop:build, then smoke the same routes inside the .app shell."
        : missingBuildArtifact
          ? "Run pnpm build before pnpm desktop:smoke so out/ contains every current static desktop artifact."
          : "Static contract drift: compare the failing title, copy, or component marker with the current route source; update the product or this smoke contract, then rebuild once.",
  };
}

function renderDesktopSmoke(report) {
  const lines = ["[desktop-smoke] packaged static route smoke"];
  for (const check of report.checks) {
    lines.push(
      `${check.ok ? "✓" : "✗"} ${check.label}${check.details ? ` (${check.details})` : ""}`,
    );
  }
  lines.push(`[desktop-smoke] ${report.ok ? "ready" : "blocked"}: ${report.nextAction}`);
  return lines.join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const report = evaluateDesktopSmoke({
    routeChunkText: DESKTOP_SMOKE_ROUTE_CHUNK_TEXT,
  });
  console.log(renderDesktopSmoke(report));
  if (!report.ok) process.exitCode = 1;
}
