"use client";
import { useTopologyAppearanceEffects } from "./use-topology-appearance-effects";
import { useTopologyFrameLoop } from "./use-topology-frame-loop";
import { useTopologyObserverBindings } from "./use-topology-observer-bindings";
import { useTopologyOverviewNavigation } from "./use-topology-overview-navigation";
import { useTopologyTrailInputs } from "./use-topology-trail-inputs";

import { useTopologyActivityState } from "./use-topology-activity-state";
import { useTopologyCameraState } from "./use-topology-camera-state";
import { useTopologyDomeState } from "./use-topology-dome-state";
import { useTopologyInteractionState } from "./use-topology-interaction-state";
import { useTopologyPresentationState } from "./use-topology-presentation-state";
import { useTopologyRealmState } from "./use-topology-realm-state";
import { useTopologySurfaceState } from "./use-topology-surface-state";
import { useTopologyVisibilityState } from "./use-topology-visibility-state";
import { useTopologyWorldState } from "./use-topology-world-state";

import type { UseTopologyLoopArgs } from "./topology-loop-contract";
export type { UseTopologyLoopArgs } from "./topology-loop-contract";

import { useTopologyCameraNavigation } from "./use-topology-camera-navigation";
import { useTopologyCameraPolicy } from "./use-topology-camera-policy";
import { useTopologyClusterExpansion } from "./use-topology-cluster-expansion";
import { useTopologyDomeTransitions } from "./use-topology-dome-transitions";
import { useTopologyFocusNavigation } from "./use-topology-focus-navigation";
import { useTopologyGalaxyTransition } from "./use-topology-galaxy-transition";
import { useTopologyGrowthReplay } from "./use-topology-growth-replay";
import { useTopologyInput } from "./use-topology-input";
import { useTopologyLayoutCommands } from "./use-topology-layout-commands";
import { useTopologyMotionPreference } from "./use-topology-motion-preference";
import { useTopologyRealmTransition } from "./use-topology-realm-transition";
import { useTopologyWorldLifecycle } from "./use-topology-world-lifecycle";

/** Compose map state owners, lifecycle transitions, input, and the frame pipeline. */

import {
  useCallback,
  useEffect,
  useRef,
  type KeyboardEvent as ReactKeyboardEvent,
  type RefObject
} from "react";

import {
  DEFAULT_EXPAND,
  DEFAULT_MAP_ARRANGEMENT
} from "@/shared/lib/appearance-preferences";
import {
  type DomeViewKind
} from "../model/dome-view";
import { DEFAULT_TIER_REVEAL } from "../model/tier-visibility";
import { type TopologyPointerHandlers } from "./topology-pointer-handlers";

import { useTopologyMapInstrumentation } from "./use-topology-map-instrumentation";
import {
  useTopologyViewportLifecycle
} from "./use-topology-viewport-lifecycle";

const EMPTY_EXPANDED_SET: ReadonlySet<string> = new Set();
const EMPTY_TRAIL: readonly string[] = [];

export type UseTopologyLoopResult = TopologyPointerHandlers & {
  canvasRef: RefObject<HTMLCanvasElement | null>;
  containerRef: RefObject<HTMLDivElement | null>;
  /** Walk to a neighbour with the arrow keys — the canvas's `onKeyDown`. */
  handleKeyDown: (event: ReactKeyboardEvent<HTMLCanvasElement>) => void;
  /** Raise one Strata plane's ring — the tier legend's hover; null clears it. */
  raiseDomeTier: (kind: DomeViewKind | null) => void;
  /** The tier names' rendered widths by kind, as they measured themselves; `{}` places none. */
  setDomeTierNameWidths: (widths: Readonly<Record<string, number>>) => void;
};

export function useTopologyLoop(args: UseTopologyLoopArgs): UseTopologyLoopResult {
  const {
    nodes, edges, focusedSlug, emphasizedNeighborSlug = null, dataSourceKey = null, overviewFit = "spine",
    fitViewToken, growthReplayToken = 0, onGrowthReplayingChange, spotlightFitToken = 0,
    constellationFocusId = null, relayoutToken, revealToken = 0, onSelectEdge, onHoverEdge, onSelect,
    onPaneClick, onVisibleCountChange, onGraphStatsChange, onDrawnCountChange, onDomeTierAnchorsChange,
    onZoomTierChange, onContextMenuNode, onContextMenuPane,
    agentFocusNodeId = null, spotlightIds = null, mapLensKind = "recent", pathEdgeIds = null,
    selectedEdge = null, previewEdge = null, expandedParents = EMPTY_EXPANDED_SET, onToggleCluster,
    onHoverCluster, realmRootId = null, onEnterRealm, realmEnterButtonRef, realmCaption = null,
    visitedTrail = EMPTY_TRAIL, trailLensActiveRef, clusterBarLabels = null,
    trailHoverNodeIdRef, panelHoverNodeIdRef, tierReveal = DEFAULT_TIER_REVEAL, tourAnchorNodeId = null,
    tourAnchorRef, glyphSet = "geometric", canvasBackground = "dot", view3d = false, galaxy = false,
    mapArrangement = DEFAULT_MAP_ARRANGEMENT, detailPanelVisible = false, footprint = null,
    expand = DEFAULT_EXPAND, wheelIntent = "zoom", ambientSleepDelayMs, onWalkDeadEnd = null,
  } = args;
  const {
    getRealmCaption, getClusterBarLabels, realmTransitionRef, realmDataRef, realmActiveHandedOffRef,
    wardingFitRef, prevRealmRootIdRef, realmEnterTargetRef, onEnterRealmRef, realmEnterButtonElRef,
    tourAnchorElRef, realmParallaxDepth2Ref, realmParallaxDepth3Ref, prevCameraCenterRef, realmParallaxRef,
    realmTierKindsRef, realmExpandChainRef, clusterBarLabelsRef,
  } = useTopologyRealmState({
    realmCaption,
    clusterBarLabels,
    onEnterRealm,
  });
  const {
    annotationRef, previewEdgePropRef, previewEdgeHeldRef, previewSignatureRef,
    previewAlphaRef, previewCommitRef, previewTransitionRef, glyphStyleRef, canvasBackgroundRef,
    footprintPrefRef, footprintInkRef, footprintStepColorRef, footprintTrailLenRef, footprintAppearAtRef,
    ambientSleepDelayRef, visitedTrailRef, visitedTrailSetRef, drawnTrailLensRef, trailLensPropRef,
    trailBrushPropRef, panelHoverPropRef, agentFocusNodeIdRef, tourAnchorNodeIdRef, spotlightIdsRef,
    mapLensKindRef, pathEdgeIdsRef, spotlightRampRef, spotlightDashOffsetRef, trailLensRampRef,
    trailLensOpenedAtRef, onZoomTierChangeRef, onDrawnCountChangeRef, drawnNodeCountRef, lastZoomTierRef,
    tierRevealRef,
  } = useTopologyPresentationState({
    args,
    previewEdge,
    glyphSet,
    canvasBackground,
    footprint,
    ambientSleepDelayMs,
    visitedTrail,
    trailLensActiveRef,
    trailHoverNodeIdRef,
    panelHoverNodeIdRef,
    agentFocusNodeId,
    tourAnchorNodeId,
    spotlightIds,
    mapLensKind,
    pathEdgeIds,
    onZoomTierChange,
    onDrawnCountChange,
    tierReveal,
  });
  const {
    canvasRef, containerRef, gridCanvasRef, viewportRef, pendingViewportRef, viewportRebuildPendingRef,
    appliedDprScaleRef, viewportSettleFramesRef, commitViewportSizeRef, rebuildViewportLayersRef,
    dustPointsRef, cosmosPointsRef, gridPatternRef, animatedBgRef, bgPointerRef, depthDotPatternsRef,
    depthDotCanvasRef,
  } = useTopologySurfaceState();
  const {
    worldRef, simRef, heatRef, nodeDragRef, activeTouchesRef, pinchRef, dragAffectedSetRef, dragStartPosRef,
    dragTugOffsetsRef, dragVelRef, dragPrevPosRef, dropSeededRef, hoverStartRef, hoverReleasedRef,
    geomPrevXRef, geomPrevYRef, sepDisplacedIdsRef, homeSpringsRef, homingActiveRef, homeTargetOverrideRef,
    prevPinnedNodeIdRef,
  } = useTopologyWorldState();
  const {
    view3dRef, galaxyRef, galaxyEnteredAtRef, galaxyAtmosphereSeedRef, galaxyLayoutRef,
    galaxyFlatReturnPositionsRef, galaxyLayoutHandoffRef, galaxyModeCameraRef, pendingFlatCameraRef,
    galaxyRampRef, neuralRampRef, mapArrangementRef, domeRuntimeRef, domeWorldSourceRef, domeModelBuildRef,
    domeFocusPendingRef, domeFitPendingRef, domeFitDurationRef, flatFitPendingRef, onDomeTierAnchorsChangeRef,
    domeTierRaisedKindRef, domeTierAnchorsSentRef, domeTierNameWidthsRef,
    domeFitInsetsRef,
  } = useTopologyDomeState({
    view3d,
    galaxy,
    mapArrangement,
    onDomeTierAnchorsChange,
  });
  const {
    lastActiveCausesRef, idleDebugEnabledRef, lastFrameTimeRef, navYieldUntilRef, reducedMotionRef,
    selectionPulseRef, pulsesRef, hasDependsEdgesRef, hasContainsEdgesRef, lastActiveMsRef, lastInputMsRef,
    prevCameraSampleRef,
  } = useTopologyActivityState();
  const {
    expandPrefRef, expandedParentsRef, prevExpandedParentsRef, clusterChipsRef, clusteredIdsRef,
    hoveredClusterIdRef, egoRevealBatchesRef, clusterRevealBatchesRef, batchAppearRef, batchAppearStartRef,
    prevBatchVisibleRef, emphasisRef, egoRevealRef, focusRampRef, chipRevealRef, expandRevealRef, appearRef,
    growthReplayRef, growthReplayAppearRef, growthReplayTokenSeenRef, onGrowthReplayingChangeRef,
    endGrowthReplay, prevNodeIdsRef, bornNodeIdsRef, labelPresentRef, colorFocusRef, rippleStartRef,
  } = useTopologyVisibilityState({
    expand,
    expandedParents,
    growthReplayToken,
    onGrowthReplayingChange,
  });
  const {
    cameraRef, cameraTargetRef, galaxyInspectionCameraRef, constellationCameraRef,
    previousConstellationFocusIdRef, userDrivenCameraRef, cameraGestureRevisionRef, cameraTweenRef,
    dampingRef, cameraAngularFreqRef, overviewScaleRef, hasInitializedRef, fittedDataSourceKeyRef,
    drawnFarTRef, initialFitTokensRef, lastProcessedSpotlightFitTokenRef, pendingSpotlightFitRef,
    runSpotlightFitRef, reframeViewportRef, viewportCameraTrackedRef, initialRelayoutTokenRef, panelInsetsRef,
    overviewFitRef,
  } = useTopologyCameraState({
    constellationFocusId,
    galaxy,
    relayoutToken,
    fitViewToken,
    overviewFit,
  });
  const {
    pointerMachineRef, dragHistoryRef, domeGripRef, camStartAtDownRef, canvasRectRef, focusedSlugRef,
    lastFocusedSlugRef, panelEmphasisNodeIdRef, hoveredNodeIdRef, hoveredEdgeRef, onHoverEdgeRef,
    selectedEdgeRef, drawnHoveredNodeIdRef, focusLeashPxRef, lastTapRef,
  } = useTopologyInteractionState({
    focusedSlug,
    emphasizedNeighborSlug,
    onHoverEdge,
    selectedEdge,
  });
  const { cameraTokens, domeFitTarget, beginCameraTween } = useTopologyCameraPolicy({
    canvasRef,
    panelInsetsRef,
    domeFitInsetsRef,
    reducedMotionRef,
    cameraTweenRef,
    cameraRef,
  });
  useTopologyObserverBindings({
    galaxy,
    galaxyEnteredAtRef,
    galaxyAtmosphereSeedRef,
    onGrowthReplayingChangeRef,
    onGrowthReplayingChange,
    onZoomTierChangeRef,
    onZoomTierChange,
    onDrawnCountChangeRef,
    onDrawnCountChange,
    onDomeTierAnchorsChangeRef,
    onDomeTierAnchorsChange,
    onHoverEdgeRef,
    onHoverEdge,
    onEnterRealmRef,
    onEnterRealm,
    realmEnterButtonElRef,
    realmEnterButtonRef,
    tourAnchorElRef,
    tourAnchorRef,
    trailLensPropRef,
    trailLensActiveRef,
    trailBrushPropRef,
    trailHoverNodeIdRef,
    panelHoverPropRef,
    panelHoverNodeIdRef,
    focusedSlugRef,
    focusedSlug,
    hoveredNodeIdRef,
    hoveredEdgeRef,
    lastActiveMsRef,
    agentFocusNodeIdRef,
    agentFocusNodeId,
    tourAnchorNodeIdRef,
    tourAnchorNodeId,
    spotlightIdsRef,
    spotlightIds,
    mapLensKindRef,
    mapLensKind,
    pathEdgeIdsRef,
    pathEdgeIds,
    glyphStyleRef,
    glyphSet,
  });
  useTopologyDomeTransitions({
    mapArrangementRef,
    mapArrangement,
    domeWorldSourceRef,
    lastActiveMsRef,
    view3dRef,
    view3d,
    domeFitPendingRef,
    domeFitDurationRef,
    flatFitPendingRef,
    domeRuntimeRef,
    lastInputMsRef,
    detailPanelVisible,
    realmTransitionRef,
    focusedSlugRef,
  });
  useTopologyAppearanceEffects({
    expandPrefRef,
    expand,
    canvasBackgroundRef,
    canvasBackground,
    animatedBgRef,
    footprintPrefRef,
    footprint,
    footprintInkRef,
    footprintStepColorRef,
    canvasRef,
    bgPointerRef,
    navYieldUntilRef,
    hoveredNodeIdRef,
    lastActiveMsRef,
    ambientSleepDelayRef,
    ambientSleepDelayMs,
    tierRevealRef,
    tierReveal,
    selectedEdgeRef,
    selectedEdge,
    annotationRef,
    args,
  });
  /*
   * Lit 3D — the evidence states the light is drawn from. A new measurement is a static
   * state change, so it wakes the idle gate for one more frame the way a selection does.
   */
  const domeEvidenceRef = useRef<ReadonlyMap<string, "current" | "stale" | "unknown"> | null>(args.domeEvidence ?? null);
  useEffect(() => {
    domeEvidenceRef.current = args.domeEvidence ?? null;
    lastActiveMsRef.current = performance.now();
  }, [args.domeEvidence, lastActiveMsRef]);
  useTopologyClusterExpansion({
    prevExpandedParentsRef,
    expandedParents,
    expandedParentsRef,
    lastActiveMsRef,
    worldRef,
    viewportRef,
    hasInitializedRef,
    overviewScaleRef,
    expandPrefRef,
    cameraTokens,
    dampingRef,
    cameraTargetRef,
    userDrivenCameraRef,
    cameraAngularFreqRef,
    beginCameraTween,
    domeRuntimeRef,
  });
  useTopologyTrailInputs({
    panelEmphasisNodeIdRef,
    emphasizedNeighborSlug,
    visitedTrailRef,
    visitedTrail,
    visitedTrailSetRef,
    lastActiveMsRef,
  });
  useTopologyMotionPreference({
    reducedMotionRef,
  });
  useTopologyGalaxyTransition({
    overviewFit,
    galaxyRef,
    galaxy,
    galaxyLayoutHandoffRef,
    galaxyModeCameraRef,
    cameraTargetRef,
    userDrivenCameraRef,
    pendingFlatCameraRef,
    galaxyEnteredAtRef,
    galaxyAtmosphereSeedRef,
    worldRef,
    galaxyLayoutRef,
    galaxyFlatReturnPositionsRef,
    nodeDragRef,
    heatRef,
    dragAffectedSetRef,
    dragStartPosRef,
    dragTugOffsetsRef,
    homeSpringsRef,
    homeTargetOverrideRef,
    homingActiveRef,
    lastActiveMsRef,
    viewportRef,
    hasInitializedRef,
    overviewFitRef,
    expandedParentsRef,
    cameraTokens,
    overviewScaleRef,
    dampingRef,
    cameraAngularFreqRef,
    reducedMotionRef,
    cameraTweenRef,
    cameraRef,
    beginCameraTween,
    cameraGestureRevisionRef,
  });
  const { rescueCameraIfEverythingOffscreen, trySnapInitialCamera } = useTopologyWorldLifecycle({
    worldRef,
    viewportRef,
    cameraRef,
    galaxyRef,
    galaxyLayoutRef,
    overviewFitRef,
    expandedParentsRef,
    clusteredIdsRef,
    cameraTokens,
    cameraTargetRef,
    userDrivenCameraRef,
    hasInitializedRef,
    overviewScaleRef,
    cameraAngularFreqRef,
    pendingSpotlightFitRef,
    runSpotlightFitRef,
    containerRef,
    nodes,
    edges,
    expand,
    galaxyFlatReturnPositionsRef,
    galaxyLayoutHandoffRef,
    prevNodeIdsRef,
    appearRef,
    bornNodeIdsRef,
    hasDependsEdgesRef,
    hasContainsEdgesRef,
    pulsesRef,
    simRef,
    nodeDragRef,
    heatRef,
    dragAffectedSetRef,
    dragStartPosRef,
    dragTugOffsetsRef,
    homeSpringsRef,
    homingActiveRef,
    homeTargetOverrideRef,
    prevPinnedNodeIdRef,
    onVisibleCountChange,
    onGraphStatsChange,
    dataSourceKey,
    fittedDataSourceKeyRef,
    galaxyModeCameraRef,
    pendingFlatCameraRef,
  });

  useTopologyViewportLifecycle({
    elements: {
      canvasRef,
      containerRef,
      canvasRectRef,
    },
    viewport: {
      viewportRef,
      pendingViewportRef,
      viewportRebuildPendingRef,
      viewportCameraTrackedRef,
      hasInitializedRef,
    },
    layers: {
      gridCanvasRef,
      gridPatternRef,
      depthDotCanvasRef,
      depthDotPatternsRef,
      dustPointsRef,
      cosmosPointsRef,
    },
    frameBridge: {
      commitViewportSizeRef,
      rebuildViewportLayersRef,
      reframeViewportRef,
    },
    trySnapInitialCamera,
    rescueCameraIfEverythingOffscreen,
  });
  const { runOverviewFit } = useTopologyOverviewNavigation({
    worldRef,
    viewportRef,
    hasInitializedRef,
    realmDataRef,
    realmTransitionRef,
    expandedParentsRef,
    cameraTargetRef,
    userDrivenCameraRef,
    dampingRef,
    cameraAngularFreqRef,
    beginCameraTween,
    domeRuntimeRef,
    domeFitTarget,
    lastActiveMsRef,
    overviewFitRef,
    spotlightIdsRef,
    runSpotlightFitRef,
    galaxyRef,
    galaxyLayoutRef,
    clusteredIdsRef,
    cameraTokens,
    overviewScaleRef,
  });
  useTopologyGrowthReplay({
    growthReplayToken,
    growthReplayTokenSeenRef,
    growthReplayRef,
    endGrowthReplay,
    worldRef,
    reducedMotionRef,
    runOverviewFit,
    cameraTargetRef,
    overviewScaleRef,
    domeRuntimeRef,
    clusteredIdsRef,
    tierRevealRef,
    growthReplayAppearRef,
    lastActiveMsRef,
    onGrowthReplayingChangeRef,
    canvasRef,
  });
  useTopologyCameraNavigation({
    runOverviewFit,
    worldRef,
    viewportRef,
    hasInitializedRef,
    realmDataRef,
    realmTransitionRef,
    expandedParentsRef,
    cameraTargetRef,
    userDrivenCameraRef,
    dampingRef,
    cameraAngularFreqRef,
    beginCameraTween,
    domeRuntimeRef,
    domeFitTarget,
    lastActiveMsRef,
    overviewFitRef,
    spotlightIdsRef,
    runSpotlightFitRef,
    galaxyRef,
    galaxyLayoutRef,
    clusteredIdsRef,
    cameraTokens,
    overviewScaleRef,
    initialFitTokensRef,
    relayoutToken,
    fitViewToken,
    mapLensKindRef,
    constellationFocusId,
    constellationCameraRef,
    dataSourceKey,
    cameraTweenRef,
    cameraRef,
    spotlightFitToken,
    lastProcessedSpotlightFitTokenRef,
    pendingSpotlightFitRef,
    previousConstellationFocusIdRef,
    focusedSlugRef,
    selectedEdgeRef,
    domeFocusPendingRef,
    reframeViewportRef,
  });
  useTopologyLayoutCommands({
    relayoutToken,
    initialRelayoutTokenRef,
    worldRef,
    nodeDragRef,
    heatRef,
    dragAffectedSetRef,
    dragStartPosRef,
    dragTugOffsetsRef,
    realmDataRef,
    realmTransitionRef,
    simRef,
    homeSpringsRef,
    homeTargetOverrideRef,
    homingActiveRef,
    galaxyRef,
    galaxyLayoutRef,
    galaxyLayoutHandoffRef,
    revealToken,
  });
  useTopologyFocusNavigation({
    lastFocusedSlugRef,
    focusedSlug,
    egoRevealBatchesRef,
    selectionPulseRef,
    galaxyRef,
    cameraTargetRef,
    galaxyInspectionCameraRef,
    constellationFocusId,
    cameraGestureRevisionRef,
    userDrivenCameraRef,
    dampingRef,
    cameraAngularFreqRef,
    lastActiveMsRef,
    beginCameraTween,
    focusedSlugRef,
    canvasRef,
    worldRef,
    viewportRef,
    overviewScaleRef,
    view3dRef,
    realmTransitionRef,
    domeRuntimeRef,
    realmDataRef,
    expandedParentsRef,
    cameraTokens,
    focusLeashPxRef,
    overviewFitRef,
    clusteredIdsRef,
    mapLensKindRef,
    spotlightIdsRef,
  });
  useTopologyRealmTransition({
    realmRootId,
    prevRealmRootIdRef,
    lastActiveMsRef,
    worldRef,
    viewportRef,
    reducedMotionRef,
    nodeDragRef,
    heatRef,
    dragAffectedSetRef,
    dragStartPosRef,
    dragTugOffsetsRef,
    realmActiveHandedOffRef,
    expandedParentsRef,
    realmDataRef,
    wardingFitRef,
    realmTransitionRef,
    homingActiveRef,
    homeSpringsRef,
    homeTargetOverrideRef,
    hasInitializedRef,
    cameraRef,
    dampingRef,
    cameraTargetRef,
    userDrivenCameraRef,
    cameraAngularFreqRef,
    beginCameraTween,
    simRef,
    overviewFitRef,
    clusteredIdsRef,
    overviewScaleRef,
  });

  // --- single rAF loop: physics -> altitude -> emphasis -> particles -> draw ---
  useTopologyFrameLoop({
    canvasRef,
    projection: { domeRuntimeRef, cameraRef, reducedMotionRef, neuralRampRef },
    recovery: { lastActiveMsRef, viewportRebuildPendingRef },
    domeFrameStage: {
      view3dRef,
      realmTransitionRef,
      domeRuntimeRef,
      domeWorldSourceRef,
      domeModelBuildRef,
      mapArrangementRef,
      domeFitPendingRef,
      domeFitDurationRef,
      flatFitPendingRef,
      domeFocusPendingRef,
      cameraRef,
      cameraTargetRef,
      dampingRef,
      cameraAngularFreqRef,
      userDrivenCameraRef,
      overviewScaleRef,
      overviewFitRef,
      expandedParentsRef,
      clusteredIdsRef,
      pointerMachineRef,
      bgPointerRef,
      reducedMotionRef,
      lastInputMsRef,
      lastActiveMsRef,
      ambientSleepDelayRef,
      viewportRef,
      beginCameraTween,
      cameraTokens,
      domeFitTarget,
    },
    worldMotionFrameStage: {
      simRef,
      nodeDragRef,
      heatRef,
      homingActiveRef,
      dragAffectedSetRef,
      dragStartPosRef,
      dragTugOffsetsRef,
      dragVelRef,
      dragPrevPosRef,
      dropSeededRef,
      geomPrevXRef,
      geomPrevYRef,
      sepDisplacedIdsRef,
      homeSpringsRef,
      homeTargetOverrideRef,
      prevPinnedNodeIdRef,
      clusteredIdsRef,
      expandedParentsRef,
      view3dRef,
      domeRuntimeRef,
      realmDataRef,
      realmTransitionRef,
      realmActiveHandedOffRef,
      wardingFitRef,
      reducedMotionRef,
      pendingFlatCameraRef,
      galaxyLayoutHandoffRef,
      galaxyFlatReturnPositionsRef,
      cameraGestureRevisionRef,
      cameraRef,
      cameraTargetRef,
      cameraTweenRef,
      cameraAngularFreqRef,
      dampingRef,
      userDrivenCameraRef,
      overviewScaleRef,
      overviewFitRef,
      beginCameraTween,
    },
    cameraFrameStage: {
      focusedSlugRef,
      trailLensPropRef,
      trailBrushPropRef,
      panelHoverPropRef,
      hoveredNodeIdRef,
      drawnHoveredNodeIdRef,
      panelEmphasisNodeIdRef,
      cameraTweenRef,
      reducedMotionRef,
      cameraRef,
      cameraTargetRef,
      dampingRef,
      overviewScaleRef,
      cameraAngularFreqRef,
      lastInputMsRef,
      ambientSleepDelayRef,
      selectedEdgeRef,
      pointerMachineRef,
      domeRuntimeRef,
      focusLeashPxRef,
      userDrivenCameraRef,
      clusteredIdsRef,
      emphasisRef,
      rippleStartRef,
      egoRevealRef,
      focusRampRef,
      growthReplayRef,
      growthReplayAppearRef,
      appearRef,
      tierRevealRef,
      drawnFarTRef,
      colorFocusRef,
      pulsesRef,
      realmDataRef,
      realmTransitionRef,
      realmParallaxDepth2Ref,
      realmParallaxDepth3Ref,
      realmParallaxRef,
      prevCameraCenterRef,
      lastZoomTierRef,
      onZoomTierChangeRef,
    },
    clusterFrameStage: {
      expandedParentsRef,
      overviewFitRef,
      realmExpandChainRef,
      realmDataRef,
      focusedSlugRef,
      expandPrefRef,
      egoRevealBatchesRef,
      clusterRevealBatchesRef,
      prevBatchVisibleRef,
      batchAppearRef,
      batchAppearStartRef,
    },
    realmFrameStage: {
      realmTransitionRef,
      realmDataRef,
      reducedMotionRef,
      realmParallaxRef,
      wardingFitRef,
      realmEnterButtonElRef,
      focusedSlugRef,
      onEnterRealmRef,
      realmEnterTargetRef,
      domeRuntimeRef,
      tourAnchorElRef,
      tourAnchorNodeIdRef,
      getRealmCaption,
    },
    revealFrameStage: {
      chipRevealRef,
      batchAppearRef,
      batchAppearStartRef,
      expandRevealRef,
      clusteredIdsRef,
      reducedMotionRef,
    },
    frameGate: {
      pointerMachineRef,
      nodeDragRef,
      pendingViewportRef,
      appliedDprScaleRef,
      viewportRef,
      commitViewportSizeRef,
      viewportSettleFramesRef,
      lastActiveMsRef,
      viewportRebuildPendingRef,
      rebuildViewportLayersRef,
      worldRef,
      lastFrameTimeRef,
      previewEdgePropRef,
      previewSignatureRef,
      previewEdgeHeldRef,
      previewTransitionRef,
      previewAlphaRef,
      previewCommitRef,
      reducedMotionRef,
      navYieldUntilRef,
      cameraRef,
      cameraTargetRef,
      prevCameraSampleRef,
      lastInputMsRef,
      ambientSleepDelayRef,
      domeRuntimeRef,
      view3dRef,
      realmTransitionRef,
      domeFocusPendingRef,
      bgPointerRef,
      growthReplayRef,
      growthReplayAppearRef,
      endGrowthReplay,
      heatRef,
      homingActiveRef,
      selectionPulseRef,
      hasDependsEdgesRef,
      focusedSlugRef,
      hasContainsEdgesRef,
      pulsesRef,
      hoveredNodeIdRef,
      panelEmphasisNodeIdRef,
      hoveredClusterIdRef,
      trailLensPropRef,
      trailBrushPropRef,
      panelHoverPropRef,
      galaxyRampRef,
      galaxyRef,
      neuralRampRef,
      mapArrangementRef,
      drawnTrailLensRef,
      trailLensRampRef,
      visitedTrailRef,
      colorFocusRef,
      selectedEdgeRef,
      spotlightRampRef,
      spotlightIdsRef,
      idleDebugEnabledRef,
      lastActiveCausesRef,
    },
    presentationFrameStage: {
      galaxyRef,
      domeRuntimeRef,
      clusterChipsRef,
      clusteredIdsRef,
      realmTierKindsRef,
      visitedTrailRef,
      footprintTrailLenRef,
      footprintAppearAtRef,
      reducedMotionRef,
      spotlightRampRef,
      spotlightIdsRef,
      spotlightDashOffsetRef,
      trailLensOpenedAtRef,
      trailLensRampRef,
      view3dRef,
      neuralRampRef,
      galaxyLayoutHandoffRef,
      galaxyRampRef,
      animatedBgRef,
      lastInputMsRef,
      ambientSleepDelayRef,
      bgPointerRef,
      galaxyLayoutRef,
      galaxyEnteredAtRef,
      galaxyAtmosphereSeedRef,
      panelInsetsRef,
      gridPatternRef,
      dustPointsRef,
      hoverStartRef,
      hoverReleasedRef,
      hoveredEdgeRef,
      selectedEdgeRef,
      annotationRef,
      previewEdgeHeldRef,
      previewAlphaRef,
      previewCommitRef,
      emphasisRef,
      egoRevealRef,
      focusRampRef,
      growthReplayRef,
      growthReplayAppearRef,
      appearRef,
      bornNodeIdsRef,
      chipRevealRef,
      expandRevealRef,
      batchAppearRef,
      labelPresentRef,
      colorFocusRef,
      pulsesRef,
      selectionPulseRef,
      agentFocusNodeIdRef,
      hoveredClusterIdRef,
      cosmosPointsRef,
      footprintPrefRef,
      footprintStepColorRef,
      footprintInkRef,
      visitedTrailSetRef,
      mapLensKindRef,
      pathEdgeIdsRef,
      tierRevealRef,
      glyphStyleRef,
      canvasBackgroundRef,
      depthDotPatternsRef,
      expandPrefRef,
      getClusterBarLabels,
      mapArrangementRef,
      domeTierRaisedKindRef,
      drawnTrailLensRef,
      tourAnchorNodeIdRef,
      drawnNodeCountRef,
      onDrawnCountChangeRef,
      domeTierAnchorsSentRef,
      onDomeTierAnchorsChangeRef,
      domeTierNameWidthsRef,
      domeFitInsetsRef,
      domeEvidenceRef,
    },
  });
  const { handlersRef, handlers, wrappedHandlers } = useTopologyInput({
    wheelIntent,
    worldRef,
    cameraRef,
    cameraTargetRef,
    cameraTweenRef,
    dampingRef,
    cameraAngularFreqRef,
    viewportRef,
    pointerMachineRef,
    dragHistoryRef,
    domeGripRef,
    camStartAtDownRef,
    canvasRectRef,
    canvasRef,
    focusedSlugRef,
    hoveredNodeIdRef,
    rippleStartRef,
    reducedMotionRef,
    userDrivenCameraRef,
    cameraGestureRevisionRef,
    simRef,
    heatRef,
    nodeDragRef,
    dragAffectedSetRef,
    dragStartPosRef,
    overviewScaleRef,
    activeTouchesRef,
    pinchRef,
    hoveredEdgeRef,
    selectedEdgeRef,
    clusterChipsRef,
    lastTapRef,
    expandPrefRef,
    clusterBarLabelsRef,
    clusteredIdsRef,
    hoveredClusterIdRef,
    realmParallaxRef,
    realmTierKindsRef,
    domeRuntimeRef,
    neuralRampRef,
    tierRevealRef,
    galaxyRef,
    pathEdgeIdsRef,
    visitedTrailRef,
    onSelect,
    onSelectEdge,
    onHoverEdge,
    onPaneClick,
    onContextMenuNode,
    onContextMenuPane,
    onToggleCluster,
    onHoverCluster,
    egoRevealBatchesRef,
    clusterRevealBatchesRef,
    realmEnterButtonRef,
    realmEnterTargetRef,
    onEnterRealmRef,
    lastInputMsRef,
    lastActiveMsRef,
    onWalkDeadEnd,
    runOverviewFit,
    beginCameraTween,
  });
  useTopologyMapInstrumentation({
    scene: {
      canvasRef,
      viewportRef,
      worldRef,
      simRef,
      clusteredIdsRef,
      clusterChipsRef,
      previewEdgeHeldRef,
      domeRuntimeRef,
      galaxyRampRef,
      neuralRampRef,
      reducedMotionRef,
    },
    interaction: {
      handlersRef,
      pointerMachineRef,
      nodeDragRef,
      cameraRef,
      cameraTargetRef,
      hoveredNodeIdRef,
      drawnHoveredNodeIdRef,
      focusedSlugRef,
      selectedEdgeRef,
      agentFocusNodeIdRef,
    },
    activity: {
      idleDebugEnabledRef,
      lastActiveCausesRef,
      heatRef,
      lastInputMsRef,
      lastActiveMsRef,
    },
    lens: {
      mapLensKindRef,
      spotlightIdsRef,
      pathEdgeIdsRef,
      visitedTrailRef,
      trailLensRampRef,
      drawnFarTRef,
    },
  });

  /**
   * Raise one Strata plane's ring — the legend rail's hover, arriving from a DOM
   * row rather than from the canvas. It marks activity as well as setting the ref,
   * because the idle gate is skipping frames whenever the map is at rest, which is
   * exactly when someone reads the legend.
   */
  const raiseDomeTier = useCallback((kind: DomeViewKind | null) => {
    if (domeTierRaisedKindRef.current === kind) return;
    domeTierRaisedKindRef.current = kind;
    lastActiveMsRef.current = performance.now();
  }, [domeTierRaisedKindRef, lastActiveMsRef]);

  /**
   * The tier names' widths, measured by the names themselves in their own type — the
   * canvas cannot measure DOM text. Marks activity so a map at rest places them.
   */
  const setDomeTierNameWidths = useCallback((widths: Readonly<Record<string, number>>) => {
    domeTierNameWidthsRef.current = widths;
    lastActiveMsRef.current = performance.now();
  }, [domeTierNameWidthsRef, lastActiveMsRef]);

  return { canvasRef, containerRef, raiseDomeTier, setDomeTierNameWidths, ...handlers, ...wrappedHandlers };
}
