import type { CameraAxes } from "../../engine/camera";
import type { EdgePairFocus, NodeEgoState } from "../../model/focus-state";
import type { ExpandPreference, FootprintPreference } from "@/shared/lib/appearance-preferences";
import type { DomeNodeFrame } from "../../model/dome-view";
import type { DomeLightFrame } from "../../render/dome-light";
import type { TierRevealConfig } from "../../model/tier-visibility";
import type { RelationCaption } from "../../render/relation-captions";
import type { ReservedBox, SafeRect } from "../../render/label-layout";
import type { ClusterBarLabels } from "../../render/cluster-chips";
import type { ClusterChip } from "../../model/density-gate";
import type { DustPoint } from "../../render/starfield";
import type { Pulse } from "../../render/edge-fireflies";
import type { OntologyMapTokens } from "../../tokens/read-map-tokens";
import type { TopologyWorld, WorldEdge } from "../topology-world";
import type { FlatDialFrameProps } from "../topology-loop-contract";
import type { ConeKind } from "../../model/cone-layout";
import type { TrailGlintLeg } from "../../model/footprint-steps";
import type { StrataLodState } from "../../model/strata-lod";
import { type FrameDrawParams } from "./frame-draw-params";

export interface FrameScope {
  params: FrameDrawParams;
  agentFocusNodeId: string | null;
  appearById: ReadonlyMap<string, number> | undefined;
  backgroundVariant: "depth" | "dot" | "web";
  batchAppearById: ReadonlyMap<string, number> | undefined;
  bornNodeIds: ReadonlySet<string> | null | undefined;
  camera: CameraAxes;
  canvasDpr: number;
  captionFoldedIds: ReadonlySet<string> | null;
  chipRevealById: ReadonlyMap<string, number> | undefined;
  clusterBarLabels: ClusterBarLabels | null;
  clusterChips: readonly ClusterChip[];
  clusteredIds: ReadonlySet<string>;
  colorFocusedNodeId: string | null;
  colorSelectedEdge: EdgePairFocus | null;
  depthDotPatterns: readonly (CanvasPattern | null)[] | undefined;
  dialProps: Pick<FlatDialFrameProps, "evidence" | "impactLens" | "labels"> | null;
  domeControlFor: ((edge: WorldEdge) => { x: number; y: number } | null) | null;
  domeLight: DomeLightFrame | null;
  domeRamp: number;
  domeRingAlpha: number;
  domeRings: readonly { kind: ConeKind; a: number; points: readonly { wx: number; wy: number; u: number }[]; label?: { wx: number; wy: number } | null | undefined; }[] | null;
  domeTierRaisedKind: ConeKind | null;
  dustPoints: readonly DustPoint[];
  egoRevealById: ReadonlyMap<string, number>;
  emphasisById: ReadonlyMap<string, number>;
  emphasizedNeighborId: string | null;
  expand: ExpandPreference;
  expandRevealById: ReadonlyMap<string, number> | null | undefined;
  farT: number;
  focusedNodeId: string | null;
  focusRampById: ReadonlyMap<string, number>;
  footprintAppear: number;
  footprintInk: readonly [number, number, number];
  footprintNewestId: string | null;
  footprintNewestStep: number;
  footprintPref: FootprintPreference | null;
  footprintStepColor: string;
  footprintStepsById: ReadonlyMap<string, readonly number[]>;
  glyphStyle: "fill" | "line";
  gridPattern: CanvasPattern | null;
  hoveredClusterId: string | null;
  hoveredEdge: { sourceId: string; targetId: string; relationType: string } | null;
  hoveredNodeId: string | null;
  hoverReleasedNodeId: string | null;
  hoverStartedAt: number | null;
  labelPresentById: Map<string, number> | undefined;
  mapLensKind: "all" | "constellation" | "path" | "recent";
  now: number;
  paintAnimatedBackground: ((ctx: CanvasRenderingContext2D, width: number, height: number) => void) | null;
  panelInsets: { left: number; right: number } | null;
  pathEdgeIds: ReadonlySet<string> | null;
  previewEdge: { sourceId: string; targetId: string; relationType: string; phase: "committing" | "draft"; alpha: number; commitProgress: number } | null;
  pulses: readonly Pulse[];
  realmDepthById: ReadonlyMap<string, number> | null;
  realmDustParallax: number;
  realmOutsideReturnAlphaById: ReadonlyMap<string, number> | null;
  realmStarPoints: readonly DustPoint[] | null;
  realmTierKinds: ReadonlyMap<string, "capability" | "domain" | "element" | "project"> | null;
  reducedMotion: boolean;
  relationCaptions: ReadonlyMap<string, string> | null | undefined;
  reviewQuestionIds: ReadonlySet<string> | null | undefined;
  selectedEdge: EdgePairFocus | null;
  selectionPulse: { nodeId: string; startAtMs: number } | null;
  spotlightDashOffset: number;
  spotlightIds: ReadonlySet<string> | null;
  spotlightRamp: number;
  tierNameBoxes: readonly { minX: number; maxX: number; minY: number; maxY: number }[] | null;
  tierReveal: TierRevealConfig;
  tokens: OntologyMapTokens;
  trailLensOpenedAtMs: number;
  trailStarInk: string | null;
  viewportHeight: number;
  viewportWidth: number;
  walkedEdgeArrivalStep: ReadonlyMap<string, number> | null;
  walkedEdgeDirections: ReadonlyMap<string, boolean> | null;
  walkedEdgeKeys: ReadonlySet<string> | null;
  wardingRing: { centerX: number; centerY: number; radius: number; drawProgress: number; caption: string | null } | null;
  world: TopologyWorld;
  zoomRatio: number;
  ctx: CanvasRenderingContext2D;
  spotlightLensActive: boolean;
  pathLensActive: boolean;
  constellationLensActive: boolean;
  recentSpotlightActive: boolean;
  spotlightSink: (inSpotlight: boolean) => number;
  trailLensKeepIds: ReadonlySet<string> | null;
  trailLensActive: boolean;
  trailRamp: number;
  trailGlint: number;
  trailGlintLegs: Map<string, TrailGlintLeg> | null;
  isTrailKept: (nodeId: string) => boolean;
  lensNodeEgoState: (nodeId: string, focusId: string | null, neighbors: ReadonlySet<string>, pair: EdgePairFocus | null) => NodeEgoState;
  realmDepthOf: (nodeId: string) => number | undefined;
  realmParallaxOffsetFor: (nodeId: string) => { x: number; y: number };
  domeOn: boolean;
  neural: number;
  domeFrameFor: (nodeId: string) => DomeNodeFrame;
  nodeFrameAt: (index: number) => DomeNodeFrame;
  gridOrigin: { x: number; y: number };
  footprintScale: number;
  labelScale: number;
  bgOrigin: { x: number; y: number };
  project: (x: number, y: number) => { x: number; y: number };
  camX: number;
  camY: number;
  camScale: number;
  halfW: number;
  halfH: number;
  projectEdgePoints: (edge: WorldEdge, knownOffA?: DomeNodeFrame | undefined, knownOffB?: DomeNodeFrame | undefined) => { a: { x: number; y: number }; b: { x: number; y: number }; control: { x: number; y: number }; };
  egoGlowRamp: number;
  neighborsOfFocusedRaw: ReadonlySet<string>;
  parentOf: (id: string) => string | null | undefined;
  litOn: boolean;
  domeAncestryOn: boolean;
  domeAncestryEdges: ReadonlySet<string>;
  neighborsOfFocused: ReadonlySet<string>;
  colorNeighbors: ReadonlySet<string>;
  litFocusId: string | null;
  litFocusRamp: number;
  inLitLine: (id: string) => boolean;
  lod: StrataLodState | null;
  egoAllNormal: boolean;
  colorAllNormal: boolean;
  traceTokensFrame: { edgeContains: string; edgeContainsL0: string; edgeContainsL2: string; edgeDepends: string; edgeDim: string; indigo: string; indigoBright: string; edgeSelected: string; edgeTrail: string };
  nodeShapeTokensFrame: { amberHub: string; recentChange: string; numeralShadow: string; numeralFace: string; holeFill: string; projectHairlineInner: string; projectPinTick: string; selectionIndigo: string; selectionHairline: string; neighborRing: string; hoverRing: string; hoverShimmerSeg: number; hoverShimmerPeriodMs: number; hoverShimmerColor: string };
  effectiveAlphaById: Map<string, number>;
  effectiveAlphaByIndex: Float64Array<ArrayBuffer>;
  expandedParentIds: Set<string>;
  expandedDiscIds: Set<string>;
  expandedChildIds: Set<string>;
  anyExpanded: boolean;
  egoCometEdges: ReadonlySet<WorldEdge>;
  edgeAlphaReused: Float64Array;
  edgeLiftReused: Float64Array;
  edgeRestDimReused: Float64Array;
  edgeFocusRamp: number;
  edgeRevealAt: number;
  captionCandidates: RelationCaption[];
  isSpineEndpoint: (id: string) => boolean;
  edgeEnds: { source: Int32Array<ArrayBufferLike>; target: Int32Array<ArrayBufferLike> };
  ambientDependsComets: ReadonlySet<string>;
  domeHaloColor: string;
  edgeDrawOrder: readonly WorldEdge[];
  drawnScreenRadiusById: Map<string, number>;
  nodeDiscReservations: ReservedBox[];
  chipReservations: ReservedBox[];
  safeRect: SafeRect;
}
