// AUTO-GENERATED by scripts/build-docs-vault.mjs — 손으로 편집 금지.
// 실제 dogfood vault(docs/ontology) frontmatter 에서 유도한 census.
// /download 소개 섹션 topology 미니어처의 "음각 숫자 = 실데이터" 계약 진실원.
export interface DogfoodCensus {
  concepts: number;
  relations: number;
  kinds: {
    project: number;
    domain: number;
    capability: number;
    element: number;
    document: number;
  };
  domains: ReadonlyArray<{ slug: string; title: string }>;
  domainRelates: ReadonlyArray<ReadonlyArray<string>>;
  hub: { slug: string; title: string; domain: string | null } | null;
}

export const DOGFOOD_CENSUS: DogfoodCensus = {
  "concepts": 4,
  "relations": 5,
  "kinds": {
    "project": 1,
    "domain": 1,
    "capability": 1,
    "element": 1,
    "document": 0
  },
  "domains": [
    {
      "slug": "example-domain",
      "title": "Example domain"
    }
  ],
  "domainRelates": [],
  "hub": {
    "slug": "example-capability",
    "title": "Example capability",
    "domain": "example-domain"
  }
};
