// AUTO-GENERATED by scripts/build-docs-vault.mjs — 손으로 편집 금지.
// 실제 dogfood vault(docs/ontology) frontmatter 에서 유도한 census.
// /download 소개 섹션 topology 미니어처의 "음각 숫자 = 실데이터" 계약 진실원.
export interface DogfoodCensus {
  concepts: number;
  relations: number;
  kinds: {
    project: number;
    domain: number;
    capability: number;
    element: number;
    document: number;
  };
  domains: ReadonlyArray<{ slug: string; title: string }>;
  domainRelates: ReadonlyArray<ReadonlyArray<string>>;
  hub: { slug: string; title: string; domain: string | null } | null;
}

export const DOGFOOD_CENSUS: DogfoodCensus = {
  "concepts": 69,
  "relations": 84,
  "kinds": {
    "project": 1,
    "domain": 6,
    "capability": 19,
    "element": 43,
    "document": 0
  },
  "domains": [
    {
      "slug": "agent-integration",
      "title": "AI Agent Integration"
    },
    {
      "slug": "graph-modeling",
      "title": "Graph Modeling & Ontology Schema"
    },
    {
      "slug": "local-vault-management",
      "title": "Local Vault & Data Source Management"
    },
    {
      "slug": "onboarding-and-shell",
      "title": "Onboarding, Distribution & App Shell"
    },
    {
      "slug": "project-portfolio",
      "title": "Project Portfolio Management"
    },
    {
      "slug": "topology-navigation",
      "title": "Topology Map Navigation"
    }
  ],
  "domainRelates": [],
  "hub": {
    "slug": "mcp-server",
    "title": "MCP Server (32 tools)",
    "domain": "agent-integration"
  }
};
