// AUTO-GENERATED by scripts/build-docs-vault.mjs — 손으로 편집 금지.
// 실제 dogfood vault(docs/ontology) frontmatter 에서 유도한 census.
// /download 소개 섹션 topology 미니어처의 "음각 숫자 = 실데이터" 계약 진실원.
export interface DogfoodCensus {
  concepts: number;
  relations: number;
  kinds: {
    project: number;
    domain: number;
    capability: number;
    element: number;
    document: number;
  };
  domains: ReadonlyArray<{ slug: string; title: string }>;
  domainRelates: ReadonlyArray<ReadonlyArray<string>>;
  hub: { slug: string; title: string; domain: string | null } | null;
}

export const DOGFOOD_CENSUS: DogfoodCensus = {
  "concepts": 102,
  "relations": 480,
  "kinds": {
    "project": 1,
    "domain": 6,
    "capability": 36,
    "element": 56,
    "document": 3
  },
  "domains": [
    {
      "slug": "ai-agent-partner",
      "title": "AI Agent Partner"
    },
    {
      "slug": "mode-aware-adapters",
      "title": "Mode-Aware Adapters"
    },
    {
      "slug": "onboarding-ux",
      "title": "Onboarding & UX (theme · toast · a11y · mobile · CLI)"
    },
    {
      "slug": "ontology-core",
      "title": "Ontology Core (TBox · ABox · Evidence)"
    },
    {
      "slug": "vault-local-first",
      "title": "Vault — Local-First"
    },
    {
      "slug": "views",
      "title": "Views (Topology · Browse · Builder)"
    }
  ],
  "domainRelates": [
    [
      "ai-agent-partner",
      "ontology-core"
    ],
    [
      "ai-agent-partner",
      "vault-local-first"
    ],
    [
      "mode-aware-adapters",
      "ontology-core"
    ],
    [
      "mode-aware-adapters",
      "vault-local-first"
    ],
    [
      "onboarding-ux",
      "views"
    ],
    [
      "ontology-core",
      "vault-local-first"
    ],
    [
      "ontology-core",
      "views"
    ]
  ],
  "hub": {
    "slug": "mcp-server",
    "title": "MCP Server (24 tools)",
    "domain": "ai-agent-partner"
  }
};
