// Generated by `pnpm gateway:specimen` — do not edit by hand.
//
// One real node of this repository's own vault, the one the download page's conduction figure
// casts. Re-run the generator when the node changes; `pnpm gateway:specimen:check` fails the
// build when this file and the vault disagree. Rationale: `scripts/generate-evidence-specimen.mjs`.

interface EvidenceSpecimenName {
  readonly en: string;
  readonly [locale: string]: string;
  /** The map engine's node id (kind:basename). */
  readonly nodeId: string;
}

export interface EvidenceSpecimen {
  /** Vault-relative slug — the string MCP and the CLI accept verbatim. */
  readonly slug: string;
  readonly facts: {
    readonly name: EvidenceSpecimenName;
    readonly dependency: EvidenceSpecimenName;
    readonly implPath: string;
  };
}

export const EVIDENCE_SPECIMEN: EvidenceSpecimen = {
    "slug": "capabilities/mcp-tool-server",
    "facts": {
      "name": {
        "ko": "MCP 도구 서버",
        "en": "MCP tool server",
        "ja": "MCP tool server",
        "zh": "MCP tool server",
        "nodeId": "capability:mcp-tool-server"
      },
      "dependency": {
        "ko": "구축 지침",
        "en": "Construction guidance",
        "ja": "Construction guidance",
        "zh": "Construction guidance",
        "nodeId": "capability:construction-guidance"
      },
      "implPath": "mcp/src/server/registry.mjs"
    }
  } as const;
