// Generated by `pnpm gateway:specimen` — do not edit by hand.
//
// One real file from this repository's own vault, read verbatim, plus the facts an agent reads
// out of it. The gateway's evidence section renders both halves; the claim it makes is that the
// left side is a file you can open in this repo, so nothing here may be hand-typed.
//
// Re-run the generator when the specimen file changes; `pnpm gateway:specimen:check` fails the
// build when this file and the vault disagree. Rationale: `scripts/generate-evidence-specimen.mjs`.

interface EvidenceSpecimenName {
  readonly ko: string;
  readonly en: string;
  /** The map engine's node id (kind:basename) — what focus/emphasis props accept. */
  readonly nodeId: string;
}

export interface EvidenceSpecimen {
  /** Vault-relative slug — the string MCP and the CLI accept verbatim. */
  readonly slug: string;
  /** Repo-relative path, shown above the frontmatter block. */
  readonly file: string;
  /** The same file on GitHub, so the claim is checkable in one click. */
  readonly url: string;
  /** Frontmatter lines, verbatim, in file order, per locale. */
  readonly frontmatter: { readonly ko: readonly string[]; readonly en: readonly string[] };
  /** How many lines are not shown, per locale — stated on screen, never hidden. */
  readonly omittedLines: { readonly ko: number; readonly en: number };
  readonly facts: {
    readonly name: EvidenceSpecimenName;
    readonly kind: string;
    readonly domain: EvidenceSpecimenName;
    readonly dependency: EvidenceSpecimenName;
    readonly implPath: string;
  };
  /** Every `kind:` node in the vault — the caption's "there are N of these" number. */
  readonly vaultNodeCount: number;
}

export const EVIDENCE_SPECIMEN: EvidenceSpecimen = {
    "slug": "capabilities/mcp-tool-server",
    "file": "docs/ontology/capabilities/mcp-tool-server.md",
    "url": "https://github.com/wlsdks/ontology-atlas/blob/main/docs/ontology/capabilities/mcp-tool-server.md",
    "frontmatter": {
      "ko": [
        "kind: capability",
        "title: MCP tool server",
        "display_ko: MCP 도구 서버",
        "domain: domains/agent-access",
        "path: mcp/src/server/registry.mjs"
      ],
      "en": [
        "kind: capability",
        "title: MCP tool server",
        "display_en: MCP tool server",
        "domain: domains/agent-access",
        "path: mcp/src/server/registry.mjs"
      ]
    },
    "omittedLines": {
      "ko": 7,
      "en": 7
    },
    "facts": {
      "name": {
        "ko": "MCP 도구 서버",
        "en": "MCP tool server",
        "nodeId": "capability:mcp-tool-server"
      },
      "kind": "capability",
      "domain": {
        "ko": "에이전트 접근",
        "en": "Agent access",
        "nodeId": "domain:agent-access"
      },
      "dependency": {
        "ko": "구축 지침",
        "en": "Construction guidance",
        "nodeId": "capability:construction-guidance"
      },
      "implPath": "mcp/src/server/registry.mjs"
    },
    "vaultNodeCount": 96
  } as const;
