// Generated by `pnpm gateway:specimen` — do not edit by hand.
//
// One real file from this repository's own vault, read verbatim, plus the facts an agent reads
// out of it. The gateway's evidence section renders both halves; the claim it makes is that the
// left side is a file you can open in this repo, so nothing here may be hand-typed.
//
// Re-run the generator when the specimen file changes; `pnpm gateway:specimen:check` fails the
// build when this file and the vault disagree. Rationale: `scripts/generate-evidence-specimen.mjs`.

export interface EvidenceSpecimenName {
  readonly ko: string;
  readonly en: string;
  /** The map engine's node id (kind:basename) — what focus/emphasis props accept. */
  readonly nodeId: string;
}

export interface EvidenceSpecimen {
  /** Vault-relative slug — the string MCP and the CLI accept verbatim. */
  readonly slug: string;
  /** Repo-relative path, shown above the frontmatter block. */
  readonly file: string;
  /** The same file on GitHub, so the claim is checkable in one click. */
  readonly url: string;
  /** Frontmatter lines, verbatim, in file order, per locale. */
  readonly frontmatter: { readonly ko: readonly string[]; readonly en: readonly string[] };
  /** How many lines are not shown, per locale — stated on screen, never hidden. */
  readonly omittedLines: { readonly ko: number; readonly en: number };
  readonly facts: {
    readonly name: EvidenceSpecimenName;
    readonly kind: string;
    readonly domain: EvidenceSpecimenName;
    readonly dependency: EvidenceSpecimenName;
    readonly implPath: string;
  };
  /** Every `kind:` node in the vault — the caption's "there are N of these" number. */
  readonly vaultNodeCount: number;
}

export const EVIDENCE_SPECIMEN: EvidenceSpecimen = {
    "slug": "capabilities/mcp-server",
    "file": "docs/ontology/capabilities/mcp-server.md",
    "url": "https://github.com/wlsdks/ontology-atlas/blob/main/docs/ontology/capabilities/mcp-server.md",
    "frontmatter": {
      "ko": [
        "kind: capability",
        "title: MCP Server",
        "domain: domains/agent-integration",
        "path: mcp/src",
        "dependencies: [capabilities/vault-ontology]",
        "display_ko: AI 연결 서버"
      ],
      "en": [
        "kind: capability",
        "title: MCP Server",
        "domain: domains/agent-integration",
        "path: mcp/src",
        "dependencies: [capabilities/vault-ontology]",
        "display_en: AI Connection Server"
      ]
    },
    "omittedLines": {
      "ko": 6,
      "en": 6
    },
    "facts": {
      "name": {
        "ko": "AI 연결 서버",
        "en": "AI Connection Server",
        "nodeId": "capability:mcp-server"
      },
      "kind": "capability",
      "domain": {
        "ko": "AI 에이전트 연동",
        "en": "AI Agent Integration",
        "nodeId": "domain:agent-integration"
      },
      "dependency": {
        "ko": "볼트 온톨로지 스키마 작성",
        "en": "Vault Ontology Schema Authoring",
        "nodeId": "capability:vault-ontology"
      },
      "implPath": "mcp/src"
    },
    "vaultNodeCount": 83
  } as const;
