// Generated by `pnpm download:release-facts` — do not edit by hand.
//
// Source of truth: the published GitHub Release for the tag below. The
// generator reads each desktop asset's real byte size and download URL, and
// its real SHA-256 from the sibling `.sha256` asset that the release workflow
// uploads. Nothing here is hand-typed, so `/download` can state a size and a
// checksum without inventing either.
//
// `published: false` is the honest pre-release state: the page then says the
// build is not out yet instead of rendering placeholder facts. Re-run the
// generator after the release publishes and commit the result.

export interface MacosReleaseAsset {
  readonly arch: 'aarch64' | 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
}

export interface MacosRelease {
  readonly published: boolean;
  /**
   * Whether this release is a **candidate** rather than a final one. The page says
   * so rather than hiding it: that a build passed the same signing and
   * notarisation path but has not been widely used yet is something the person
   * downloading needs to know beforehand.
   */
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly MacosReleaseAsset[];
}

export interface WindowsReleaseAsset {
  readonly arch: 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
  /** Authenticode status verified by the Windows release job. */
  readonly signed: false;
}

export interface WindowsRelease {
  readonly published: boolean;
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly WindowsReleaseAsset[];
}

export const MACOS_RELEASE: MacosRelease = {
  published: true,
  prerelease: false,
  tag: "v1.0.4",
  publishedAt: "2026-09-02T09:42:10Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.4",
  assets: [
    {
      arch: "aarch64",
      fileName: "ontology-atlas_1.0.4_aarch64.dmg",
      sizeBytes: 53852971,
      sha256: "2a7d5ac47ec73df2959135d3beb323acd589275e52d68a7f8850bb3c211d61f5",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.4/ontology-atlas_1.0.4_aarch64.dmg",
    },
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.4_x64.dmg",
      sizeBytes: 57240147,
      sha256: "16c09acc30b5c57efd16f11efb61fe2959c19ffb7e7c9c58b27e107c43b8f137",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.4/ontology-atlas_1.0.4_x64.dmg",
    },
  ],
};

export const WINDOWS_RELEASE: WindowsRelease = {
  published: true,
  prerelease: false,
  tag: "v1.0.4",
  publishedAt: "2026-09-02T09:42:10Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.4",
  assets: [
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.4_windows_x64-setup.exe",
      sizeBytes: 50756953,
      sha256: "8dd0db44c383fdaacecf446048515d853129986dba3184bee74523777b9686e0",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.4/ontology-atlas_1.0.4_windows_x64-setup.exe",
      signed: false,
    },
  ],
};
