// Generated by `pnpm download:release-facts` — do not edit by hand.
//
// Source of truth: the published GitHub Release for the tag below. The
// generator reads each desktop asset's real byte size and download URL, and
// its real SHA-256 from the sibling `.sha256` asset that the release workflow
// uploads. Nothing here is hand-typed, so `/download` can state a size and a
// checksum without inventing either.
//
// `published: false` is the honest pre-release state: the page then says the
// build is not out yet instead of rendering placeholder facts. Re-run the
// generator after the release publishes and commit the result.

export interface MacosReleaseAsset {
  readonly arch: 'aarch64' | 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
}

export interface MacosRelease {
  readonly published: boolean;
  /**
   * Whether this release is a **candidate** rather than a final one. The page says
   * so rather than hiding it: that a build passed the same signing and
   * notarisation path but has not been widely used yet is something the person
   * downloading needs to know beforehand.
   */
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly MacosReleaseAsset[];
}

export interface WindowsReleaseAsset {
  readonly arch: 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
  /** Authenticode status verified by the Windows release job. */
  readonly signed: false;
}

export interface WindowsRelease {
  readonly published: boolean;
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly WindowsReleaseAsset[];
}

export const MACOS_RELEASE: MacosRelease = {
  published: true,
  prerelease: true,
  tag: "v1.0.0-rc.18",
  publishedAt: "2026-08-29T14:20:21Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.0-rc.18",
  assets: [
    {
      arch: "aarch64",
      fileName: "ontology-atlas_1.0.0-rc.18_aarch64.dmg",
      sizeBytes: 50976653,
      sha256: "222251fdaa19cf66f5d93fd17db3906ac9f4b51daef1c45ea5777032c6c2ebbc",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.0-rc.18/ontology-atlas_1.0.0-rc.18_aarch64.dmg",
    },
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.0-rc.18_x64.dmg",
      sizeBytes: 54782845,
      sha256: "2d3fe16be59a121afb651153c24a2e26733fe17283331e2bb2a07e6ab6b10fbe",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.0-rc.18/ontology-atlas_1.0.0-rc.18_x64.dmg",
    },
  ],
};

export const WINDOWS_RELEASE: WindowsRelease = {
  published: true,
  prerelease: true,
  tag: "v1.0.0-rc.18",
  publishedAt: "2026-08-29T14:20:21Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.0-rc.18",
  assets: [
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.0-rc.18_windows_x64-setup.exe",
      sizeBytes: 48123759,
      sha256: "c0859a5a506b0e0a9ab6a7107e2993f8c79b65beee0081ef0a803513999a9bcd",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.0-rc.18/ontology-atlas_1.0.0-rc.18_windows_x64-setup.exe",
      signed: false,
    },
  ],
};
