// Generated by `pnpm download:release-facts` — do not edit by hand.
//
// Source of truth: the published GitHub Release for the tag below. The
// generator reads each desktop asset's real byte size and download URL, and
// its real SHA-256 from the sibling `.sha256` asset that the release workflow
// uploads. Nothing here is hand-typed, so `/download` can state a size and a
// checksum without inventing either.
//
// `published: false` is the honest pre-release state: the page then says the
// build is not out yet instead of rendering placeholder facts. Re-run the
// generator after the release publishes and commit the result.

export interface MacosReleaseAsset {
  readonly arch: 'aarch64' | 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
}

export interface MacosRelease {
  readonly published: boolean;
  /**
   * Whether this release is a **candidate** rather than a final one. The page says
   * so rather than hiding it: that a build passed the same signing and
   * notarisation path but has not been widely used yet is something the person
   * downloading needs to know beforehand.
   */
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly MacosReleaseAsset[];
}

export interface WindowsReleaseAsset {
  readonly arch: 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
  /** Authenticode status verified by the Windows release job. */
  readonly signed: false;
}

export interface WindowsRelease {
  readonly published: boolean;
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly WindowsReleaseAsset[];
}

export const MACOS_RELEASE: MacosRelease = {
  published: true,
  prerelease: false,
  tag: "v1.0.3",
  publishedAt: "2026-09-01T13:03:53Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.3",
  assets: [
    {
      arch: "aarch64",
      fileName: "ontology-atlas_1.0.3_aarch64.dmg",
      sizeBytes: 53991372,
      sha256: "bc947dd3aa186b3453beba15c349faecd2dc0a17a064fa14880346413e49f5cd",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.3/ontology-atlas_1.0.3_aarch64.dmg",
    },
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.3_x64.dmg",
      sizeBytes: 57737259,
      sha256: "7b606323c80649f965b2814d3f9e6d56120367e0b998897509153cc4f13a5b5b",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.3/ontology-atlas_1.0.3_x64.dmg",
    },
  ],
};

export const WINDOWS_RELEASE: WindowsRelease = {
  published: true,
  prerelease: false,
  tag: "v1.0.3",
  publishedAt: "2026-09-01T13:03:53Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.0.3",
  assets: [
    {
      arch: "x64",
      fileName: "ontology-atlas_1.0.3_windows_x64-setup.exe",
      sizeBytes: 51685269,
      sha256: "0a8212a9fb285dd414197d38b96bd6cc1653abdfddf554be431c2dde2123f035",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.0.3/ontology-atlas_1.0.3_windows_x64-setup.exe",
      signed: false,
    },
  ],
};
