/**
 * The one place that decides what `/download` may claim: published gives real size, checksum
 * and links; unpublished gives one "not out yet" state with no invented numbers. The release
 * facts are generated by `pnpm download:release-facts`, never hand-edited.
 */

import {
  MACOS_RELEASE,
  WINDOWS_RELEASE,
  type MacosReleaseAsset,
  type WindowsReleaseAsset,
} from '../model/macos-release.generated';

export type DesktopArch = MacosReleaseAsset['arch'];

export const ARCH_ORDER: readonly DesktopArch[] = ['aarch64'];

export function isMacosReleasePublished(): boolean {
  return MACOS_RELEASE.published && MACOS_RELEASE.assets.length > 0;
}

/** Shown beside the version, which alone cannot say how old the build is. */
export function macosPublishedDate(): Date | null {
  if (!MACOS_RELEASE.publishedAt) return null;
  const date = new Date(MACOS_RELEASE.publishedAt);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function macosAssetFor(arch: DesktopArch): MacosReleaseAsset | null {
  return MACOS_RELEASE.assets.find((asset) => asset.arch === arch) ?? null;
}

function isWindowsReleasePublished(): boolean {
  return WINDOWS_RELEASE.published && WINDOWS_RELEASE.assets.length === 1;
}

export function windowsAsset(): WindowsReleaseAsset | null {
  if (!isWindowsReleasePublished()) return null;
  return WINDOWS_RELEASE.assets[0] ?? null;
}

/** Decimal MB with one decimal, matching what Finder and Safari show for the same file. */
export function formatAssetSize(sizeBytes: number): string {
  if (!Number.isFinite(sizeBytes) || sizeBytes <= 0) return '';
  return `${(sizeBytes / 1_000_000).toFixed(1)} MB`;
}

export { MACOS_RELEASE };
export type { MacosReleaseAsset, WindowsReleaseAsset };
