/**
 * Ontology construction rules: the single source of every text that tells a
 * model how to build this graph, and of the path heuristics the write gate
 * in `vault/eligibility-gate.mjs` runs. Values live in `schema.mjs`, logic there, text
 * here (`docs/DECISIONS.md`: sibling count is not the target, since a cap is
 * gamed with empty buckets). English only; screen text lives in `messages/*.json`
 * by issue code.
 *
 * Since `src/` cannot import `mcp/`, `src/features/vault-agent/model/system-prompt.ts`
 * carries a literal copy; `tests/contract/vault-schema.contract.test.ts` keeps it
 * byte-aligned and `construction-rules.contract.test.ts` proves the MCP imports.
 */

import {
  NODE_ELIGIBILITY_GATE,
  ONTOLOGY_META_MODEL_REFERENCE,
  VAULT_KIND_SCHEMA,
} from './schema.mjs';

/**
 * Compact meta-model boundary for the MCP prompt and the in-app agent, for when
 * the public specification is unavailable. `src/` cannot import `mcp/`, so the
 * app mirrors it literally, guarded by `tests/contract/ontology-meta-model.contract.test.ts`.
 */
export const META_MODEL_RULES_EN = `## Meta-model truth boundary

Canonical kind, relation, and inference contract: ${ONTOLOGY_META_MODEL_REFERENCE}

Atlas has five authorable kinds: project, domain, capability, element, and
document. \`vault-readme\` is a reserved reader kind generated by Atlas; never
author it. A folder, package, team, workflow, technology, or README heading is
observed evidence, not automatically a domain or capability. A bare path is
evidence for an element role, not a concept by itself.

Direct \`is_a\` is an application-level subsumption claim. The stored key is
\`broader:\`: narrower → direct broader, displayed by the UI as \`is_a\`. Both
endpoints must be the same authorable kind among domain, capability, or element.
Every valid example of the narrower must satisfy the broader definition, and no
known intermediate concept may fit between them. Same domain, name similarity,
and folder nesting are not \`is_a\` evidence; neither are instance/member,
part/containment, dependency, sequence, or synonym claims.

\`broader\` is validated as frontmatter and rendered by the UI, but it is not an
accepted public \`add_relation\` or relation-query enum in the current MCP
contract. To change it safely, call \`get_concept\`, capture \`mtime\`, build the
full post-change \`broader\` array, call \`patch_concept\` with \`expected_mtime\`,
then call \`validate_vault\`. Do not invent an \`add_relation(type:"is_a")\` call.

Atlas performs no automatic inverse or transitive inference. Missing relations
are unknown/visible gaps, not falsehoods or proof of completeness. Atlas Markdown
is not an RDF serialization, OWL reasoner, SKOS implementation, or SHACL processor;
the product makes no RDF, OWL, SKOS, or SHACL conformance claim.`;

/**
 * The procedure a model follows before adding a child to a parent, written as
 * steps rather than judgement so weaker models can follow it. Step 5 never
 * blocks a write: the gate reports, and the person and the maintenance queue decide.
 */
export const CONSTRUCTION_RULES_EN = `## Construction rules — read before add_concept / add_concepts / patch_concept

1. BEFORE adding a child to a parent, call get_concept(parentSlug) and read \`neighbors\`.
2. Count the parent's children that RESOLVE to real vault nodes — an entry that
   resolves to nothing is evidence, not a child, and does not count. Compare that
   against this vault's own distribution (list_kinds /
   query_ontology({operation:'facets'})). Until the vault has enough parents of
   that kind to have a distribution, use this starting range: about ${NODE_ELIGIBILITY_GATE.BOOTSTRAP_FANOUT_TRIGGER.domain_to_capability} capabilities
   under a domain, about ${NODE_ELIGIBILITY_GATE.BOOTSTRAP_FANOUT_TRIGGER.capability_to_element} elements under a capability. Crossing that is a
   TRIGGER for step 3 — NOT a limit. There is no maximum number of children,
   crossing it is not a defect, and it never blocks a write.
3. When triggered, answer before writing:
   a. Can you write ONE non-circular sentence why the new child is NOT interchangeable
      with an existing sibling? If you cannot, patch_concept the existing sibling's
      body instead of creating a new node. THIS IS THE TEST — the other two are hints.
   b. Is the candidate title a file/import path rather than a concept name? A path is
      EVIDENCE of a concept, not the concept — do not create one node per file unless
      each file's role differs in a sentence you can actually write.
   c. Do several existing children share a name/path prefix? Glance at them, but do
      NOT treat this as the condition — prefixed siblings are often legitimate, and
      broken ones often share no prefix. It only tells you where to look first.
4. IF (a) fails for 3+ existing children, the fix is a BRIDGE NODE: one node inserted
   between the parent and those children, named after the behavior they share. Call
   add_concept ONCE for it, then patch_concept each matching child to point at it.
   Create a bridge only when all four hold:
   i.   It names a shared BEHAVIOR. "Group A" / "Part 2" / "Other" divide the pile
        without adding meaning — those are not bridges, they are empty buckets with
        a name on them.
   ii.  You can state that behavior in ONE sentence. If you cannot write the
        sentence, you have not found the grouping yet.
   iii. The bridge itself passes (a) against its own siblings — a bridge that is
        interchangeable with an existing node is a duplicate, not a layer.
   iv.  You actually reparent the children afterwards. A bridge left empty IS the
        empty bucket it was meant to prevent, and it does not go unnoticed: a node
        that groups nothing is reported for retirement.
   IF you cannot satisfy all four: create NOTHING — count alone is not evidence of
   a problem.
5. This procedure does not block writes. Skipping it still succeeds; \`warnings\` /
   \`postWriteMaintenance\` on the response flags it for cleanup instead.
6. When you create a \`capability\`, attach its EVIDENCE in the same pass. Put one
   canonical implementation entry point in \`path:\` — the repo-relative file or
   directory an unfamiliar agent should open first. \`elements:\` contains only
   slugs of real element nodes whose implementation roles differ in a sentence;
   never put a raw file path in that graph relation. A capability with neither
   \`path:\` nor an element relation is a claim nobody can open. This does not block
   the write; the node is reported under \`capability_without_evidence\` in
   \`maintenance_plan\` until it points at something.`;

/**
 * Appended to the add_concept and add_concepts descriptions, the text a model
 * reads right before calling: an element is named after a role, not a file.
 */
export const ELEMENT_NAMING_RULE_EN = `When \`kind\` is \`element\`: an element names a CONCEPT a capability uses (e.g. "jwt-token"), not a file. If your \`title\` is a bare path or ends in a source extension, you are describing evidence, not the concept — rename \`title\` to the role and put the path in \`path:\`, or if 3+ siblings under the same parent already look like this, call \`get_concept\` on the parent and consider \`patch_concept\` on an existing sibling instead of adding another file-mirror node. The same rule binds the \`slug\`: flat under the kind folder (\`elements/<role-name>\`), never a code path (\`elements/src/views/home\` is rejected) — path-style slugs collide the moment two files share a basename and the graph silently merges distinct nodes.`;

/** Batch variant — same rule, stated for the row-wise call shape. */
export const ELEMENT_NAMING_RULE_BATCH_EN = `Rows whose \`title\` is a bare file path follow the same rule as \`add_concept\` above. Prefer one capability node covering a directory plus a short \`elements:\` list over one row per file, unless each file's role differs in a stated sentence.`;

/**
 * Chat-only delta for the in-app agent: the chat talks to a person, so a warning
 * trigger must become a sentence before the tool runs, not a structured field.
 */
export const CHAT_RULES_DELTA_EN = `You are talking to a person, not returning structured \`warnings\` to another program. So when step 4 of the construction rules above would have you create a grouping node, say so in the conversation first, in the language the person is writing to you in, and let them answer before you propose the call. A structured warning a person never opens is not a disclosure — silently reshaping someone's ontology and logging it where only a machine looks is the failure this rule exists to prevent.`;

/**
 * Does this title look like a file path rather than a concept name? The code
 * half of the naming rule, firing whatever the model read. Deliberately narrow (a
 * slash or a source extension, and no internal whitespace, since prose titles
 * contain slashes too): a warning that cries wolf gets filtered out.
 */
export function looksLikePath(title) {
  if (typeof title !== "string") return false;
  const t = title.trim();
  if (t.length === 0) return false;
  if (/\s/.test(t)) return false;
  if (t.includes("/") || t.includes("\\")) return true;
  return /\.(m?[jt]sx?|py|rb|go|rs|java|kt|swift|c|cc|cpp|h|hpp|css|scss|json|ya?ml|toml|sh)$/i.test(t);
}

/**
 * Slugs are slash-separated too, so {@link looksLikePath} cannot tell a file from
 * a slug reference. A reference starting in a kind folder the schema creates
 * claims to be a node; anything else path-shaped claims to be a file.
 */
const VAULT_FOLDER_SEGMENTS = new Set(
  Object.values(VAULT_KIND_SCHEMA)
    .map((schema) => schema.folder)
    .filter(Boolean)
    .map((folder) => folder.replace(/\/$/, '')),
);

/**
 * Is this graph-array entry evidence (a file) rather than a node reference? Never
 * decides a defect: callers ask only about entries that already failed to
 * resolve, and the answer only picks which repair the message names first, so a
 * heuristic is acceptable.
 */
export function looksLikeEvidencePath(ref) {
  if (!looksLikePath(ref)) return false;
  const trimmed = String(ref).trim();
  if (trimmed.includes('\\')) return true;
  const segments = trimmed.split('/');
  if (segments.length === 1) return true; // bare "absorb.mjs" — the extension clause fired
  return !VAULT_FOLDER_SEGMENTS.has(segments[0]);
}

/** Warning literal for {@link looksLikePath}. Advisory — never blocks the write. */
export function pathShapedTitleMessage(title) {
  return `title "${title}" looks like a file path, not a concept name — elements name a role, not a location. If this file plays a distinct role, rename the title to that role and move the path into path:. If it doesn't, patch_concept the parent capability's body instead of adding another file-mirror node.`;
}

/**
 * Action text for a dense parent whose references are mostly broken. It proposes
 * a question, then a call, never a ready-made split (the shortest path to empty
 * buckets), and keeps a "leave it alone" exit so the number never becomes the
 * goal. The test that holds: one non-circular sentence on why a child is not
 * interchangeable with its siblings. `basis` keeps a bootstrap trigger from being
 * printed as the vault's own p90; a shared prefix is only a hint.
 *
 * @param {object} args
 * @param {string} args.parentSlug
 * @param {number} args.count resolved children; unresolved strings are not children
 * @param {string} args.childKind
 * @param {number} args.trigger the number crossed, whatever its basis
 * @param {'vault-p90'|'bootstrap'} args.basis where `trigger` came from
 * @param {string} args.evidence why this parent was looked at
 */
export function denseParentActionMessage({ parentSlug, count, childKind, trigger, basis, evidence }) {
  const source = basis === 'vault-p90'
    ? `this vault's own p90 for ${childKind} parents is ${trigger}`
    : `the starting range for ${childKind} children is ${trigger} (this vault has too few ${childKind} parents yet for its own percentile to mean anything)`;
  return `"${parentSlug}" has ${count} ${childKind} children that resolve to real nodes, and ${source}. That number is a trigger, not a limit — nothing here caps how many children a node may have, and a wide parent whose children each earn their place is correct. What made this worth mentioning is ${evidence}. Call get_concept("${parentSlug}") and answer one question per child: can you write a non-circular sentence saying why it is NOT interchangeable with its siblings? For every child where you can, leave it alone. Where you cannot for three or more, those children want a BRIDGE NODE — one node named after the behavior they share, with them reparented onto it; the construction rules list the four conditions a bridge has to meet, and a bridge you leave empty is reported back to you for retirement. Shared name prefixes are a hint worth glancing at, not the test — in this vault, prefixed siblings have been legitimate and the broken ones shared no prefix at all.`;
}

/** The count plus a few examples: pasting every ref is unread by a person and costs an agent context. */
function sampleRefs(refs, limit) {
  const shown = refs.slice(0, limit).map((ref) => `"${ref}"`).join(', ');
  const rest = refs.length - Math.min(refs.length, limit);
  return rest > 0 ? `${shown} and ${rest} more` : shown;
}

/**
 * Warning literal for an entry a kind change could not move: the referrer's kind
 * keeps no list for the new kind (spec §5), so the entry stays, still resolves,
 * and fires no compile warning. Only the writer knows, so the writer says it.
 */
export function containmentEntryKeptMessage({ slug, key, ref, holderKind, newKind }) {
  const holder = holderKind ? `a ${holderKind}` : 'a document with no kind';
  return `"${slug}" still lists "${ref}" under ${key}:, but "${ref}" is now a ${newKind} and ${holder} keeps no list for a ${newKind}, so the entry was left where it was rather than guessed into another relation. Readers still count it as one of "${slug}"'s ${key}. Decide what "${slug}" means by it: remove_relation({from:"${slug}", to:"${ref}", type:"${key}"}) drops it, and add_relation with the type that fits restates it.`;
}

/**
 * Warning literal for a graph-array entry that resolves to no node. It names both
 * exits and carries no `proposedAction`: a literal "create the node" makes an
 * agent manufacture one node per unresolved string.
 */
export function danglingGraphReferenceMessage({ slug, key, refs, count, sampleLimit }) {
  return `${count} entry/entries in "${slug}".${key} resolve to no vault node: ${sampleRefs(refs, sampleLimit)}. A relation array is a claim that a node exists; an unresolved string is not a child, it is a name with nothing behind it. Either promote it — add_concept({slug, kind, title}) for the concept it names, then keep the reference — or drop it from ${key}: and record what it points at as evidence on this node instead. Do not leave it in a meaning slot.`;
}

/**
 * Warning literal for a file path in a graph-relation array. validate_vault
 * exempts path-shaped `elements:` entries (`isPathLikeGraphRef`) and the
 * compiler only prescribes "create a node per file", so only the write path can
 * say "this does not belong here".
 */
export function pathShapedReferenceMessage({ slug, key, refs, count, sampleLimit }) {
  return `${count} entry/entries in "${slug}".${key} are file paths, not concept names: ${sampleRefs(refs, sampleLimit)}. A path is EVIDENCE for a concept, not the concept — it names where something lives, so it cannot be a child in the graph. For each one, either write the sentence that says what distinct role that file plays and promote it with add_concept({kind:"element", title:"<the role>", path:"<the path>"}), or remove it from ${key}: and keep the path as evidence on "${slug}" (frontmatter path: / the node body). One node per file, mirroring a directory listing, is the failure this check exists to stop.`;
}

/**
 * Warning literal for a capability created with no evidence, at creation only:
 * "name the behaviour, then attach the file" is an honest two-step,
 * and `maintenance_plan`'s `capability_without_evidence` keeps asking afterwards.
 * Never rejects (construction rule 5).
 */
export function capabilityWithoutEvidenceMessage({ slug }) {
  return `"${slug}" is a capability with neither a canonical \`path:\` entrypoint nor an \`elements:\` relation to a real implementation concept, so nothing in the vault says where this behavior lives in code. The write succeeded and nothing here blocks it — but an agent handed only this vault can describe this capability and cannot open it. Attach evidence while you still have the file in hand: patch_concept({slug:"${slug}", frontmatter:{path:"<repo-relative file or directory>"}}). Create an element node only when a distinct implementation role earns ontology identity. Until it points at something, this node is listed under \`capability_without_evidence\` in query_ontology({operation:"maintenance_plan"}).`;
}

/**
 * Warning literal for siblings born under one parent in one run: provenance, not
 * population, which only the write path can see. The "leave it alone" branch
 * keeps the trigger from becoming a target.
 */
export function bulkProvenanceMessage({ parent, count, slugs, sampleLimit }) {
  return `${count} nodes were created under "${parent}" in this session: ${sampleRefs(slugs, sampleLimit)}. That is a provenance signal, not a size limit — there is no maximum number of children here. Call get_concept("${parent}") and answer one question: can you write a non-circular sentence saying why each of these is NOT interchangeable with its siblings? If yes, this is a legitimately wide parent — leave it exactly as it is. If no, name the shared behavior once with add_concept and patch_concept the siblings that share it to point at that node instead.`;
}

/*
 * Meaning gaps in the body. Every real build lands through add_concept and
 * patch_concept, so this door must say what is thin (starter body, evidence
 * limits under Excludes, folder evidence) while the author has the file open.
 * Advisory (construction rule 5); logic in `meaning-findings.mjs`, text here.
 */

/**
 * Heading names for each side of a concept's boundary (spec §2.1 asks for both),
 * including the synonyms vaults already use so a filled section is read as is.
 * Test the negative side first: "out of scope" contains "scope".
 */
export const BODY_BOUNDARY_SECTIONS = Object.freeze({
  includes: Object.freeze(['includes', 'inclusions', 'in scope', 'scope', 'boundary', 'constraints']),
  excludes: Object.freeze(['excludes', 'exclusions', 'out of scope', 'not this']),
});

/**
 * Does this exclusion state an evidence limit ("not mentioned in this scan")
 * rather than a product boundary? A source-hidden reader repeats the first as
 * the second. Here, beside the schema-only imports, so `meaning-evaluation.mjs`
 * and `meaning-findings.mjs` share one implementation without an import cycle.
 */
export function isEpistemicExclusionBoundary(value) {
  const normalized = String(value).replace(/\s+/g, ' ').trim().toLowerCase();
  return EPISTEMIC_EXCLUSION_PATTERNS.some((pattern) => pattern.test(normalized));
}

/**
 * Evidence-limit phrasings. Each clause stays tied to a reading verb ("inspect",
 * "read", "trace", "carried as a node") so an ordinary product boundary such as
 * "flags, which are options rather than positional arguments" does not match.
 */
const EPISTEMIC_EXCLUSION_PATTERNS = Object.freeze([
  /\bnot\s+(?:established|asserted|proven|verified|measured|observed|known|confirmed)\b/,
  /\bremain(?:s|ed)?\s+outside\s+(?:this|the)\s+(?:bounded\s+)?(?:scan|evidence)\b/,
  /\bnot\s+(?:named|listed|mentioned|included|covered|present)\s+in\s+(?:this|the)\s+(?:bounded\s+)?(?:semantic\s+)?(?:excerpt|evidence|scan|packet)\b/,
  // "this survey did not inspect" / "the pass did not reach"
  /\b(?:this|the|our)\s+(?:survey|scan|pass|packet|excerpt|read|analysis|review|session)\s+did\s+not\s+(?:inspect|read|trace|scan|cover|open|look\s+at|examine|visit)\b/,
  // "which was not read" / "were not inspected"
  /\b(?:was|were)\s+not\s+(?:read|inspected|traced|scanned|covered|opened|examined|visited|analysed|analyzed|reviewed)\b/,
  // "is not carried as a node": the graph has not caught up, which says nothing
  // about the product.
  /\bnot\s+(?:yet\s+)?(?:carried|represented|modelled|modeled|captured)\s+(?:as|in)\b/,
  /\b(?:unread|uninspected|untraced|unscanned)\b/,
  /\bnot\s+(?:yet\s+)?(?:inspected|read|traced)\s+in\s+this\s+(?:first\s+)?(?:pass|survey|scan|round)\b/,
  /\b(?:did\s+not|didn't|could\s+not|couldn't)\s+(?:get\s+to|reach|cover|read)\b/,
  /\boutside\s+(?:what|the\s+files)\s+(?:this|the)\s+(?:survey|scan|pass)\s+(?:read|covered|inspected)\b/,
]);

/**
 * Heading names that carry the node's definition. The qualification lane writes
 * it under `## Definition` with nothing above, so the lead paragraph alone is
 * not the definition.
 */
export const BODY_DEFINITION_SECTIONS = Object.freeze([
  'definition',
  'summary',
  'what it is',
  'what this is',
  'overview',
]);

/** Warning literal for a node whose body never says what the node is. */
export function definitionMissingMessage({ slug, kind }) {
  return `"${slug}" is a ${kind} whose body carries no definition — it is still the starter scaffold, it opens straight into headings, or it only restates the title. The write succeeded and nothing here blocks it; what is missing is the one sentence that makes this a concept instead of a label. Write what this ${kind} is and what it is not, in prose before the first \`##\` or under \`## Definition\`: patch_concept({slug:"${slug}", body:"# <title>\\n\\n<one non-circular sentence: what it is, and what it is not>\\n\\n…"}). An agent handed only this vault can read the title and learn nothing it did not already know from the title.`;
}

/** Warning literal for a boundary side the body never states. */
export function boundaryMissingMessage({ slug, kind, side }) {
  const heading = side === 'excludes' ? 'Excludes' : 'Includes';
  const other = side === 'excludes' ? 'what this is often confused with and is not' : 'what this covers';
  return `"${slug}" (${kind}) has no \`## ${heading}\` section with anything in it, so the body never states ${other}. The write succeeded; this is the half of the boundary the next reader cannot reconstruct from code, because there is no code for a thing deliberately left out. Add it with patch_concept({slug:"${slug}", body:"…\\n\\n## ${heading}\\n\\n- <one concrete item>\\n"}) — one real bullet is worth more than the placeholder, and a placeholder bullet still counts as empty here.`;
}

/**
 * Warning literal for an exclusion that states an evidence limit, judged by
 * {@link isEpistemicExclusionBoundary}, the qualification lane's rule, so the two
 * lanes cannot disagree about one sentence.
 */
export function epistemicExclusionMessage({ slug, refs, count, sampleLimit }) {
  return `${count} exclusion bullet(s) on "${slug}" state an evidence limit rather than a product boundary: ${sampleRefs(refs, sampleLimit)}. "Not mentioned in this scan" says what the writer did not see; an \`Excludes\` bullet says what the product deliberately does not do. A reader handed the vault without the source cannot tell those apart, and repeats the first as the second — measured in the 2026-08-28 field trial. The write succeeded; move each one to an \`## Uncertainty\` (or \`## Open questions\`) section with patch_concept({slug:"${slug}", body:"…"}), and leave in \`Excludes\` only what a source actually supports.`;
}

/** Warning literal for evidence that names a folder instead of a file. */
export function folderOnlyEvidenceMessage({ slug, path, suggestion }) {
  const opener = suggestion
    ? `Name the one file an unfamiliar agent should open first — \`${suggestion}\` is what this folder offers as an entry point`
    : 'Name the one file an unfamiliar agent should open first';
  return `"${slug}" cites \`path: ${path}\`, and that is a directory. The write succeeded, but drift on a folder can never be checked: a folder's timestamp moves on almost any commit underneath it, so this node's evidence is permanently "unknown" rather than current or stale. ${opener}: patch_concept({slug:"${slug}", frontmatter:{path:"${suggestion || `${path.replace(/\/$/, '')}/<file>`}"}}). Keep the folder in the body as context if it matters; the frontmatter slot is for the one entry point.`;
}

/**
 * Warning literal for a node written outside its kind's folder, the convention no
 * other channel states. Never rejects: unlike `flatSlugIssue`'s hard error on a
 * path-style slug nested under a kind folder (which merges nodes sharing a
 * basename), a flat root slug merges nothing and only reads worse.
 *
 * @param {object} args
 * @param {string} args.slug the slug as written
 * @param {string} args.kind
 * @param {string} args.canonicalSlug the same node's name inside its folder
 */
export function slugOutsideKindFolderMessage({ slug, kind, canonicalSlug }) {
  return `"${slug}" is a ${kind} written at the vault root instead of inside its kind folder, so it reads as "${slug}" where every other ${kind} reads as "${canonicalSlug}". The write succeeded and nothing here blocks it — a flat slug is valid, it just groups with nothing. The map, the README generator, and every other reader that shows a vault by kind group on that folder, so a root-level ${kind} sits beside the project node rather than with its own kind. Move it when you are ready: rename_concept({oldSlug:"${slug}", newSlug:"${canonicalSlug}"}) without \`confirm\` returns a dry-run listing every backlink that would be rewritten; repeat the same call with \`confirm: true\` to move the file and rewrite them in one pass. The UID does not change, so nothing loses its identity.`;
}

/**
 * Heading names for what the writer did not check. A node with no stated unknown
 * claims completeness, and which files were not read is what a later reader most
 * needs; `confidence` is accepted because vaults already use it for this.
 */
export const BODY_UNCERTAINTY_SECTIONS = Object.freeze([
  'uncertainty',
  'open questions',
  'unknowns',
  'not checked',
  'confidence',
]);

/** Warning literal for a node that records no unknown at all. */
export function uncertaintyMissingMessage({ slug, kind }) {
  return `"${slug}" (${kind}) records no uncertainty, so the body reads as complete — and nothing in a vault is. The write succeeded and nothing here blocks it; what is missing is the fact a later reader most needs and can least recover: which files you did not open, which claim you inferred rather than read, what you could not check. Without it an agent handed only this vault treats every silence as a settled negative. Say it plainly: patch_concept({slug:"${slug}", body:"…\\n\\n## Uncertainty\\n\\n- <what you did not read or could not check>\\n"}). \`## Open questions\`, \`## Unknowns\`, \`## Not checked\` and \`## Confidence\` are read as the same section, and this is also where an \`Excludes\` bullet belongs once you notice it was an evidence limit rather than a product boundary.`;
}

/**
 * Keys holding a declared dependency edge; `depends_on:` is the authoring alias.
 */
export const DEPENDENCY_FRONTMATTER_KEYS = Object.freeze(['dependencies', 'depends_on']);

/**
 * Warning literal for a declared dependency the citing file does not witness.
 * It asks for the witness, not removal: an import is evidence of a dependency,
 * but its absence is not evidence of independence (runtime lookups, build
 * steps, config and spawned processes leave no mention). Removal is offered only
 * for an edge inferred from look-alike names. The check reads the files the `why`
 * names, so the sentence says repository-relative out loud: a partial path is
 * never guessed. Advisory (construction rule 5).
 */
export function dependencyUnjudgedMessage({ slug, target, unreadPaths, maxBytes }) {
  return `"${slug}" declares a dependency on "${target}", but ${unreadPaths.map((path) => `\`${path}\``).join(' and ')} ${unreadPaths.length > 1 ? 'are' : 'is'} larger than ${maxBytes / 1024 / 1024} MiB, so no witness was looked for there and the edge is not judged. Cite a smaller file in \`path:\`, or name the file that imports the target in this relation's \`why\`.`;
}

export function dependencyUnwitnessedMessage({ slug, sourcePath, target, targetPath, witnessName }) {
  return `"${slug}" declares a dependency on "${target}", and \`${sourcePath}\` never brings \`${targetPath}\` in — no import, require, use or include names \`${witnessName}\`, and the path appears nowhere in that file. The write succeeded and nothing here blocks it. A file importing the file it depends on is evidence of a code dependency; a bare word is not, and not importing it is **not** proof of independence, because a dependency carried by a runtime lookup, a build step, or a configuration key is real and leaves no mention in the source. So state the witness instead of deleting the edge: in the \`why\`, name the file that imports or calls the target and the line it does it on — **repository-relative, the way \`path:\` is written**, because the check opens that file and reads it. \`src/features/thing/index.ts:42\` is read; \`thing/index.ts:42\` is not a path from the repository root, so it is ignored and this finding stands. A \`why\` naming a readable file clears this once that file really does import \`${targetPath}\`. That is how a cross-boundary dependency gets witnessed at all: browser code depending on an MCP module, or TypeScript on Rust, is proved by the barrel, the bridge or the contract test that binds them, never by either end alone. Write it with replace_relation({from:"${slug}", oldTo:"${target}", oldType:"depends_on", newTo:"${target}", newType:"depends_on", why:"<file>:<line> — what the source does with the target", confirm:true}), or write the same sentence straight into the note with patch_concept({slug:"${slug}", frontmatter:{relation_notes:{"${target}":"<file>:<line> — …"}}}). If the edge came from the two names looking alike rather than from something you read, remove it: remove_relation({from:"${slug}", to:"${target}", type:"depends_on", confirm:true}).`;
}

/**
 * The three nodes `init` writes into a new vault. The templates in
 * cli/templates/vault/** and cli/templates/vault-ko/** and the browser's
 * src/entities/vault-session/lib/ontology-starter.ts use the same addresses.
 */
export const STARTER_EXAMPLE_SLUGS = Object.freeze({
  domain: 'domains/example-domain',
  capability: 'capabilities/example-capability',
  element: 'elements/example-element',
});

/**
 * Sentences only the untouched starter body carries. They only strengthen the
 * message; slug and title decide, so an edited body keeping the starter name
 * still fires.
 */
export const STARTER_EXAMPLE_BODY_MARKERS = Object.freeze([
  'this file is a starter, not an observation',
  '## How to fill it in',
]);

/**
 * Warning literal for an `init` starter example left beside real nodes. It fires
 * once a real sibling of its kind exists: alone, the starter is instructions;
 * beside real nodes it is a fake concept on the map. Advisory: deleting a file
 * is not the gate's decision.
 */
export function starterExampleNodeMessage({ starterSlug, kind, realSlug, renameTo, untouchedBody }) {
  const bodyNote = untouchedBody
    ? ` Its body is still the starter's own explanation of what a ${kind} is, so a reader who opens it asking what this ${kind} does gets a definition of the word instead.`
    : '';
  const sibling = realSlug
    ? `"${realSlug}" is now a real ${kind} beside it`
    : `this vault now holds a real ${kind} beside it`;
  return `"${starterSlug}" is the ${kind} the \`init\` starter wrote as a shape to copy, and ${sibling}. The write succeeded and nothing here blocks it. While the starter was the only ${kind} in the vault it was instructions; now it is a fake concept sitting on the map next to the real ones, and the only relations it has run to the other two starter examples.${bodyNote} Delete it: delete_concept({slug:"${starterSlug}"}) without \`confirm\` returns a dry-run listing its backlinks first — they are the other two starter examples, so delete all three together and the graph loses nothing. If you meant to keep this one, it is not a starter any more: patch_concept it into a real concept, then give it a real address with rename_concept({oldSlug:"${starterSlug}", newSlug:"${renameTo}", confirm:true}). The UID does not change, so nothing loses its identity.`;
}
